<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Materials for the MSc Statistics and Research Design course at the University of Glasgow.">
<title>2&nbsp; Regression with one categorical predictor – Statistics and Research Design</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./01-03-lm-multiple.html" rel="next">
<link href="./01-01-lm-continuous.html" rel="prev">
<link href="./images/logos/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-6NP3MF25W3', { 'anonymize_ip': true});
</script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" href="include/booktem.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/glossary.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-00-GLM.html">General linear model</a></li><li class="breadcrumb-item"><a href="./01-02-lm-categorical.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression with one categorical predictor</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics and Research Design</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./01-00-GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">General linear model</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-01-lm-continuous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Regression with one continuous predictor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-02-lm-categorical.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression with one categorical predictor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-03-lm-multiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-04-screening-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Missing data, outliers, and checking assumptions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-05-glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Generalised Linear Regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./02-00-graph_robust.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Graphical representations and robust statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-07-gar-ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-08-gar-gpcomp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Perspectives on group comparisons</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-a-installing-brms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Installing the <code>brms</code> package</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#chapter-preparation" id="toc-chapter-preparation" class="nav-link active" data-scroll-target="#chapter-preparation"><span class="header-section-number">2.1</span> Chapter preparation</a>
  <ul class="collapse">
<li><a href="#introduction-to-the-data-set" id="toc-introduction-to-the-data-set" class="nav-link" data-scroll-target="#introduction-to-the-data-set"><span class="header-section-number">2.1.1</span> Introduction to the data set</a></li>
  <li><a href="#organising-your-files-and-project-for-the-chapter" id="toc-organising-your-files-and-project-for-the-chapter" class="nav-link" data-scroll-target="#organising-your-files-and-project-for-the-chapter"><span class="header-section-number">2.1.2</span> Organising your files and project for the chapter</a></li>
  <li><a href="#activity-1---read-and-wrangle-the-data" id="toc-activity-1---read-and-wrangle-the-data" class="nav-link" data-scroll-target="#activity-1---read-and-wrangle-the-data"><span class="header-section-number">2.1.3</span> Activity 1 - Read and wrangle the data</a></li>
  <li><a href="#09-explore" id="toc-09-explore" class="nav-link" data-scroll-target="#09-explore"><span class="header-section-number">2.1.4</span> Activity 2 - Explore the data</a></li>
  </ul>
</li>
  <li>
<a href="#comparing-differences-using-the-t-test" id="toc-comparing-differences-using-the-t-test" class="nav-link" data-scroll-target="#comparing-differences-using-the-t-test"><span class="header-section-number">2.2</span> Comparing differences using the t-test</a>
  <ul class="collapse">
<li><a href="#activity-3---visualising-the-difference" id="toc-activity-3---visualising-the-difference" class="nav-link" data-scroll-target="#activity-3---visualising-the-difference"><span class="header-section-number">2.2.1</span> Activity 3 - Visualising the difference</a></li>
  <li><a href="#activity-4---using-the-t.test-function" id="toc-activity-4---using-the-t.test-function" class="nav-link" data-scroll-target="#activity-4---using-the-t.test-function"><span class="header-section-number">2.2.2</span> Activity 4 - Using the <code>t.test()</code> function</a></li>
  <li><a href="#activity-5---calculating-cohens-d" id="toc-activity-5---calculating-cohens-d" class="nav-link" data-scroll-target="#activity-5---calculating-cohens-d"><span class="header-section-number">2.2.3</span> Activity 5 - Calculating Cohen’s d</a></li>
  </ul>
</li>
  <li>
<a href="#09-categorical" id="toc-09-categorical" class="nav-link" data-scroll-target="#09-categorical"><span class="header-section-number">2.3</span> Linear regression with one categorical predictor</a>
  <ul class="collapse">
<li><a href="#activity-6---descriptive-statistics" id="toc-activity-6---descriptive-statistics" class="nav-link" data-scroll-target="#activity-6---descriptive-statistics"><span class="header-section-number">2.3.1</span> Activity 6 - Descriptive statistics</a></li>
  <li><a href="#activity-7---using-the-lm-function" id="toc-activity-7---using-the-lm-function" class="nav-link" data-scroll-target="#activity-7---using-the-lm-function"><span class="header-section-number">2.3.2</span> Activity 7 - Using the <code>lm()</code> function</a></li>
  <li><a href="#activity-8---calculating-confidence-intervals" id="toc-activity-8---calculating-confidence-intervals" class="nav-link" data-scroll-target="#activity-8---calculating-confidence-intervals"><span class="header-section-number">2.3.3</span> Activity 8 - Calculating confidence intervals</a></li>
  <li><a href="#activity-9---standardising-predictors" id="toc-activity-9---standardising-predictors" class="nav-link" data-scroll-target="#activity-9---standardising-predictors"><span class="header-section-number">2.3.4</span> Activity 9 - Standardising predictors</a></li>
  </ul>
</li>
  <li>
<a href="#checking-assumptions" id="toc-checking-assumptions" class="nav-link" data-scroll-target="#checking-assumptions"><span class="header-section-number">2.4</span> Checking assumptions</a>
  <ul class="collapse">
<li><a href="#activity-10---diagnostic-plots-for-linear-regression" id="toc-activity-10---diagnostic-plots-for-linear-regression" class="nav-link" data-scroll-target="#activity-10---diagnostic-plots-for-linear-regression"><span class="header-section-number">2.4.1</span> Activity 10 - Diagnostic plots for linear regression</a></li>
  <li><a href="#checking-linearity" id="toc-checking-linearity" class="nav-link" data-scroll-target="#checking-linearity"><span class="header-section-number">2.4.2</span> Checking linearity</a></li>
  <li><a href="#checking-normality" id="toc-checking-normality" class="nav-link" data-scroll-target="#checking-normality"><span class="header-section-number">2.4.3</span> Checking normality</a></li>
  <li><a href="#checking-homoscedasticity" id="toc-checking-homoscedasticity" class="nav-link" data-scroll-target="#checking-homoscedasticity"><span class="header-section-number">2.4.4</span> Checking homoscedasticity</a></li>
  <li><a href="#checking-influential-cases" id="toc-checking-influential-cases" class="nav-link" data-scroll-target="#checking-influential-cases"><span class="header-section-number">2.4.5</span> Checking influential cases</a></li>
  <li><a href="#checking-all-the-assumptions" id="toc-checking-all-the-assumptions" class="nav-link" data-scroll-target="#checking-all-the-assumptions"><span class="header-section-number">2.4.6</span> Checking all the assumptions</a></li>
  </ul>
</li>
  <li><a href="#reporting-your-results" id="toc-reporting-your-results" class="nav-link" data-scroll-target="#reporting-your-results"><span class="header-section-number">2.5</span> Reporting your results</a></li>
  <li>
<a href="#09-bonus" id="toc-09-bonus" class="nav-link" data-scroll-target="#09-bonus"><span class="header-section-number">2.6</span> One- and paired-samples tests</a>
  <ul class="collapse">
<li><a href="#activity-11---one-sample-comparing-against-a-fixed-value" id="toc-activity-11---one-sample-comparing-against-a-fixed-value" class="nav-link" data-scroll-target="#activity-11---one-sample-comparing-against-a-fixed-value"><span class="header-section-number">2.6.1</span> Activity 11 - One-sample comparing against a fixed value</a></li>
  <li><a href="#activity-12---paired-samples-comparing-conditions" id="toc-activity-12---paired-samples-comparing-conditions" class="nav-link" data-scroll-target="#activity-12---paired-samples-comparing-conditions"><span class="header-section-number">2.6.2</span> Activity 12 - Paired-samples comparing conditions</a></li>
  </ul>
</li>
  <li><a href="#09-test" id="toc-09-test" class="nav-link" data-scroll-target="#09-test"><span class="header-section-number">2.7</span> Test Yourself</a></li>
  <li><a href="#words-from-this-chapter" id="toc-words-from-this-chapter" class="nav-link" data-scroll-target="#words-from-this-chapter"><span class="header-section-number">2.8</span> Words from this Chapter</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-00-GLM.html">General linear model</a></li><li class="breadcrumb-item"><a href="./01-02-lm-categorical.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression with one categorical predictor</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression with one categorical predictor</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>In these first two chapters, we focus on simple linear regression for testing research questions and hypotheses. We are starting slow and demonstrating how common statistical tests such as correlation and t-tests are specific applications of the general linear model (<a href="https://lindeloev.github.io/tests-as-linear/" target="_blank">Lindeløv, 2019</a>). With inferential statistics, we want to test our research questions and hypotheses by analysing the data given the research design you are working with. By adopting a modelling approach, you will have far more flexibility to adapt to the design you are working with.</p>
<p>In this chapter, we explore the concepts of t-tests as those specific applications compared to recreating them using linear regression. We also have a bonus section on expressing a one-sample and paired-samples design as linear models.</p>
<p><strong>Chapter Intended Learning Outcomes (ILOs)</strong></p>
<p>By the end of this chapter, you will be able to:</p>
<ul>
<li><p>Visualise the difference between two groups on an outcome.</p></li>
<li><p>Apply and interpret a Student and Welch t-test.</p></li>
<li><p>Apply and interpret linear regression with one categorical predictor variable.</p></li>
<li><p>Apply and interpret linear regression adapted to one-sample and paired-samples designs.</p></li>
</ul>
<section id="chapter-preparation" class="level2" data-number="2.1"><h2 data-number="2.1" class="anchored" data-anchor-id="chapter-preparation">
<span class="header-section-number">2.1</span> Chapter preparation</h2>
<section id="introduction-to-the-data-set" class="level3" data-number="2.1.1"><h3 data-number="2.1.1" class="anchored" data-anchor-id="introduction-to-the-data-set">
<span class="header-section-number">2.1.1</span> Introduction to the data set</h3>
<p>For most of this chapter, we are using open data from <span class="citation" data-cites="lopez_visual_2023">Lopez et al. (<a href="references.html#ref-lopez_visual_2023" role="doc-biblioref">2023</a>)</span>. The abstract of their article is:</p>
<blockquote class="blockquote">
<p>Imagine a bowl of soup that never emptied, no matter how many spoonfuls you ate—when and how would you know to stop eating? Satiation can play a role in regulating eating behavior, but research suggests visual cues may be just as important. In a seminal study by Wansink et al.&nbsp;(2005), researchers used self-refilling bowls to assess how visual cues of portion size would influence intake. The study found that participants who unknowingly ate from self-refilling bowls ate more soup than did participants eating from normal (not self-refilling) bowls. Despite consuming 73% more soup, however, participants in the self-refilling condition did not believe they had consumed more soup, nor did they perceive themselves as more satiated than did participants eating from normal bowls. Given recent concerns regarding the validity of research from the Wansink lab, we conducted a preregistered direct replication study of Wansink et al.&nbsp;(2005) with a more highly powered sample (N = 464 vs.&nbsp;54 in the original study). We found that most results replicated, albeit with half the effect size (d = 0.45 instead of 0.84), with participants in the self-refilling bowl condition eating significantly more soup than those in the control condition. Like the original study, participants in the selfrefilling condition did not believe they had consumed any more soup than participants in the control condition. These results suggest that eating can be strongly controlled by visual cues, which can even override satiation.</p>
</blockquote>
<p>In summary, they replicated an (in)famous experiment that won the Ig-Nobel prize. Participants engaged in a intricate setting (seriously, go and look at the diagrams in the article) where they ate soup from bowls on a table. In the control group, participants could eat as much soup as they wanted and could ask for a top-up from the researchers. In the experimental group, the soup bowls automatically topped up through a series of hidden tubes under the table. The idea behind the control group is they get an accurate visual cue by the soup bowl reducing, and the experimental group get an inaccurate visual cue by the soup bowl seemingly never reducing. So, the inaccurate visual cue would interfere with natural signs of getting full and lead to people eating more.</p>
<p>In the original article, participants in the experimental group ate more soup than participants in the control group, but the main author was involved in a series of research misconduct cases. <span class="citation" data-cites="lopez_visual_2023">Lopez et al. (<a href="references.html#ref-lopez_visual_2023" role="doc-biblioref">2023</a>)</span> wanted to see if the result would replicate in an independent study, so they predicted they would find the same results. In this chapter, we will explore the difference between the control and experimental groups on several variables in their data set.</p>
</section><section id="organising-your-files-and-project-for-the-chapter" class="level3" data-number="2.1.2"><h3 data-number="2.1.2" class="anchored" data-anchor-id="organising-your-files-and-project-for-the-chapter">
<span class="header-section-number">2.1.2</span> Organising your files and project for the chapter</h3>
<p>Before we can get started, you need to organise your files and project for the chapter, so your working directory is in order.</p>
<ol type="1">
<li><p>In your folder for statistics and research design <code>Stats_Research_Design</code>, create a new folder called <code>02_regression_categorical</code>. Within <code>02_regression_categorical</code>, create two new folders called <code>data</code> and <code>figures</code>.</p></li>
<li><p>Create an R Project for <code>02_regression_categorical</code> as an existing directory for your chapter folder. This should now be your working directory.</p></li>
<li><p>Create a new Quarto document and give it a sensible title describing the chapter, such as <code>02 t-tests and Regression</code>. Save the file in your <code>02_regression_categorical</code> folder.</p></li>
<li><p>We are working with a new data set, so please save the following data file: <a href="data/Lopez_2023.csv">Lopez_2023.csv</a>. Right click the link and select “save link as”, or clicking the link will save the files to your Downloads. Make sure that you save the file as “.csv”. Save or copy the file to your <code>data/</code> folder within <code>02_regression_categorical</code>.</p></li>
</ol>
<p>You are now ready to start working on the chapter!</p>
</section><section id="activity-1---read-and-wrangle-the-data" class="level3" data-number="2.1.3"><h3 data-number="2.1.3" class="anchored" data-anchor-id="activity-1---read-and-wrangle-the-data">
<span class="header-section-number">2.1.3</span> Activity 1 - Read and wrangle the data</h3>
<p>As the first activity, try and test yourself by completing the following task list to practice your data wrangling skills. In this example, there is not loads to do, you just need to tidy up some variables. Create a final object called <code>lopez_clean</code> to be consistent with the tasks below. If you want to focus on t-tests and regression, then you can just type the code in the solution.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try this
</div>
</div>
<div class="callout-body-container callout-body">
<p>To wrangle the data, complete the following tasks:</p>
<ol type="1">
<li>
<p>Load the following packages:</p>
<ul>
<li><p><pkg>tidyverse</pkg></p></li>
<li><p><pkg>effectsize</pkg></p></li>
<li><p><pkg>performance</pkg></p></li>
</ul>
</li>
<li><p>Read the data file <code>data/Lopez_2023.csv</code> to the object name <code>lopez_data</code>.</p></li>
<li>
<p>Create a new object called <code>lopez_clean</code> based on <code>lopez_data</code>:</p>
<ul>
<li><p>Modify the variable <code>Condition</code> to turn it into a factor.</p></li>
<li><p>Create a new variable called <code>Condition_label</code> by recoding <code>Condition</code>. “0” is the “Control” group and “1” is the “Experimental” group.</p></li>
</ul>
</li>
</ol>
<p>Your data should look like this to be ready to analyse:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 464
Columns: 10
$ ParticipantID      &lt;dbl&gt; 1002, 1004, 1007, 1016, 1018, 1021, 1022, 1024, 102…
$ Sex                &lt;dbl&gt; 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, …
$ Age                &lt;dbl&gt; 18, 19, 19, 21, 20, 20, 21, 21, 19, 20, 21, 20, 21,…
$ Ethnicity          &lt;dbl&gt; 7, 3, 3, 4, 1, 3, 1, 6, 4, 7, 1, 3, 3, 4, 7, 2, 3, …
$ OzEstimate         &lt;dbl&gt; 3.0, 2.0, 1.0, 3.0, 5.0, 1.0, 1.0, 3.0, 4.0, 1.0, 4…
$ CalEstimate        &lt;dbl&gt; 65, 10, 20, 25, 50, 5, 20, 180, 470, 50, 130, 100, …
$ M_postsoup         &lt;dbl&gt; 3.3, 3.1, 43.4, 5.5, 6.0, 0.8, 3.8, 4.5, 7.9, 8.1, …
$ F_CaloriesConsumed &lt;dbl&gt; 73.19441, 68.75839, 962.61743, 121.99069, 133.08075…
$ Condition          &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ Condition_label    &lt;chr&gt; "Control", "Control", "Control", "Control", "Contro…</code></pre>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You should have the following in a code chunk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># load the relevant packages</span></span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="fu">library</span>(performance)</span>
<span id="cb2-4"><a href="#cb2-4"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-5"><a href="#cb2-5"></a></span>
<span id="cb2-6"><a href="#cb2-6"></a><span class="co"># Read the Lopez_2023.csv file </span></span>
<span id="cb2-7"><a href="#cb2-7"></a>lopez_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Lopez_2023.csv"</span>)</span>
<span id="cb2-8"><a href="#cb2-8"></a></span>
<span id="cb2-9"><a href="#cb2-9"></a><span class="co"># turn condition into a factor and recode</span></span>
<span id="cb2-10"><a href="#cb2-10"></a>lopez_clean <span class="ot">&lt;-</span> lopez_data <span class="sc">%&gt;%</span> </span>
<span id="cb2-11"><a href="#cb2-11"></a>  <span class="fu">mutate</span>(<span class="at">Condition =</span> <span class="fu">as.factor</span>(Condition),</span>
<span id="cb2-12"><a href="#cb2-12"></a>         <span class="at">Condition_label =</span> <span class="fu">case_match</span>(Condition,</span>
<span id="cb2-13"><a href="#cb2-13"></a>                                      <span class="st">"0"</span> <span class="sc">~</span> <span class="st">"Control"</span>,</span>
<span id="cb2-14"><a href="#cb2-14"></a>                                      <span class="st">"1"</span> <span class="sc">~</span> <span class="st">"Experimental"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="09-explore" class="level3" data-number="2.1.4"><h3 data-number="2.1.4" class="anchored" data-anchor-id="09-explore">
<span class="header-section-number">2.1.4</span> Activity 2 - Explore the data</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try this
</div>
</div>
<div class="callout-body-container callout-body">
<p>After the wrangling steps, try and explore <code>lopez_clean</code> to see what variables you are working with. For example, opening the data object as a tab to scroll around, explore with <code>glimpse()</code>, or try plotting some of the individual variables.</p>
</div>
</div>
<p>In <code>lopez_clean</code>, we have the following variables:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 41%">
<col style="width: 39%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">Variable</th>
<th style="text-align: left;">Type</th>
<th style="text-align: left;">Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">ParticipantID</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Participant ID number.</td>
</tr>
<tr class="even">
<td style="text-align: center;">Sex</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Participant sex.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Age</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Participant age in years.</td>
</tr>
<tr class="even">
<td style="text-align: center;">Ethnicity</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Participant ethnicity.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">OzEstimate</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Estimated soup consumption in ounces (Oz).</td>
</tr>
<tr class="even">
<td style="text-align: center;">CalEstimate</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Estimated soup consumption in calories (kcals).</td>
</tr>
<tr class="odd">
<td style="text-align: center;">M_postsoup</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Actual soup consumption in ounces (Oz).</td>
</tr>
<tr class="even">
<td style="text-align: center;">F_CaloriesConsumed</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Actual soup consumption in calories (kcals).</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Condition</td>
<td style="text-align: left;">integer</td>
<td style="text-align: left;">Condition labelled numerically as 0 (Control) and 1 (Experimental).</td>
</tr>
<tr class="even">
<td style="text-align: center;">Condition_label</td>
<td style="text-align: left;">character</td>
<td style="text-align: left;">Condition as a direct label: Control and Experimental.</td>
</tr>
</tbody>
</table>
<p>We will use this data set to demonstrate t-tests and regression when you have one categorical predictor.</p>
</section></section><section id="comparing-differences-using-the-t-test" class="level2" data-number="2.2"><h2 data-number="2.2" class="anchored" data-anchor-id="comparing-differences-using-the-t-test">
<span class="header-section-number">2.2</span> Comparing differences using the t-test</h2>
<p>Like correlations are a specific application of the general linear model for the relationship between two continuous variables, t-tests are a specific application for the difference between two groups. Before we demonstrate how you can express this kind of design as a regression model, we cover t-tests so you know how to calculate and interpret them when you come across them in your research.</p>
<section id="activity-3---visualising-the-difference" class="level3" data-number="2.2.1"><h3 data-number="2.2.1" class="anchored" data-anchor-id="activity-3---visualising-the-difference">
<span class="header-section-number">2.2.1</span> Activity 3 - Visualising the difference</h3>
<p>To visualise the difference between two groups, it is useful to create something like a boxplot early for yourself, then provide a more professional looking violin-boxplot to help communicate your results. For most of the demonstrations in this chapter, we will try and answer the research question: “Is there a difference in actual calories consumed between the control and experimental groups?”</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try this
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using your data visualisation skills from Repro Res, recreate the violin-boxplot below using the variables <code>F_CaloriesConsumed</code> and <code>Condition_label</code> from <code>lopez_clean</code>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-02-lm-categorical_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Looking at the graph, the <select class="webex-select"><option value="blank"></option>
<option value="">Control</option>
<option value="answer">Experimental</option></select> group consumed more calories on average.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The violin-boxplot shows the experimental group who had the biased visual cues consumed more soup in calories than the control group who had the accurate visual cues.</p>
<p>You should have the following in a code chunk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>lopez_clean <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> F_CaloriesConsumed, <span class="at">x =</span> Condition_label, <span class="at">fill =</span> Condition_label)) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3"></a>  <span class="fu">geom_violin</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb3-4"><a href="#cb3-4"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.2</span>, </span>
<span id="cb3-5"><a href="#cb3-5"></a>               <span class="at">fatten =</span> <span class="cn">NULL</span>) <span class="sc">+</span> </span>
<span id="cb3-6"><a href="#cb3-6"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, </span>
<span id="cb3-7"><a href="#cb3-7"></a>               <span class="at">geom =</span> <span class="st">"point"</span>) <span class="sc">+</span></span>
<span id="cb3-8"><a href="#cb3-8"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_cl_boot"</span>, <span class="co"># confidence interval</span></span>
<span id="cb3-9"><a href="#cb3-9"></a>               <span class="at">geom =</span> <span class="st">"errorbar"</span>, </span>
<span id="cb3-10"><a href="#cb3-10"></a>               <span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb3-11"><a href="#cb3-11"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">"E"</span>) <span class="sc">+</span> </span>
<span id="cb3-12"><a href="#cb3-12"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Actual Calories Consumed (kcals)"</span>) <span class="sc">+</span></span>
<span id="cb3-13"><a href="#cb3-13"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">name =</span> <span class="st">"Study Condition"</span>) <span class="sc">+</span> </span>
<span id="cb3-14"><a href="#cb3-14"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb3-15"><a href="#cb3-15"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="activity-4---using-the-t.test-function" class="level3" data-number="2.2.2"><h3 data-number="2.2.2" class="anchored" data-anchor-id="activity-4---using-the-t.test-function">
<span class="header-section-number">2.2.2</span> Activity 4 - Using the <code>t.test()</code> function</h3>
<p>A t-test is a specific application of the general linear model. In this test, we express the difference in an outcome between two groups as a kind of standardised mean difference. If you are interested, see the Handy Workbook (<a href="https://psyteachr.github.io/handyworkbook/between-subjects-students-t-test.html" target="_blank">McAleer, 2023</a>) for the calculations behind the Student and Welch t-test. Conceptually, a t-test is the difference between two groups divided by the standard error of the difference. There are two main versions of a t-test:</p>
<ul>
<li><p><a class="glossary">Student t-test<span class="def">Calculating a t-value based on the mean difference divided by the pooled standard deviation. In the Student t-test, we times the pooled standard deviation by a term containing the sample sizes of each group.</span></a></p></li>
<li><p><a class="glossary">Welch t-test<span class="def">Calculating a t-value based on the mean difference divided by a term containing the variance of each group. We also correct the degrees of freedom for the difference in variances.</span></a></p></li>
</ul>
<p>There is a function built into R to calculate the t-test: <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code>. The function requires:</p>
<ul>
<li><p>A formula like <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> where you specify the outcome/dependent variable and the predictor/independent variable in the form <code>outcome ~ predictor</code>.</p></li>
<li><p>The data set you want to use.</p></li>
</ul>
<p>For our <code>lopez_clean</code> data, we would run the following code for a two-tailed Welch t-test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="fu">t.test</span>(<span class="at">formula =</span> F_CaloriesConsumed <span class="sc">~</span> Condition_label, </span>
<span id="cb4-2"><a href="#cb4-2"></a>       <span class="at">data =</span> lopez_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  F_CaloriesConsumed by Condition_label
t = -4.8578, df = 453.45, p-value = 1.638e-06
alternative hypothesis: true difference in means between group Control and group Experimental is not equal to 0
95 percent confidence interval:
 -88.55610 -37.54289
sample estimates:
     mean in group Control mean in group Experimental 
                  196.6818                   259.7313 </code></pre>
</div>
</div>
<p>For the three key concepts of inferential statistics, we get</p>
<ul>
<li>
<strong>Hypothesis testing</strong>: <em>p</em> &lt; .001, suggesting we can reject the null hypothesis assuming <span class="math inline">\(\alpha\)</span> = .05.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What does 1.638e-06 mean?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Remember: R reports very small or very large numbers using scientific notation to save space. We normally report <em>p</em>-values to three decimals, so we report anything smaller as <em>p</em> &lt; .001 to say it is smaller than this.</p>
<p>If you want to see the real number, you can use the following function which shows just how small the <em>p</em>-value is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="fu">format</span>(<span class="fl">1.638e-06</span>, <span class="at">scientific =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "0.000001638"</code></pre>
</div>
</div>
</div>
</div>
<ul>
<li>
<strong>Effect size</strong>: Somewhat annoyingly, we do not directly get the mean difference between groups as a raw/unstandardised mean difference. We must manually calculate it by subtracting the means of each group (196.6818 - 259.7313 = -63.05). So, those in the experimental group ate on average 63 more calories of soup than the control group.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Does it matter whether the difference is positive or negative?
</div>
</div>
<div class="callout-body-container callout-body">
<p>For effect sizes describing the difference between two groups, it is the absolute difference which is important, providing it is consistent with your predictions (if applicable). If you entered the groups the other way around, the mean difference would become 259.7313 - 196.6818 = 63.05. The same applies when we calculate a standardised mean difference like Cohen’s d later.</p>
</div>
</div>
<ul>
<li>
<strong>Confidence interval</strong>: [-88.56, -37.54], although we do not get the mean difference, we get the confidence interval around the mean difference.</li>
</ul>
<p>To summarise: A Welch t-test showed participants in the experimental group ate significantly more calories of soup than participants in the control group, <em>t</em> (453.45) = -4.86, <em>p</em> &lt; .001. On average, those in the experimental group ate 63.05 (95% CI = [37.54, 88.56]) more calories than those in the control group.</p>
<p>When you have statistics software like R to do the heavy lifting for you, there is not really a scenario where you would use the Student t-test anymore, but if you did, you can use the <code>var.equal</code> argument to say you assume there are equal variances in each group:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="fu">t.test</span>(<span class="at">formula =</span> F_CaloriesConsumed <span class="sc">~</span> Condition_label, </span>
<span id="cb8-2"><a href="#cb8-2"></a>       <span class="at">data =</span> lopez_clean, </span>
<span id="cb8-3"><a href="#cb8-3"></a>       <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  F_CaloriesConsumed by Condition_label
t = -4.8625, df = 462, p-value = 1.591e-06
alternative hypothesis: true difference in means between group Control and group Experimental is not equal to 0
95 percent confidence interval:
 -88.52983 -37.56915
sample estimates:
     mean in group Control mean in group Experimental 
                  196.6818                   259.7313 </code></pre>
</div>
</div>
<p>You can see the main difference between the two versions is the Welch t-test corrects the degrees of freedom, so they are a decimal. While the Student t-test does not correct the degrees of freedom, so they are predictably N - 2.</p>
<p>To summarise: A Student t-test showed participants in the experimental group ate significantly more calories of soup than participants in the control group, <em>t</em> (462) = -4.86, <em>p</em> &lt; .001. On average, those in the experimental group ate 63.05 (95% CI = [37.57, 88.53]) more calories than those in the control group.</p>
<p>One further useful argument is specifying a one-tailed test if you have a specific prediction. The only downside to using linear models later is there is not a simple argument to apply a one-tailed test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="fu">t.test</span>(<span class="at">formula =</span> F_CaloriesConsumed <span class="sc">~</span> Condition_label, </span>
<span id="cb10-2"><a href="#cb10-2"></a>       <span class="at">data =</span> lopez_clean, </span>
<span id="cb10-3"><a href="#cb10-3"></a>       <span class="at">alternative =</span> <span class="st">"less"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  F_CaloriesConsumed by Condition_label
t = -4.8578, df = 453.45, p-value = 8.188e-07
alternative hypothesis: true difference in means between group Control and group Experimental is less than 0
95 percent confidence interval:
     -Inf -41.6571
sample estimates:
     mean in group Control mean in group Experimental 
                  196.6818                   259.7313 </code></pre>
</div>
</div>
<p>The difference here is specifying the <code>alternative</code> argument. You can use “less” or “greater” depending if you predict a negative (group A &lt; group B) or positive difference (group A &gt; group B).</p>
</section><section id="activity-5---calculating-cohens-d" class="level3" data-number="2.2.3"><h3 data-number="2.2.3" class="anchored" data-anchor-id="activity-5---calculating-cohens-d">
<span class="header-section-number">2.2.3</span> Activity 5 - Calculating Cohen’s d</h3>
<p>Raw/unstandardised effect sizes are great for putting results in context, particularly when the units are comparable across studies. For our outcome in this study, differences in calories are easy to put in context.</p>
<p>Alternatively, it can be useful to calculate standardised effect sizes. This helps for power analyses and when you want to compare across comparable studies with slightly different measurement scales.</p>
<p>There are different formulas for calculating Cohen’s d, but if you know the t-value and degrees of freedom, you can calculate Cohen’s d through:</p>
<p><span class="math inline">\(d = \frac{2t}{\sqrt{df}} = \frac{-9.725}{21.49} = -0.45\)</span></p>
<p>Note the different formulas make different assumption and have various rounding errors from the statistics available, so this value will be slightly different to what we calculate shortly.</p>
<p>It is important to know the concepts before you use shortcuts, but there is the <code>cohens_d()</code> function from the <pkg>effectsize</pkg> package which uses the same format as <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">cohens_d</span>(F_CaloriesConsumed <span class="sc">~</span> Condition_label, </span>
<span id="cb12-2"><a href="#cb12-2"></a>         <span class="at">data =</span> lopez_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">Cohens_d</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: right;">-0.4523004</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.6366884</td>
<td style="text-align: right;">-0.2674345</td>
</tr></tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try this
</div>
</div>
<div class="callout-body-container callout-body">
<p>Great work following along so far, but now it is time to test your understanding on a new set of variables. Use the variables <code>CalEstimate</code> and <code>Condition_label</code> from <code>lopez_clean</code>. We can ask the question: “What is the difference in estimated calories consumed between the experimental and control groups?”</p>
<ol type="1">
<li><p>Create a violin-boxplot to visualise the difference between <code>CalEstimate</code> and <code>Condition_label</code> from <code>lopez_clean</code>.</p></li>
<li>
<p>Apply the Welch t-test to get your inferential statistics and answer the following questions:</p>
<ul>
<li><p><strong>Hypothesis testing</strong>: Assuming <span class="math inline">\(\alpha\)</span> = .05, the difference between the experimental and control groups on estimated calories consumed was <select class="webex-select"><option value="blank"></option>
<option value="">statistically significant</option>
<option value="answer">not statistically significant</option></select>.</p></li>
<li><p><strong>Effect size</strong>: Rounded to 2 decimals, the raw effect size was an average difference of <input class="webex-solveme nospaces" size="5" data-answer="[&quot;17.88&quot;]"> estimates calories between the two groups. Expressed as a standardised effect size, this difference equates to Cohen’s <em>d</em> = <input class="webex-solveme nospaces" size="4" data-answer="[&quot;0.15&quot;,&quot;.15&quot;]">.</p></li>
<li><p><strong>Confidence interval</strong>: Rounded to 2 decimals, the 95% confidence interval for the mean difference is <select class="webex-select"><option value="blank"></option>
<option value="answer">-4.08</option>
<option value="">-0.03</option>
<option value="">39.85</option>
<option value="">0.33</option></select> to <select class="webex-select"><option value="blank"></option>
<option value="">-4.08</option>
<option value="">-0.03</option>
<option value="answer">39.85</option>
<option value="">0.33</option></select>. The 95% confidence interval for Cohen’s d is <select class="webex-select"><option value="blank"></option>
<option value="">-4.08</option>
<option value="answer">-0.03</option>
<option value="">39.85</option>
<option value="">0.33</option></select> to <select class="webex-select"><option value="blank"></option>
<option value="">-4.08</option>
<option value="">-0.03</option>
<option value="">39.85</option>
<option value="answer">0.33</option></select>.</p></li>
</ul>
</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The violin-boxplot shows little difference between the two groups on estimated calories consumed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>lopez_clean <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> CalEstimate, <span class="at">x =</span> Condition_label, <span class="at">fill =</span> Condition_label)) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3"></a>  <span class="fu">geom_violin</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb13-4"><a href="#cb13-4"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.2</span>, </span>
<span id="cb13-5"><a href="#cb13-5"></a>               <span class="at">fatten =</span> <span class="cn">NULL</span>) <span class="sc">+</span> </span>
<span id="cb13-6"><a href="#cb13-6"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, </span>
<span id="cb13-7"><a href="#cb13-7"></a>               <span class="at">geom =</span> <span class="st">"point"</span>) <span class="sc">+</span></span>
<span id="cb13-8"><a href="#cb13-8"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_cl_boot"</span>, <span class="co"># confidence interval</span></span>
<span id="cb13-9"><a href="#cb13-9"></a>               <span class="at">geom =</span> <span class="st">"errorbar"</span>, </span>
<span id="cb13-10"><a href="#cb13-10"></a>               <span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb13-11"><a href="#cb13-11"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">"E"</span>) <span class="sc">+</span> </span>
<span id="cb13-12"><a href="#cb13-12"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Estimated Calories Consumed (kcals)"</span>) <span class="sc">+</span></span>
<span id="cb13-13"><a href="#cb13-13"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">name =</span> <span class="st">"Study Condition"</span>) <span class="sc">+</span> </span>
<span id="cb13-14"><a href="#cb13-14"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb13-15"><a href="#cb13-15"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-02-lm-categorical_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For our inferential statistics, a Welch t-test showed the difference is not statistically significant, <em>t</em> (455.06) = 1.60, <em>p</em> = .110.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="fu">t.test</span>(<span class="at">formula =</span> CalEstimate <span class="sc">~</span> Condition_label, </span>
<span id="cb14-2"><a href="#cb14-2"></a>       <span class="at">data =</span> lopez_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  CalEstimate by Condition_label
t = 1.6001, df = 455.06, p-value = 0.1103
alternative hypothesis: true difference in means between group Control and group Experimental is not equal to 0
95 percent confidence interval:
 -4.080399 39.846433
sample estimates:
     mean in group Control mean in group Experimental 
                  133.0328                   115.1498 </code></pre>
</div>
</div>
<p>The control group estimated they consumed 17.88 (95% CI = [-4.08, 39.85]) more calories than the experimental group, but the difference was not significant. Expressed as a standardised effect size, this equates to Cohen’s d = 0.15 (95% CI = [-0.03, 0.33]).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="fu">cohens_d</span>(CalEstimate <span class="sc">~</span> Condition_label, </span>
<span id="cb16-2"><a href="#cb16-2"></a>         <span class="at">data =</span> lopez_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">Cohens_d</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: right;">0.1490887</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.0341294</td>
<td style="text-align: right;">0.3321449</td>
</tr></tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</section></section><section id="09-categorical" class="level2" data-number="2.3"><h2 data-number="2.3" class="anchored" data-anchor-id="09-categorical">
<span class="header-section-number">2.3</span> Linear regression with one categorical predictor</h2>
<p>Now you know how to calculate a t-test in R, we can turn to simple linear regression as a more flexible tool for modelling the difference between two groups. As a reminder, there is a chapter in the Handy Workbook (<a href="https://psyteachr.github.io/handyworkbook/simple-linear-regression.html" target="_blank">McAleer, 2023</a>) dedicated to manually calculating simple linear regression if you want to work through what the functions are doing behind the scenes.</p>
<section id="activity-6---descriptive-statistics" class="level3" data-number="2.3.1"><h3 data-number="2.3.1" class="anchored" data-anchor-id="activity-6---descriptive-statistics">
<span class="header-section-number">2.3.1</span> Activity 6 - Descriptive statistics</h3>
<p>For all the information we want to include in a report, calculating descriptive statistics is helpful for the reader to show the context behind the results you present. Here, we can report the mean and standard deviation of our outcome per group.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a>lopez_clean <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2"></a>  <span class="fu">group_by</span>(Condition_label) <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3"></a>  <span class="fu">summarise</span>(<span class="at">mean_cals =</span> <span class="fu">round</span>(<span class="fu">mean</span>(F_CaloriesConsumed), <span class="dv">2</span>), </span>
<span id="cb17-4"><a href="#cb17-4"></a>            <span class="at">sd_cals =</span> <span class="fu">round</span>(<span class="fu">mean</span>(F_CaloriesConsumed), <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Condition_label</th>
<th style="text-align: right;">mean_cals</th>
<th style="text-align: right;">sd_cals</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control</td>
<td style="text-align: right;">196.68</td>
<td style="text-align: right;">196.68</td>
</tr>
<tr class="even">
<td style="text-align: left;">Experimental</td>
<td style="text-align: right;">259.73</td>
<td style="text-align: right;">259.73</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you want some reinforcement of how these skills apply to published research, look at Table 1 in <span class="citation" data-cites="lopez_visual_2023">Lopez et al. (<a href="references.html#ref-lopez_visual_2023" role="doc-biblioref">2023</a>)</span>. The means and standard deviations here (and Cohen’s d from Activity 5) exactly reproduce the values they report, apart from the <em>SD</em> for the control group (maybe there is a typo in their article).</p>
</div>
</div>
</section><section id="activity-7---using-the-lm-function" class="level3" data-number="2.3.2"><h3 data-number="2.3.2" class="anchored" data-anchor-id="activity-7---using-the-lm-function">
<span class="header-section-number">2.3.2</span> Activity 7 - Using the <code>lm()</code> function</h3>
<p>For our research question of “is there a difference in actual calories consumed between the control and experimental group?”, we can address it with simple linear regression. In this study, we can make causal conclusions as it was an experiment to randomly allocate people into one of two groups, but you can also use regression to compare two self-selecting groups when you cannot make a causal conclusion in isolation. Think carefully about what you can conclude from your design.</p>
<p>Like Chapter 1, we start by defining our regression model with a formula in the pattern <code>outcome ~ predictor</code> and specify the data frame you want to use. We must then use the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> function around your model object to get all the statistics you need.</p>
<p>There are two ways you can use a categorical predictor. First, we can code groups numerically which people called <a class="glossary">dummy coding<span class="def">Entering a categorical predictor using two values such as 0 and 1.</span></a>. You code your first group 0 and you code your second group as 1, which maps on directly to how the regression model works. Let’s look at the output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="co"># Condition as a factor containing 0 and 1</span></span>
<span id="cb18-2"><a href="#cb18-2"></a>lm_cals_numbers <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> F_CaloriesConsumed <span class="sc">~</span> Condition, </span>
<span id="cb18-3"><a href="#cb18-3"></a>                      <span class="at">data =</span> lopez_clean)</span>
<span id="cb18-4"><a href="#cb18-4"></a></span>
<span id="cb18-5"><a href="#cb18-5"></a><span class="fu">summary</span>(lm_cals_numbers)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = F_CaloriesConsumed ~ Condition, data = lopez_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-230.90  -99.09  -24.15   62.83  828.04 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  196.682      8.888  22.130  &lt; 2e-16 ***
Condition1    63.049     12.966   4.863 1.59e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 139.4 on 462 degrees of freedom
Multiple R-squared:  0.04869,   Adjusted R-squared:  0.04663 
F-statistic: 23.64 on 1 and 462 DF,  p-value: 1.591e-06</code></pre>
</div>
</div>
<p>Compared to when we had a continuous predictor in Chapter 1, the output is identical. We just need to remember what the key numbers represent. The intercept is the predicted value of your outcome when your predictor is set to 0. When we have two groups coded as 0 and 1, this means the intercept is essentially the mean value of group 0 (here, the control group). We call this the <a class="glossary">reference group<span class="def">In a dummy-coded variable, the first level of your variable, typically 0.</span></a>. You can confirm this by comparing the intercept estimate 196.68 to the mean value of the control group we calculated in Activity 6.</p>
<p>The slope estimate then represents how we predict the outcome to change for every 1-unit increase in the predictor. Since we coded the predictor 0 and 1, this just represents the shift from group 1 to group 2. We call the group we code as 1 the <a class="glossary">target group<span class="def">In a dummy-coded variable, the second level of your variable, typically 1.</span></a>. You see the target group appended to the variable name, which is <code>Condition1</code> here. So, for a categorical predictor, the slope represents the mean difference between the reference group (0) and the target group (1): 63.05. In contrast to the t-test, this is our raw/unstandardised effect size for the mean difference we do not need to manually calculate.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Does it matter if the slope is positive or negative?
</div>
</div>
<div class="callout-body-container callout-body">
<p>When you have a categorical predictor, the sign is only important for interpreting which group is bigger or smaller. The absolute size is relevant for the effect size where a larger absolute value indicates a larger effect. Whether the slope is positive or negative depends on the order of the groups and which has a larger mean. If the reference is larger than the target, you will get a negative slope. If the target is larger than the reference, you will get a positive slope.</p>
</div>
</div>
<p>Like the continuous predictor, we get values for <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span>, showing we explain .046 (in other words, 4.6%) variance in the outcome through our condition manipulation. We then get the model fit statistics, but with a single predictor, the <em>p</em>-value is identifical to the slope.</p>
<p>Alternatively, you can use character labels for your categorical predictor and it will still work. This time, we use <code>Condition_label</code>. By default, it will set the order of the reference and target groups alphabetically, but you can manually specify the order by setting factor levels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="co"># Condition_label as characters</span></span>
<span id="cb20-2"><a href="#cb20-2"></a>lm_cals_labels <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> F_CaloriesConsumed <span class="sc">~</span> Condition_label, </span>
<span id="cb20-3"><a href="#cb20-3"></a>                     <span class="at">data =</span> lopez_clean)</span>
<span id="cb20-4"><a href="#cb20-4"></a></span>
<span id="cb20-5"><a href="#cb20-5"></a><span class="fu">summary</span>(lm_cals_labels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = F_CaloriesConsumed ~ Condition_label, data = lopez_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-230.90  -99.09  -24.15   62.83  828.04 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                  196.682      8.888  22.130  &lt; 2e-16 ***
Condition_labelExperimental   63.049     12.966   4.863 1.59e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 139.4 on 462 degrees of freedom
Multiple R-squared:  0.04869,   Adjusted R-squared:  0.04663 
F-statistic: 23.64 on 1 and 462 DF,  p-value: 1.591e-06</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you want to test specifying the factor order to see how it affects the output, try running this code prior to the regression model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="co"># Specify group order of Experimental then Control</span></span>
<span id="cb22-2"><a href="#cb22-2"></a>lopez_clean <span class="ot">&lt;-</span> lopez_clean <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="#cb22-3"></a>  <span class="fu">mutate</span>(<span class="at">Condition_label =</span> <span class="fu">factor</span>(Condition_label, </span>
<span id="cb22-4"><a href="#cb22-4"></a>                                  <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Experimental"</span>, <span class="st">"Control"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How are t-tests and regression the same?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If you are interested in the relationship between the two concepts, we said a t-test was a specific application of the general linear model. In the t-test calculations, it expresses the mean difference between groups by the standard error of the difference. In essence, it describes the difference in standard errors, which we can describe with a t-distribution to calculate <em>p</em>-values.</p>
<p>In regression, we frame the model as how much variance you explain compared to the total amount of variance. The more variance your predictor explains, the less unexplained variance there is left over. For the slope estimate though, this is identical to the t-test as we estimate the mean difference between groups plus the standard error around the mean difference. We calculate a <em>p</em>-value for the slope from a t-distribution, so you get a t-value in the output.</p>
<p>You can see the process is identical by comparing the key values from the regression output to the Student t-test. We can recreate the mean difference to compare to the slope, the t-value is the same, the p-value is the same, the degrees of freedom are the same, and the 95% confidence intervals below are the same.</p>
<p>So, when you have a single categorical predictor, it is the exact same process as the Student t-test, just expressed slightly different. The only downside to this procedure is it is much more difficult to recreate the Welch t-test.</p>
</div>
</div>
</div>
</section><section id="activity-8---calculating-confidence-intervals" class="level3" data-number="2.3.3"><h3 data-number="2.3.3" class="anchored" data-anchor-id="activity-8---calculating-confidence-intervals">
<span class="header-section-number">2.3.3</span> Activity 8 - Calculating confidence intervals</h3>
<p>The only thing we are missing is our confidence intervals around the estimates which we can calculate through the <code><a href="https://rdrr.io/r/stats/confint.html">confint()</a></code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="fu">confint</span>(lm_cals_numbers)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept) 179.21657 214.14704
Condition1   37.56915  88.52983</code></pre>
</div>
</div>
<p>Now, we can summarise the three key concepts of inferential statistics as:</p>
<ul>
<li><p><strong>Hypothesis testing</strong>: <em>p</em> &lt; .001, suggesting we can reject the null hypothesis assuming <span class="math inline">\(\alpha\)</span> = .05. The experimental group ate significantly more calories of soup than the control group.</p></li>
<li><p><strong>Effect size</strong>: <span class="math inline">\(b_1\)</span> = 63.05, suggesting the experimental group ate on average 63 more calories than the control group.</p></li>
<li><p><strong>Confidence interval</strong>: [37.57, 88.53], showing the precision around the slope estimate.</p></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try this
</div>
</div>
<div class="callout-body-container callout-body">
<p>Now it is time to test your understanding on a new set of variables. This time, use <code>CalEstimate</code> as your outcome, <code>Condition_label</code> as your predictor, and use <code>lopez_clean</code> as your data. We can ask the same question as Activity 5: “What is the difference in estimated calories consumed between the experimental and control groups?”.</p>
<p>Apply simple linear regression to get your inferential statistics and answer the following questions:</p>
<ul>
<li><p><strong>Hypothesis testing</strong>: Assuming <span class="math inline">\(\alpha\)</span> = .05, Condition is a <select class="webex-select"><option value="blank"></option>
<option value="">statistically significant</option>
<option value="answer">non-significant</option></select> predictor of estimates calories consumed.</p></li>
<li><p><strong>Effect size</strong>: Rounded to 2 decimals, the Condition slope coefficient means there was a mean difference of <select class="webex-select"><option value="blank"></option>
<option value="">133.03</option>
<option value="">7.68</option>
<option value="answer">-17.88</option>
<option value="">11.19</option></select>.</p></li>
<li><p><strong>Confidence interval</strong>: Rounded to 2 decimals, the lower bound of the slope is <select class="webex-select"><option value="blank"></option>
<option value="">117.94</option>
<option value="answer">-39.88</option>
<option value="">148.12</option>
<option value="">4.11</option></select> and the upper bound is <select class="webex-select"><option value="blank"></option>
<option value="">117.94</option>
<option value="">-39.88</option>
<option value="">148.12</option>
<option value="answer">4.11</option></select>.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The conclusions are the same as when we calculated the t-test, where condition is not a statistically significant predictor of estimated calories consumed. As a regression model, we get the same conclusions expressed in a slightly different way. Condition is a negative but non-significant predictor (<em>p</em> = .111). The control group ate 17.88 (<span class="math inline">\(b_1\)</span> = -17.88, 95% CI = [-39.88, 4.11]) more calories than the experimental group. We explain very little variance in estimated calories consumed (adjusted <span class="math inline">\(R^2\)</span> = .003), so the condition manipulation had little effect.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="co"># Create lm object for condiiton label as a predictor</span></span>
<span id="cb25-2"><a href="#cb25-2"></a>lm_cal_est <span class="ot">&lt;-</span> <span class="fu">lm</span>(CalEstimate <span class="sc">~</span> Condition_label, </span>
<span id="cb25-3"><a href="#cb25-3"></a>                 <span class="at">data =</span> lopez_clean)</span>
<span id="cb25-4"><a href="#cb25-4"></a></span>
<span id="cb25-5"><a href="#cb25-5"></a><span class="co"># summary of the model object</span></span>
<span id="cb25-6"><a href="#cb25-6"></a><span class="fu">summary</span>(lm_cal_est)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = CalEstimate ~ Condition_label, data = lopez_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-130.03  -83.03  -33.03   44.85  666.97 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                  133.033      7.679  17.324   &lt;2e-16 ***
Condition_labelExperimental  -17.883     11.192  -1.598    0.111    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 119.9 on 459 degrees of freedom
  (3 observations deleted due to missingness)
Multiple R-squared:  0.005531,  Adjusted R-squared:  0.003365 
F-statistic: 2.553 on 1 and 459 DF,  p-value: 0.1108</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="co"># confidence intervals around estimates</span></span>
<span id="cb27-2"><a href="#cb27-2"></a><span class="fu">confint</span>(lm_cal_est)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                2.5 %     97.5 %
(Intercept)                 117.94256 148.123015
Condition_labelExperimental -39.87763   4.111599</code></pre>
</div>
</div>
</div>
</div>
</div>
</section><section id="activity-9---standardising-predictors" class="level3" data-number="2.3.4"><h3 data-number="2.3.4" class="anchored" data-anchor-id="activity-9---standardising-predictors">
<span class="header-section-number">2.3.4</span> Activity 9 - Standardising predictors</h3>
<p>For simple linear regression with two levels of a categorical predictor, centering the variable does not help, but we can standardise our outcome to express the estimate in standard deviations rather than the raw units. This is analogous to calculating Cohen’s d as we express the standardised mean difference. In contrast to continuous predictors, we only need to standardise the outcome, rather than both the outcome and predictor(s). We then use the standardised variable as our outcome.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="co"># Be careful with the bracket placement to subtract the mean first</span></span>
<span id="cb29-2"><a href="#cb29-2"></a>lopez_clean <span class="ot">&lt;-</span>lopez_clean <span class="sc">%&gt;%</span> </span>
<span id="cb29-3"><a href="#cb29-3"></a>  <span class="fu">mutate</span>(<span class="at">actual_calories_std =</span> (F_CaloriesConsumed <span class="sc">-</span> <span class="fu">mean</span>(F_CaloriesConsumed)) <span class="sc">/</span> <span class="fu">sd</span>(F_CaloriesConsumed))</span>
<span id="cb29-4"><a href="#cb29-4"></a></span>
<span id="cb29-5"><a href="#cb29-5"></a><span class="co"># Condition as a factor containing 0 and 1</span></span>
<span id="cb29-6"><a href="#cb29-6"></a>lm_cals_std <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> actual_calories_std <span class="sc">~</span> Condition, </span>
<span id="cb29-7"><a href="#cb29-7"></a>                      <span class="at">data =</span> lopez_clean)</span>
<span id="cb29-8"><a href="#cb29-8"></a></span>
<span id="cb29-9"><a href="#cb29-9"></a><span class="fu">summary</span>(lm_cals_std)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = actual_calories_std ~ Condition, data = lopez_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6173 -0.6941 -0.1692  0.4401  5.8000 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.20749    0.06225  -3.333 0.000928 ***
Condition1   0.44163    0.09082   4.863 1.59e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9764 on 462 degrees of freedom
Multiple R-squared:  0.04869,   Adjusted R-squared:  0.04663 
F-statistic: 23.64 on 1 and 462 DF,  p-value: 1.591e-06</code></pre>
</div>
</div>
<p>Note, the estimate may be slightly different to directly calculating Cohen’s d as there are a few formulas. If you compare to Activity 5, we got <em>d</em> = 0.45 there and 0.44 here. Between the estimate and 95% confidence intervals, they are off by .02, so it does not have a material impact on the results.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>As before, once you know how it works conceptually, there is a shortcut where you do not need to standardise all your variables first. The <pkg>effectsize</pkg> package has a handy function called <code>standardize_parameters()</code> which you can apply to your initial <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="fu">standardize_parameters</span>(lm_cals_numbers)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Std_Coefficient</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-0.2074898</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.3298249</td>
<td style="text-align: right;">-0.0851547</td>
</tr>
<tr class="even">
<td style="text-align: left;">Condition1</td>
<td style="text-align: right;">0.4416297</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.2631529</td>
<td style="text-align: right;">0.6201065</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</section></section><section id="checking-assumptions" class="level2" data-number="2.4"><h2 data-number="2.4" class="anchored" data-anchor-id="checking-assumptions">
<span class="header-section-number">2.4</span> Checking assumptions</h2>
<p>For the inferential statistics to work as intended, the model makes certain assumptions about the data you are putting into it and the accuracy of the inferences depends on how sensible these assumption are.</p>
<section id="activity-10---diagnostic-plots-for-linear-regression" class="level3" data-number="2.4.1"><h3 data-number="2.4.1" class="anchored" data-anchor-id="activity-10---diagnostic-plots-for-linear-regression">
<span class="header-section-number">2.4.1</span> Activity 10 - Diagnostic plots for linear regression</h3>
<p>We have the same assumptions for simple linear regression now we have a categorical predictor:</p>
<ol type="1">
<li><p>The outcome is interval/ratio level data.</p></li>
<li><p>The predictor variable is interval/ratio or categorical (with two levels at a time).</p></li>
<li><p>All values of the outcome variable are independent (i.e., each score should come from a different participant/observation).</p></li>
<li><p>The predictors have non-zero variance.</p></li>
<li><p>The relationship between the outcome and predictor is linear.</p></li>
<li><p>The residuals should be normally distributed.</p></li>
<li><p>There should be homoscedasticity.</p></li>
</ol>
<p>Assumptions 1-4 are pretty straight forward as they relate to your understanding of the design or a simple check on the data for non-zero variance (the responses are not all the exact same value).</p>
<p>Assumptions 5-7 require diagnostic checks on the residuals from the model. In contrast to continuous predictors, they are a little harder to identify patterns in. As we only have two values on the x-axis (0 and 1), all the residuals will be organised into vertical lines and the trend lines to help spot patterns do not look quite right.</p>
</section><section id="checking-linearity" class="level3" data-number="2.4.2"><h3 data-number="2.4.2" class="anchored" data-anchor-id="checking-linearity">
<span class="header-section-number">2.4.2</span> Checking linearity</h3>
<p>When you have a categorical predictor with two levels, you meet linearity by default, so you <strong>do not</strong> need to check this assumption directly. When you have two levels, you can only fit a straight line between the values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="fu">plot</span>(lm_cals_numbers, </span>
<span id="cb32-2"><a href="#cb32-2"></a>     <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-02-lm-categorical_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="checking-normality" class="level3" data-number="2.4.3"><h3 data-number="2.4.3" class="anchored" data-anchor-id="checking-normality">
<span class="header-section-number">2.4.3</span> Checking normality</h3>
<p>The qq-plot is still the same to interpret. Now, this example presents a useful case of decision making in data analysis we explore more in Chapter 4. The plot here is approaching signs of violating normality as there is a clear curve to the data points with 3 and 118 the largest deviations (you can see these on the violin-boxplot as the two highest values in the control group). For this chapter, we are sticking with it and it would be consistent with how the original authors analysed the data, but note this would be a key decision to make and justify when reporting the analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="fu">plot</span>(lm_cals_numbers, </span>
<span id="cb33-2"><a href="#cb33-2"></a>     <span class="at">which =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-02-lm-categorical_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="checking-homoscedasticity" class="level3" data-number="2.4.4"><h3 data-number="2.4.4" class="anchored" data-anchor-id="checking-homoscedasticity">
<span class="header-section-number">2.4.4</span> Checking homoscedasticity</h3>
<p>The scale-location plot is harder to interpret when you have a categorical predictor. Like linearity, the points are all arranged in two vertical lines as we only have two levels. You are looking out for the spread of the two lines to be roughly similar. They look fine here, just points 118 and 3 separated a little from the other points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a><span class="fu">plot</span>(lm_cals_numbers, </span>
<span id="cb34-2"><a href="#cb34-2"></a>     <span class="at">which =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-02-lm-categorical_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="checking-influential-cases" class="level3" data-number="2.4.5"><h3 data-number="2.4.5" class="anchored" data-anchor-id="checking-influential-cases">
<span class="header-section-number">2.4.5</span> Checking influential cases</h3>
<p>Finally, we have our plots for identifying influential cases. First, we get Cook’s distance for all the observations in your data. We see points 3 and 118 come up yet again, but although they are the largest deviations, they do not necessarily have worrying Cook’s distance values. There are different thresholds in the literature, but estimates range from 1, 0.5, to 4/n.&nbsp;It would only be under this final most conservative estimate (0.009) we would highlight several observations for further inspection.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="fu">plot</span>(lm_cals_numbers, </span>
<span id="cb35-2"><a href="#cb35-2"></a>     <span class="at">which =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-02-lm-categorical_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Finally, the fifth plot shows residual values against leverage. Like Chapter 1, we cannot see the Cook’s distance threshold it uses in the plot as none of the points are a large enough deviation, despite 3 and 188 sticking out again.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a><span class="fu">plot</span>(lm_cals_numbers, </span>
<span id="cb36-2"><a href="#cb36-2"></a>     <span class="at">which =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-02-lm-categorical_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="checking-all-the-assumptions" class="level3" data-number="2.4.6"><h3 data-number="2.4.6" class="anchored" data-anchor-id="checking-all-the-assumptions">
<span class="header-section-number">2.4.6</span> Checking all the assumptions</h3>
<p>Now we have covered the individual diagnostic plots, there is a handy function called <code>check_model()</code> from the <pkg>performance</pkg> package. Like the <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> function, the output for linearity, homoscedasticity, and influential observations does not plot right as we only have two values for the predictor and the plot lines do not really work. Do not worry, you have not done anything wrong.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="fu">check_model</span>(lm_cals_numbers)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-02-lm-categorical_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What might explain the funky normality?
</div>
</div>
<div class="callout-body-container callout-body">
<p>The posterior predictive check here provides an insight into why we get potential problems with normality. The outcome is ratio but cannot be smaller than 0 as we cannot have negative calories. So, in the green line for the observed data, the data are a little skewed as it drops off prior to 0. However, the model does not know that and it happily predicts normally distributed values which go below 0, creating a mismatch between what the model predicts and the values we enter into it.</p>
<p>Remember the models will work regardless of the data you put into them, it is important to keep your role in mind to recognise when you need to be cautious about what you can learn from the model. This is what we will explore in Chapters 4 and 5 as we consider data screening and alternative model distributions.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try this
</div>
</div>
<div class="callout-body-container callout-body">
<p>In activity 8, you should have calculated the effect of condition (<code>Condition_label</code>) on estimated calories consumed (<code>CalEstimate</code>) for your independent task. Using the model object <code>lm_cal_est</code>, work through assumptions for simple linear regression and make a note of whether you think it meets the assumptions, or there might be any problems. Some of the assumptions you consider what you know about the design, while others you need the diagnostic plots.</p>
<ol type="1">
<li><p>The outcome is interval/ratio level data.</p></li>
<li><p>The predictor variable is interval/ratio or categorical (with two levels at a time).</p></li>
<li><p>All values of the outcome variable are independent (i.e., each score should come from a different participant/observation).</p></li>
<li><p>The predictors have non-zero variance.</p></li>
<li><p>The relationship between the outcome and predictor is linear.</p></li>
<li><p>The residuals should be normally distributed.</p></li>
<li><p>There should be homoscedasticity.</p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The outcome is interval/ratio level data.</li>
</ol>
<p><strong>The outcome is nicely ratio as estimated calories have a logical 0 point (no calories) and the units are in equal measurements..</strong></p>
<ol start="2" type="1">
<li>The predictor variable is interval/ratio or categorical (with two levels at a time).</li>
</ol>
<p><strong>Our predictor is categorical with two levels.</strong></p>
<ol start="3" type="1">
<li>All values of the outcome variable are independent (i.e., each score should come from a different participant/observation).</li>
</ol>
<p><strong>The short answer is this appears to be the case in this study. The longer answer is there might have been an issue with the participants apparently completing the study in groups of 3. It is not entirely clear in the data how they recorded this, but grouped data collection does present a potential problem with independence which you will not learn about until the final lecture on mixed effects models and the original authors did not seem to address it.</strong></p>
<ol start="4" type="1">
<li>The predictors have non-zero variance.</li>
</ol>
<p><strong>We have observations from both levels of the predictor.</strong></p>
<ol start="5" type="1">
<li>The relationship between the outcome and predictor is linear.</li>
</ol>
<p><strong>We meet linearity by default with two levels, so we do not need the plot here.</strong></p>
<ol start="6" type="1">
<li>The residuals should be normally distributed.</li>
</ol>
<p><strong>Like the actual calories consumed, this is firmly a clear deviation from what we expect and provides a good example of when it does not look right. If we were to analyse the data fully, we would explore the impact of this and alternative models, but for this chapter, we are going to note our concern and remember the authors analysed the data like this.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="fu">plot</span>(lm_cal_est, </span>
<span id="cb38-2"><a href="#cb38-2"></a>     <span class="at">which =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-02-lm-categorical_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="7" type="1">
<li>There should be homoscedasticity.</li>
</ol>
<p><strong>Looking at the spread of each group, it looks fine with a similar range until both groups are more sparsely distributed above 1.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="fu">plot</span>(lm_cal_est, </span>
<span id="cb39-2"><a href="#cb39-2"></a>     <span class="at">which =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-02-lm-categorical_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In summary, normality is a clear concern and something we will return to for your options in Chapter 4 and the course materials. For now, we will stick with the model but recognise we should be cautious.</p>
</div>
</div>
</div>
</section></section><section id="reporting-your-results" class="level2" data-number="2.5"><h2 data-number="2.5" class="anchored" data-anchor-id="reporting-your-results">
<span class="header-section-number">2.5</span> Reporting your results</h2>
<p>Now we have some results to go with, there are a few recommendations on how to communicate that information. If you need a reminder of APA style for formatting numbers, you can see <a href="https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf" target="_blank">this PDF online</a> for a little cheat sheet for numbers and statistics.</p>
<ol type="1">
<li><p>Explain to the reader what your linear regression model was. For example, what was your outcome and predictor variable?</p></li>
<li><p>Report descriptive statistics to help contextualise your findings. For example, the mean/standard deviation for your outcome per group.</p></li>
<li><p>Provide an appropriate data visualisation to help communciate key patterns to the reader. For example, a violin-boxplot for how each group responded on your outcome.</p></li>
<li><p>Report all three key inferential statistics concepts for the coefficient: the slope, the confidence interval around your slope, and the <em>p</em>-value for hypothesis testing. When you have one predictor in simple linear regression, you typically focus on the slope as your key effect size that helps address your research question and hypothesis. APA style rounds numbers to 2 decimal places when numbers can be bigger than 1, and 3 decimals with no leading zero when it cannot be bigger than 1. When you report the unstandardised slope, you use the symbol <span class="math inline">\(b_1\)</span> but for the standardised slope, you use Beta instead <span class="math inline">\(\beta_1\)</span>.</p></li>
<li><p>Provide an overview of the model fit statistics for whether your model explained a significant amount of variance in your outcome. Remember: the <em>p</em>-value for your model will be the same as for the slope in simple linear regression.</p></li>
</ol>
<p>For our main example, we could summarise the findings as:</p>
<p>“Our research question was: is there a difference in actual calories consumed between the control and experimental group? To test this, we applied simple linear regression using condition as a predictor with two levels (control and experimental) and actual calories consumed as our outcome. Figure 1 shows a violin-boxplot of the difference between the control and experimental groups.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-02-lm-categorical_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Our model explained a statistically significant amount of variance in our outcome (adjusted <span class="math inline">\(R^2\)</span> = .047, F(1, 462) = 23.64, <em>p</em> &lt; .001). Condition was a positive predictor, where the experimental group consumed on average 63 more calories than the control group (<span class="math inline">\(b_1\)</span> = 63.05, 95% CI = [37.57, 88.53], <em>p</em> &lt; .001). Expressed as a standardised effect size, the experimental group consumed 0.44 (95% CI = [0.26, 0.62]) more standard deviations than the control group.”</p>
<p>Note: we have not included an APA formatted Figure title here as it is not easy to format in our book, so refer to the course materials for guidance.</p>
</section><section id="09-bonus" class="level2" data-number="2.6"><h2 data-number="2.6" class="anchored" data-anchor-id="09-bonus">
<span class="header-section-number">2.6</span> One- and paired-samples tests</h2>
<p>You might find yourself in a situation where you want to test a continuous variable against a fixed value or compare conditions in the same participants. In experimental designs, you might have multiple conditions from the same participants which causes problems if you analyse the data as if they were groups as above. You will learn a more flexible approach in the final lecture on mixed effects models but for simple cases when you have two conditions, the following approach will work.</p>
<p>For this demonstration, we will use data from experiment 1 of <span class="citation" data-cites="bem_feeling_2011">Bem (<a href="references.html#ref-bem_feeling_2011" role="doc-biblioref">2011</a>)</span>, an (in)famous study that almost single-handedly started the replication crisis in psychology. Briefly, participants completed a computer task adapted from priming experiments where they could select one of two windows. They had to guess which window had an image hidden behind it and the images contained different stimuli like erotic or neutral/control images. Across many trials of the participants guessing the location, Bem calculated the proportion of successful trials which could range between 0 (never correct), 50 (50%, chance), and 100 (always correct). The headline finding was participants demonstrated precognition - or the ability to see into the future - to guess above chance levels, but what does the data look like?</p>
<p>We are working with a new data set, so please save the following data file: <a href="data/Bem_2011.csv">Bem_2011.csv</a>. Right click the link and select “save link as”, or clicking the link will save the files to your Downloads. Make sure that you save the file as “.csv”. Save or copy the file to your <code>data/</code> folder within <code>02_regression_categorical</code>. Read in the data file to the object <code>bem_data</code> to be consistent with the tasks below.</p>
<section id="activity-11---one-sample-comparing-against-a-fixed-value" class="level3" data-number="2.6.1"><h3 data-number="2.6.1" class="anchored" data-anchor-id="activity-11---one-sample-comparing-against-a-fixed-value">
<span class="header-section-number">2.6.1</span> Activity 11 - One-sample comparing against a fixed value</h3>
<p>There are scenarios where you want to compare a single continuous variable against a fixed value. For example, do your participants respond significantly above or below chance?</p>
<section id="expressed-as-a-t-test" class="level4" data-number="2.6.1.1"><h4 data-number="2.6.1.1" class="anchored" data-anchor-id="expressed-as-a-t-test">
<span class="header-section-number">2.6.1.1</span> Expressed as a t-test</h4>
<p>As a t-test, we need to specify two arguments:</p>
<ul>
<li><p><code>x</code> - This is the continuous variable you want to analyse and compare the mean value of. We must use the base R operator <code>$</code> to specify the column from your data.</p></li>
<li><p><code>mu</code> - This is the fixed value you want to test your variable against.</p></li>
</ul>
<p>In this scenario, we want to compare the hit rate to erotic images against a value of 50. This will tell us if the hit rate is significantly above or below chance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> bem_data<span class="sc">$</span>Erotic.Hits.PC,</span>
<span id="cb40-2"><a href="#cb40-2"></a>       <span class="at">mu =</span> <span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  bem_data$Erotic.Hits.PC
t = 2.5133, df = 99, p-value = 0.01358
alternative hypothesis: true mean is not equal to 50
95 percent confidence interval:
 50.66075 55.61703
sample estimates:
mean of x 
 53.13889 </code></pre>
</div>
</div>
<p>The output is similar to the independent samples t-test. We get the <em>p</em>-value for hypothesis testing, the mean estimate of the variable, and it’s 95% confidence interval. To express it as an effect size, you can subtract 50 from each value. So, participants responded 3.14% above chance - statistically significant, but hardly convincing evidence for precognition.</p>
</section><section id="expressed-as-a-linear-model" class="level4" data-number="2.6.1.2"><h4 data-number="2.6.1.2" class="anchored" data-anchor-id="expressed-as-a-linear-model">
<span class="header-section-number">2.6.1.2</span> Expressed as a linear model</h4>
<p>We can also express this as a linear model, but we must first add a small wrangling step. In the one-sample t-test, we can manually enter a fixed value to compare the mean against. In a linear model, we must compare against 0 by subtracting the fixed value from your variable. So, we subtract 50 from all the observations, so they become a kind of deviation from 50.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a>bem_data <span class="ot">&lt;-</span> bem_data <span class="sc">%&gt;%</span> </span>
<span id="cb42-2"><a href="#cb42-2"></a>  <span class="fu">mutate</span>(<span class="at">erotic_deviation =</span> Erotic.Hits.PC <span class="sc">-</span> <span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In contrast to previous linear models, we only add a fixed intercept and do not add a predictor. This recreates the one-sample t-test by estimating the mean value of your outcome.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a>lm_erotic <span class="ot">&lt;-</span> <span class="fu">lm</span>(erotic_deviation <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb43-2"><a href="#cb43-2"></a>                <span class="at">data =</span> bem_data)</span>
<span id="cb43-3"><a href="#cb43-3"></a></span>
<span id="cb43-4"><a href="#cb43-4"></a><span class="fu">summary</span>(lm_erotic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = erotic_deviation ~ 1, data = bem_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-28.139  -8.694   2.417   7.972  30.194 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)    3.139      1.249   2.513   0.0136 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.49 on 99 degrees of freedom</code></pre>
</div>
</div>
<p>This process has the benefit of directly producing your effect size, as the intercept estimate is the deviation from your fixed value (here, 50). As we calculated manually before, the erotic hit rate is 3.14% above your fixed value. If you remember back to the linear model explanations, this is where the <em>p</em>-value for the intercept is finally useful as it tests against 0.</p>
<p>If you compare to the one-sample t-test, all of these values are identical. You also have the option of calculating confidence intervals around the estimate, calculating a standardised effect size, and checking assumptions by applying the previous linear regression activities.</p>
</section></section><section id="activity-12---paired-samples-comparing-conditions" class="level3" data-number="2.6.2"><h3 data-number="2.6.2" class="anchored" data-anchor-id="activity-12---paired-samples-comparing-conditions">
<span class="header-section-number">2.6.2</span> Activity 12 - Paired-samples comparing conditions</h3>
<p>Alternatively, you might want to compare two conditions from the same participants in paired samples/within-subjects design. For example, is the hit-rate significantly higher for erotic images compared to control images?</p>
<section id="expressed-as-a-t-test-1" class="level4" data-number="2.6.2.1"><h4 data-number="2.6.2.1" class="anchored" data-anchor-id="expressed-as-a-t-test-1">
<span class="header-section-number">2.6.2.1</span> Expressed as a t-test</h4>
<p>To conduct a paired-samples t-test, we must specify three arguments:</p>
<ul>
<li><p><code>x</code> - This is the first level of your condition as a column. You need your data in wide format, so the condition levels are spread across two columns per participant. We must use the base R operator <code>$</code> to specify the column from your data.</p></li>
<li><p><code>y</code> - This is the second level of your condition as a column.</p></li>
<li><p><code>paired</code> - This instructs R you want a paired-samples t-test to compare conditions within participants.</p></li>
</ul>
<p>In this scenario, we want to compare the hit rate for erotic images to control images.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> bem_data<span class="sc">$</span>Erotic.Hits.PC,</span>
<span id="cb45-2"><a href="#cb45-2"></a>       <span class="at">y =</span> bem_data<span class="sc">$</span>Control.Hits.PC, </span>
<span id="cb45-3"><a href="#cb45-3"></a>       <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  bem_data$Erotic.Hits.PC and bem_data$Control.Hits.PC
t = 1.8563, df = 99, p-value = 0.06638
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -0.2277431  6.8388542
sample estimates:
mean difference 
       3.305556 </code></pre>
</div>
</div>
<p>The output is almost identical to the one-sample t-test, but this time the effect size is the mean difference between conditions, not just the mean per condition. Behind the scenes, a paired-samples t-test is actually a one-sample t-test in disguise as it uses the difference between conditions as the outcome.</p>
<p>As an aside, <span class="citation" data-cites="bem_feeling_2011">Bem (<a href="references.html#ref-bem_feeling_2011" role="doc-biblioref">2011</a>)</span> reported a significant difference here, but only because he reported a one-tailed test (<code>alternative = "greater"</code>). This is an example where you ideally need a strong (ideally pre-registered) prediction as it makes a material impact on the inferences you would make.</p>
</section><section id="expressed-as-a-linear-model-1" class="level4" data-number="2.6.2.2"><h4 data-number="2.6.2.2" class="anchored" data-anchor-id="expressed-as-a-linear-model-1">
<span class="header-section-number">2.6.2.2</span> Expressed as a linear model</h4>
<p>Finally, we can express a paired-samples t-test as a linear model. We must apply a small data wrangling step to calculate a difference score between conditions. This is so the linear model compares the estimate against 0 of no difference. So, for this example, we create a variable for the difference between erotic and control images.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1"></a>bem_data <span class="ot">&lt;-</span> bem_data <span class="sc">%&gt;%</span> </span>
<span id="cb47-2"><a href="#cb47-2"></a>  <span class="fu">mutate</span>(<span class="at">erotic_control =</span> Erotic.Hits.PC <span class="sc">-</span> Control.Hits.PC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Like the one-sample scenario, we only add a fixed intercept for the new difference variance and do not add a predictor. This recreates the paired-samples t-test by estimating the mean value of your difference score.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a>lm_paired <span class="ot">&lt;-</span> <span class="fu">lm</span>(erotic_control <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb48-2"><a href="#cb48-2"></a>                <span class="at">data =</span> bem_data)</span>
<span id="cb48-3"><a href="#cb48-3"></a></span>
<span id="cb48-4"><a href="#cb48-4"></a><span class="fu">summary</span>(lm_paired)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = erotic_control ~ 1, data = bem_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-58.861  -9.556   2.250   9.194  35.583 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)    3.306      1.781   1.856   0.0664 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17.81 on 99 degrees of freedom</code></pre>
</div>
</div>
<p>This process directly produces your effect size again, as the intercept estimate is the deviation from 0 for your difference score. As we saw in the paired-samples t-test output, there was a 3.31% higher hit rate for erotic images compared to control (as we calculated erotic - control).</p>
<p>If you compare to the paired-samples t-test, all of these values are identical. You also have the option of calculating confidence intervals around the estimate, calculating a standardised effect size, and checking assumptions by applying the previous linear regression activities.</p>
</section></section></section><section id="09-test" class="level2" data-number="2.7"><h2 data-number="2.7" class="anchored" data-anchor-id="09-test">
<span class="header-section-number">2.7</span> Test Yourself</h2>
<p>For this chapter’s knowledge check section, we have something a little different. Instead of purely conceptual questions about functions, we have another example of linear regression from <span class="citation" data-cites="lopez_visual_2023">Lopez et al. (<a href="references.html#ref-lopez_visual_2023" role="doc-biblioref">2023</a>)</span>. Feel free to create this model yourself, but we will show you some output and ask you questions based on it.</p>
<p>For this model, we focus on ounces of soup consumed (<code>M_postsoup</code>) rather than calories by each Condition group (<code>Condition_label</code>). You might have a good idea about the results based on the chapter, but you will still need to interpret the output accurately.</p>
<p><strong>Question 1</strong>. In the violin-boxplot below, the experimental group consumed more soup in ounces than the control group: <select class="webex-select"><option value="blank"></option>
<option value="answer">TRUE</option>
<option value="">FALSE</option></select>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-02-lm-categorical_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Question 2</strong> For the next few questions, we have the output from a linear regression model and we would like you to interpret it.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = M_postsoup ~ Condition_label, data = lopez_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-10.410  -4.467  -1.089   2.833  37.333 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                   8.8675     0.4007  22.130  &lt; 2e-16 ***
Condition_labelExperimental   2.8426     0.5846   4.863 1.59e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.285 on 462 degrees of freedom
Multiple R-squared:  0.04869,   Adjusted R-squared:  0.04663 
F-statistic: 23.64 on 1 and 462 DF,  p-value: 1.591e-06</code></pre>
</div>
</div>
<p>The outcome variable in this model is <select class="webex-select"><option value="blank"></option>
<option value="answer">Actual ounces of soup consumed</option>
<option value="">Experimental condition</option></select> and the predictor variable is <select class="webex-select"><option value="blank"></option>
<option value="">Actual ounces of soup consumed</option>
<option value="answer">Experimental condition</option></select>.</p>
<p><strong>Question 3</strong> In this model, the reference group is <select class="webex-select"><option value="blank"></option>
<option value="answer">Control</option>
<option value="">Experimental</option></select> and the target group is <select class="webex-select"><option value="blank"></option>
<option value="">Control</option>
<option value="answer">Experimental</option></select></p>
<p><strong>Question 4</strong> Rounded to 2 decimals, we predict a value of <input class="webex-solveme nospaces" size="4" data-answer="[&quot;8.87&quot;]"> for our reference group.</p>
<p><strong>Question 5</strong> The predictor is <select class="webex-select"><option value="blank"></option>
<option value="answer">statistically significant</option>
<option value="">non-significant</option></select> and <select class="webex-select"><option value="blank"></option>
<option value="answer">positive</option>
<option value="">negative</option></select>.</p>
<p><strong>Question 6</strong> The target group consumed on average <input class="webex-solveme nospaces" size="4" data-answer="[&quot;2.84&quot;]"> ounces <select class="webex-select"><option value="blank"></option>
<option value="">less</option>
<option value="answer">more</option></select> soup than the reference group.</p>
</section><section id="words-from-this-chapter" class="level2" data-number="2.8"><h2 data-number="2.8" class="anchored" data-anchor-id="words-from-this-chapter">
<span class="header-section-number">2.8</span> Words from this Chapter</h2>
<p>Below you will find a list of words that were used in this chapter that might be new to you in case it helps to have somewhere to refer back to what they mean. The links in this table take you to the entry for the words in the <a href="https://psyteachr.github.io/glossary/" target="_blank">PsyTeachR Glossary</a>. Note that the Glossary is written by numerous members of the team and as such may use slightly different terminology from that shown in the chapter.</p>
<table class="table caption-top" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">dummy coding</td>
<td style="text-align: left;">Entering a categorical predictor using two values such as 0 and 1.</td>
</tr>
<tr class="even">
<td style="text-align: left;">reference group</td>
<td style="text-align: left;">In a dummy-coded variable, the first level of your variable, typically 0.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Student t-test</td>
<td style="text-align: left;">Calculating a t-value based on the mean difference divided by the pooled standard deviation. In the Student t-test, we times the pooled standard deviation by a term containing the sample sizes of each group.</td>
</tr>
<tr class="even">
<td style="text-align: left;">target group</td>
<td style="text-align: left;">In a dummy-coded variable, the second level of your variable, typically 1.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Welch t-test</td>
<td style="text-align: left;">Calculating a t-value based on the mean difference divided by a term containing the variance of each group. We also correct the degrees of freedom for the difference in variances.</td>
</tr>
</tbody>
</table>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-bem_feeling_2011" class="csl-entry" role="listitem">
Bem, D. J. (2011). Feeling the future: <span>Experimental</span> evidence for anomalous retroactive influences on cognition and affect. <em>Journal of Personality and Social Psychology</em>, <em>100</em>(3), 407–425. <a href="https://doi.org/10.1037/a0021524">https://doi.org/10.1037/a0021524</a>
</div>
<div id="ref-lopez_visual_2023" class="csl-entry" role="listitem">
Lopez, A., Choi, A. K., Dellawar, N. C., Cullen, B. C., Avila Contreras, S., Rosenfeld, D. L., &amp; Tomiyama, A. J. (2023). Visual cues and food intake: <span>A</span> preregistered replication of <span>Wansink</span> et al (2005). <em>Journal of Experimental Psychology: General</em>. <a href="https://doi.org/10.1037/xge0001503.supp">https://doi.org/10.1037/xge0001503.supp</a>
</div>
</div>
</section></main><!-- /main --><script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script><script>
// open rdrr links externally ----

var exlinks = document.querySelectorAll("a[href^='https://rdrr.io']");
var exlink_func = function(){
  window.open(this.href);
  return false;
};
for (var i = 0; i < exlinks.length; i++) {
    exlinks[i].addEventListener('click', exlink_func, false);
}

// visible second sidebar in mobile ----

function move_sidebar() {
  var toc = document.getElementById("TOC");
  var small_sidebar = document.querySelector("#quarto-sidebar .sidebar-menu-container");
  var right_sidebar = document.getElementById("quarto-margin-sidebar");

  if (window.innerWidth < 768) {
    small_sidebar.append(toc);
  } else {
    right_sidebar.append(toc);
  }
}
move_sidebar();
window.onresize = move_sidebar;
</script><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./01-01-lm-continuous.html" class="pagination-link" aria-label="Regression with one continuous predictor">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Regression with one continuous predictor</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./01-03-lm-multiple.html" class="pagination-link" aria-label="Multiple Linear Regression">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>CC-BY (2025) Bartlett, Rousselet, &amp; DeBruine.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>