<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Materials for the MSc Statistics and Research Design course at the University of Glasgow.">
<title>1&nbsp; Regression with one continuous predictor – Statistics and Research Design</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./02-lm-categorical.html" rel="next">
<link href="./index.html" rel="prev">
<link href="./images/logos/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-6NP3MF25W3', { 'anonymize_ip': true});
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" href="include/booktem.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/glossary.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-lm-continuous.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Regression with one continuous predictor</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics and Research Design</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-lm-continuous.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Regression with one continuous predictor</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-lm-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression with one categorical predictor</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-screening-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Missing data, outliers, and checking assumptions</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#chapter-preparation" id="toc-chapter-preparation" class="nav-link active" data-scroll-target="#chapter-preparation"><span class="header-section-number">1.1</span> Chapter preparation</a>
  <ul class="collapse">
<li><a href="#introduction-to-the-data-set" id="toc-introduction-to-the-data-set" class="nav-link" data-scroll-target="#introduction-to-the-data-set"><span class="header-section-number">1.1.1</span> Introduction to the data set</a></li>
  <li><a href="#organising-your-files-and-project-for-the-chapter" id="toc-organising-your-files-and-project-for-the-chapter" class="nav-link" data-scroll-target="#organising-your-files-and-project-for-the-chapter"><span class="header-section-number">1.1.2</span> Organising your files and project for the chapter</a></li>
  <li><a href="#activity-1---read-and-wrangle-the-data" id="toc-activity-1---read-and-wrangle-the-data" class="nav-link" data-scroll-target="#activity-1---read-and-wrangle-the-data"><span class="header-section-number">1.1.3</span> Activity 1 - Read and wrangle the data</a></li>
  <li><a href="#08-explore" id="toc-08-explore" class="nav-link" data-scroll-target="#08-explore"><span class="header-section-number">1.1.4</span> Activity 2 - Explore the data</a></li>
  </ul>
</li>
  <li>
<a href="#correlation" id="toc-correlation" class="nav-link" data-scroll-target="#correlation"><span class="header-section-number">1.2</span> Correlation</a>
  <ul class="collapse">
<li><a href="#activity-3---visualise-the-relationship" id="toc-activity-3---visualise-the-relationship" class="nav-link" data-scroll-target="#activity-3---visualise-the-relationship"><span class="header-section-number">1.2.1</span> Activity 3 - Visualise the relationship</a></li>
  <li><a href="#activity-4---calculate-the-correlation-coefficient" id="toc-activity-4---calculate-the-correlation-coefficient" class="nav-link" data-scroll-target="#activity-4---calculate-the-correlation-coefficient"><span class="header-section-number">1.2.2</span> Activity 4 - Calculate the correlation coefficient</a></li>
  </ul>
</li>
  <li>
<a href="#linear-regression-with-one-continuous-predictor" id="toc-linear-regression-with-one-continuous-predictor" class="nav-link" data-scroll-target="#linear-regression-with-one-continuous-predictor"><span class="header-section-number">1.3</span> Linear regression with one continuous predictor</a>
  <ul class="collapse">
<li><a href="#activity-5--calculating-descriptive-statistics" id="toc-activity-5--calculating-descriptive-statistics" class="nav-link" data-scroll-target="#activity-5--calculating-descriptive-statistics"><span class="header-section-number">1.3.1</span> Activity 5- Calculating descriptive statistics</a></li>
  <li><a href="#activity-6---using-the-lm-function" id="toc-activity-6---using-the-lm-function" class="nav-link" data-scroll-target="#activity-6---using-the-lm-function"><span class="header-section-number">1.3.2</span> Activity 6 - Using the <code>lm()</code> function</a></li>
  <li><a href="#activity-7---calculating-confidence-intervals" id="toc-activity-7---calculating-confidence-intervals" class="nav-link" data-scroll-target="#activity-7---calculating-confidence-intervals"><span class="header-section-number">1.3.3</span> Activity 7 - Calculating confidence intervals</a></li>
  <li><a href="#activity-8---centering-and-standardising-predictors" id="toc-activity-8---centering-and-standardising-predictors" class="nav-link" data-scroll-target="#activity-8---centering-and-standardising-predictors"><span class="header-section-number">1.3.4</span> Activity 8 - Centering and standardising predictors</a></li>
  </ul>
</li>
  <li>
<a href="#checking-assumptions" id="toc-checking-assumptions" class="nav-link" data-scroll-target="#checking-assumptions"><span class="header-section-number">1.4</span> Checking assumptions</a>
  <ul class="collapse">
<li><a href="#activity-9---diagnostic-plots-for-linear-regression" id="toc-activity-9---diagnostic-plots-for-linear-regression" class="nav-link" data-scroll-target="#activity-9---diagnostic-plots-for-linear-regression"><span class="header-section-number">1.4.1</span> Activity 9 - Diagnostic plots for linear regression</a></li>
  <li><a href="#checking-linearity" id="toc-checking-linearity" class="nav-link" data-scroll-target="#checking-linearity"><span class="header-section-number">1.4.2</span> Checking linearity</a></li>
  <li><a href="#checking-normality" id="toc-checking-normality" class="nav-link" data-scroll-target="#checking-normality"><span class="header-section-number">1.4.3</span> Checking normality</a></li>
  <li><a href="#checking-homoscedasticity" id="toc-checking-homoscedasticity" class="nav-link" data-scroll-target="#checking-homoscedasticity"><span class="header-section-number">1.4.4</span> Checking homoscedasticity</a></li>
  <li><a href="#checking-influential-cases" id="toc-checking-influential-cases" class="nav-link" data-scroll-target="#checking-influential-cases"><span class="header-section-number">1.4.5</span> Checking influential cases</a></li>
  <li><a href="#checking-all-the-assumptions" id="toc-checking-all-the-assumptions" class="nav-link" data-scroll-target="#checking-all-the-assumptions"><span class="header-section-number">1.4.6</span> Checking all the assumptions</a></li>
  </ul>
</li>
  <li><a href="#reporting-your-results" id="toc-reporting-your-results" class="nav-link" data-scroll-target="#reporting-your-results"><span class="header-section-number">1.5</span> Reporting your results</a></li>
  <li><a href="#test-yourself" id="toc-test-yourself" class="nav-link" data-scroll-target="#test-yourself"><span class="header-section-number">1.6</span> Test Yourself</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Regression with one continuous predictor</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>In these first two chapters, we focus on simple linear regression for testing research questions and hypotheses. We are starting slow and demonstrating how common statistical tests such as correlation and t-tests are specific applications of the general linear model (<a href="https://lindeloev.github.io/tests-as-linear/" target="_blank">Lindeløv, 2019</a>). With inferential statistics, we want to test our research questions and hypotheses by analysing the data given the research design you are working with. By adopting a modelling approach, you will have far more flexibility to adapt to the design you are working with.</p>
<p>In this chapter, we focus on simple linear regression for testing research questions and hypotheses for the relationship between two continuous predictors. We will also explore the concepts of correlation and checking the statistical assumptions of your regression model.</p>
<p><strong>Chapter Intended Learning Outcomes (ILOs)</strong></p>
<p>By the end of this chapter, you will be able to:</p>
<ul>
<li><p>Visualise the relationship between two continuous variables using a scatterplot.</p></li>
<li><p>Apply and interpret a Pearson’s and Spearman’s correlation.</p></li>
<li><p>Apply and interpret linear regression with one continuous predictor variable.</p></li>
<li><p>Check the assumptions of linear regression through diagnostic plots.</p></li>
</ul>
<section id="chapter-preparation" class="level2" data-number="1.1"><h2 data-number="1.1" class="anchored" data-anchor-id="chapter-preparation">
<span class="header-section-number">1.1</span> Chapter preparation</h2>
<section id="introduction-to-the-data-set" class="level3" data-number="1.1.1"><h3 data-number="1.1.1" class="anchored" data-anchor-id="introduction-to-the-data-set">
<span class="header-section-number">1.1.1</span> Introduction to the data set</h3>
<p>For this chapter, we are using open data from <span class="citation" data-cites="dawtry_why_2015">Dawtry et al. (<a href="references.html#ref-dawtry_why_2015" role="doc-biblioref">2015</a>)</span>. The abstract of their article is:</p>
<blockquote class="blockquote">
<p>The present studies provide evidence that social-sampling processes lead wealthier people to oppose redistribution policies. In samples of American Internet users, wealthier participants reported higher levels of wealth in their social circles (Studies 1a and 1b). This was associated, in turn, with estimates of higher mean wealth in the wider U.S. population, greater perceived fairness of the economic status quo, and opposition to redistribution policies. Furthermore, results from a large-scale, nationally representative New Zealand survey revealed that low levels of neighborhood-level socioeconomic deprivation?an objective index of wealth within participants’ social circles mediated the relation between income and satisfaction with the economic status quo (Study 2). These findings held controlling for relevant variables, including political orientation and perceived self-interest. Social-structural inequalities appear to combine with social-sampling processes to shape the different political attitudes of wealthier and poorer people.</p>
</blockquote>
<p>In summary, the authors investigated why people with more money tend to oppose wealth redistribution policies like higher taxes for higher incomes to decrease inequality in society. We are using data from Study 1A where 305 people completed measures on household income, predicted population income, their predicted social circle income, in addition to measures on support for wealth redistribution and fairness and satisfaction with the current system.</p>
<p>They predicted people with higher incomes have social circles with higher incomes, so they are more satisfied with the current system of wealth redistribution and less interested in changing it. In essence, poorer people and richer people have different experiences of how rich and equal their country is. In this chapter, we will explore the relationship between a range of these variables.</p>
</section><section id="organising-your-files-and-project-for-the-chapter" class="level3" data-number="1.1.2"><h3 data-number="1.1.2" class="anchored" data-anchor-id="organising-your-files-and-project-for-the-chapter">
<span class="header-section-number">1.1.2</span> Organising your files and project for the chapter</h3>
<p>Before we can get started, you need to organise your files and project for the chapter, so your working directory is in order. This course builds on <a href="https://psyteachr.github.io/reprores-v4/" target="_blank">Data Skills for Reproducible Research</a> to focus on inferential statistics, so if any concepts sound unfamiliar, make sure you revisit the course book.</p>
<p>To keep your work organised for this course, we recommend creating a folder on your computer for the course, then a separate sub-folder for assessments and each chapter of the book. Within each sub-folder, create folders for data and figures, so you have somewhere memorable to save the files and you know where everything is.</p>
<ol type="1">
<li><p>In your folder for statistics and research design <code>Stats_Research_Design</code>, create a new folder called <code>01_regression_continuous</code>. Within <code>01_regression_continuous</code>, create two new folders called <code>data</code> and <code>figures</code>.</p></li>
<li><p>Create an R Project for <code>01_regression_continuous</code> as an existing directory for your chapter folder. This should now be your working directory.</p></li>
<li><p>Create a new Quarto document and give it a sensible title describing the chapter, such as <code>01 Correlations and Regression</code> and save the file in your <code>01_regression_continuous</code> folder.</p></li>
<li><p>We are working with a new data set, so please save the following data file: <a href="data/Dawtry_2015.csv">Dawtry_2015.csv</a>. Right click the link and select “save link as”, or clicking the link will save the files to your Downloads. Make sure that you save the file as “.csv”. Save or copy the file to your <code>data/</code> folder within <code>01_regression_continuous</code>.</p></li>
</ol>
<p>You are now ready to start working on the chapter!</p>
</section><section id="activity-1---read-and-wrangle-the-data" class="level3" data-number="1.1.3"><h3 data-number="1.1.3" class="anchored" data-anchor-id="activity-1---read-and-wrangle-the-data">
<span class="header-section-number">1.1.3</span> Activity 1 - Read and wrangle the data</h3>
<p>As the first activity, try and test yourself by completing the following task list to practice your data wrangling skills. Create a final object called <code>dawtry_clean</code> to be consistent with the tasks below. If you just want to focus on correlations and regression, then you can just type the code in the solution.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try this
</div>
</div>
<div class="callout-body-container callout-body">
<p>To wrangle the data, complete the following tasks:</p>
<ol type="1">
<li>
<p>Load the following packages. If you do not have them already, remember you will need to install them first if you are working on your own computer:</p>
<ul>
<li><p><pkg>tidyverse</pkg></p></li>
<li><p><pkg>effectsize</pkg></p></li>
<li><p><pkg>correlation</pkg></p></li>
<li><p><pkg>performance</pkg></p></li>
</ul>
</li>
<li><p>Read the data file <code>data/Dawtry_2015.csv</code> to the object name <code>dawtry_data</code>.</p></li>
<li><p>Reverse code two items: <code>redist2</code> and <code>redist4</code> to create two new variables <code>redist2_R</code> and <code>redist4_R</code>. See the codebook below, but they are on a 1-6 scale.</p></li>
<li><p>Summarise the data to calculate the mean <code>fairness_satisfaction</code> score, by taking the mean of two items: <code>fairness</code> and <code>satisfaction</code>.</p></li>
<li><p>Summarise the data to calculate the mean <code>redistribution</code> score, by taking the mean of four items: <code>redist1</code>, <code>redist2_R</code>, <code>redist3</code>, and <code>redist4_R</code>.</p></li>
<li><p>Create a new object called <code>dawtry_clean</code> by joining <code>dawtry_data</code> with your two new variables <code>fairness_satisfaction</code> and <code>redistribution</code>.</p></li>
<li><p>Decrease the number of columns in <code>dawtry_clean</code> by selecting <code>PS</code>, all the columns between <code>Household_Income</code> and <code>redistribution</code>, but removing the two reverse coded items <code>redist2_R</code> and <code>redist4_R</code>.</p></li>
</ol>
<p>Your data should look like this to be ready to analyse:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 305
Columns: 11
$ PS                                  &lt;dbl&gt; 233, 157, 275, 111, 52, 11, 76, 90…
$ Household_Income                    &lt;dbl&gt; NA, 20.00, 100.00, 150.00, 500.00,…
$ Political_Preference                &lt;dbl&gt; 5, 5, 5, 8, 5, 3, 4, 3, 2, 3, NA, …
$ age                                 &lt;dbl&gt; 40, 59, 41, 59, 35, 34, 36, 39, 40…
$ gender                              &lt;dbl&gt; 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, NA, …
$ Population_Inequality_Gini_Index    &lt;dbl&gt; 38.78294, 37.21451, 20.75000, 35.3…
$ Population_Mean_Income              &lt;dbl&gt; 29715, 123630, 60000, 59355, 15360…
$ Social_Circle_Inequality_Gini_Index &lt;dbl&gt; 28.056738, 24.323388, 14.442577, 2…
$ Social_Circle_Mean_Income           &lt;dbl&gt; 21150, 65355, 107100, 86640, 56850…
$ fairness_satisfaction               &lt;dbl&gt; 1.0, 3.5, 5.0, 7.0, 4.5, 2.5, 3.0,…
$ redistribution                      &lt;dbl&gt; 5.50, 3.25, 3.75, 2.75, 3.00, 3.75…</code></pre>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You should have the following in a code chunk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># Load the packages below</span></span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb2-4"><a href="#cb2-4"></a><span class="fu">library</span>(correlation)</span>
<span id="cb2-5"><a href="#cb2-5"></a><span class="fu">library</span>(performance)</span>
<span id="cb2-6"><a href="#cb2-6"></a></span>
<span id="cb2-7"><a href="#cb2-7"></a><span class="co"># Load the data file</span></span>
<span id="cb2-8"><a href="#cb2-8"></a><span class="co"># This should be the Dawtry_2015.csv file </span></span>
<span id="cb2-9"><a href="#cb2-9"></a>dawtry_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Dawtry_2015.csv"</span>)</span>
<span id="cb2-10"><a href="#cb2-10"></a></span>
<span id="cb2-11"><a href="#cb2-11"></a><span class="co"># Reverse code redist2 and redist4</span></span>
<span id="cb2-12"><a href="#cb2-12"></a>dawtry_data <span class="ot">&lt;-</span> dawtry_data <span class="sc">%&gt;%</span></span>
<span id="cb2-13"><a href="#cb2-13"></a>  <span class="fu">mutate</span>(<span class="at">redist2_R =</span> <span class="dv">7</span> <span class="sc">-</span> redist2,</span>
<span id="cb2-14"><a href="#cb2-14"></a>         <span class="at">redist4_R =</span> <span class="dv">7</span> <span class="sc">-</span> redist4)</span>
<span id="cb2-15"><a href="#cb2-15"></a></span>
<span id="cb2-16"><a href="#cb2-16"></a><span class="co"># calculate mean fairness and satisfaction score  </span></span>
<span id="cb2-17"><a href="#cb2-17"></a>fairness_satisfaction <span class="ot">&lt;-</span> dawtry_data <span class="sc">%&gt;%</span> </span>
<span id="cb2-18"><a href="#cb2-18"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> fairness<span class="sc">:</span>satisfaction, </span>
<span id="cb2-19"><a href="#cb2-19"></a>               <span class="at">names_to =</span> <span class="st">"Items"</span>, </span>
<span id="cb2-20"><a href="#cb2-20"></a>               <span class="at">values_to =</span> <span class="st">"Response"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-21"><a href="#cb2-21"></a>  <span class="fu">group_by</span>(PS) <span class="sc">%&gt;%</span> </span>
<span id="cb2-22"><a href="#cb2-22"></a>  <span class="fu">summarise</span>(<span class="at">fairness_satisfaction =</span> <span class="fu">mean</span>(Response)) <span class="sc">%&gt;%</span> </span>
<span id="cb2-23"><a href="#cb2-23"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb2-24"><a href="#cb2-24"></a></span>
<span id="cb2-25"><a href="#cb2-25"></a><span class="co"># calculate mean wealth redistribution score  </span></span>
<span id="cb2-26"><a href="#cb2-26"></a>redistribution <span class="ot">&lt;-</span> dawtry_data <span class="sc">%&gt;%</span> </span>
<span id="cb2-27"><a href="#cb2-27"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(redist1, redist2_R, redist3, redist4_R), </span>
<span id="cb2-28"><a href="#cb2-28"></a>               <span class="at">names_to =</span> <span class="st">"Items"</span>, </span>
<span id="cb2-29"><a href="#cb2-29"></a>               <span class="at">values_to =</span> <span class="st">"Response"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-30"><a href="#cb2-30"></a>  <span class="fu">group_by</span>(PS) <span class="sc">%&gt;%</span> </span>
<span id="cb2-31"><a href="#cb2-31"></a>  <span class="fu">summarise</span>(<span class="at">redistribution =</span> <span class="fu">mean</span>(Response)) <span class="sc">%&gt;%</span> </span>
<span id="cb2-32"><a href="#cb2-32"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb2-33"><a href="#cb2-33"></a></span>
<span id="cb2-34"><a href="#cb2-34"></a><span class="co"># join data and select columns for focus</span></span>
<span id="cb2-35"><a href="#cb2-35"></a>dawtry_clean <span class="ot">&lt;-</span> dawtry_data <span class="sc">%&gt;%</span> </span>
<span id="cb2-36"><a href="#cb2-36"></a>  <span class="fu">inner_join</span>(fairness_satisfaction, <span class="at">by =</span> <span class="st">"PS"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-37"><a href="#cb2-37"></a>  <span class="fu">inner_join</span>(redistribution, <span class="at">by =</span> <span class="st">"PS"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-38"><a href="#cb2-38"></a>  <span class="fu">select</span>(PS, Household_Income<span class="sc">:</span>redistribution, <span class="sc">-</span>redist2_R, <span class="sc">-</span>redist4_R)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="08-explore" class="level3" data-number="1.1.4"><h3 data-number="1.1.4" class="anchored" data-anchor-id="08-explore">
<span class="header-section-number">1.1.4</span> Activity 2 - Explore the data</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try this
</div>
</div>
<div class="callout-body-container callout-body">
<p>After the wrangling steps, try and explore <code>dawtry_clean</code> to see what variables you are working with. For example, opening the data object as a tab to scroll around, explore with <code>glimpse()</code>, or try plotting some of the individual variables using a histogram.</p>
</div>
</div>
<p>In <code>dawtry_clean</code>, we have the following variables:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 41%">
<col style="width: 39%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">Variable</th>
<th style="text-align: left;">Type</th>
<th style="text-align: left;">Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">PS</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Participant ID number.</td>
</tr>
<tr class="even">
<td style="text-align: center;">Household_Income</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Household income in US Dollars ($).</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Political_Preference</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Political attitudes: 1 = very liberal/very left-wing/strong Democrat to 7 = very conservative/very right-wing/strong Republican.</td>
</tr>
<tr class="even">
<td style="text-align: center;">age</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Age in years.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">gender</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">1 = “Male”, 2 = “Female.</td>
</tr>
<tr class="even">
<td style="text-align: center;">Population_Inequality_Gini_Index</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Measure of income inequality from 0 (perfect equality) to 100 (perfect inequality), here where participants estimated population in equality.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Population_Mean_Income</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Participant estimate of the mean household income in the population ($).</td>
</tr>
<tr class="even">
<td style="text-align: center;">Social_Circle_Inequality_Gini_Index</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Measure of income inequality from 0 (perfect equality) to 100 (perfect inequality), here where participants estimated inequality in their social circle.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Social_Circle_Mean_Income</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Participant estimate of the mean household income in their social circle ($).</td>
</tr>
<tr class="even">
<td style="text-align: center;">fairness_satisfaction</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Perceived fairness and satisfaction about the current system of wealth redistribution: Mean of two items (1 extremely fair – 9 extremely unfair)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">redistribution</td>
<td style="text-align: left;">double</td>
<td style="text-align: left;">Support for wealth distribution: Mean of four items (1 strongly disagree – 6 strongly agree).</td>
</tr>
</tbody>
</table>
<p>We will use this data set to demonstrate correlations and regression when you have one continuous predictor.</p>
</section></section><section id="correlation" class="level2" data-number="1.2"><h2 data-number="1.2" class="anchored" data-anchor-id="correlation">
<span class="header-section-number">1.2</span> Correlation</h2>
<p>Before we cover regression as a more flexible framework for inferential statistics, we think it is useful to start with correlation to get a feel for how we can capture the relationship between two variables. As a reminder, correlations are standardised to range from -1 (a perfect negative correlation) to 1 (a perfect positive correlation). A value of 0 would mean there is no correlation between your variables.</p>
<section id="activity-3---visualise-the-relationship" class="level3" data-number="1.2.1"><h3 data-number="1.2.1" class="anchored" data-anchor-id="activity-3---visualise-the-relationship">
<span class="header-section-number">1.2.1</span> Activity 3 - Visualise the relationship</h3>
<p>To explore the relationship between two variables, it is useful to create a scatterplot early for yourself, then provide a more professional looking version to help communicate your results. For most of the demonstrations in this chapter, we will try and answer the research question: “Is there a relationship between support for wealth redistribution and fairness and satisfaction with the current system?”</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try this
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using your data visualisation skills from Repro Res, recreate the scatterplot below using the variables <code>fairness_satisfaction</code> and <code>redistribution</code> from <code>dawtry_clean</code>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-lm-continuous_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Looking at the graph, we can describe the relationship as <select class="webex-select"><option value="blank"></option>
<option value="">positive</option>
<option value="">little to no correlation</option>
<option value="answer">negative</option></select>.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The scatterplot shows a negative correlation between the two variables. You need to be careful interpreting fairness and satisfaction as it is coded a little counterintuitive. Higher values mean great <em>dissatisfaction</em>.</p>
<p>As support for wealth redistribution increases to be more positive, perceived fairness and satisfaction tends to decrease. This makes sense as people who are more dissatisfied with the current system think there should be more wealth redistribution strategies.</p>
<p>You should have the following in a code chunk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>dawtry_clean <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> fairness_satisfaction, <span class="at">y =</span> redistribution)) <span class="sc">+</span> </span>
<span id="cb3-3"><a href="#cb3-3"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb3-4"><a href="#cb3-4"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span> </span>
<span id="cb3-5"><a href="#cb3-5"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">name =</span> <span class="st">"Perceived Fairness and Satisfaction"</span>, </span>
<span id="cb3-6"><a href="#cb3-6"></a>                     <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>)) <span class="sc">+</span> </span>
<span id="cb3-7"><a href="#cb3-7"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Support for Wealth Redistribution"</span>, </span>
<span id="cb3-8"><a href="#cb3-8"></a>                     <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="activity-4---calculate-the-correlation-coefficient" class="level3" data-number="1.2.2"><h3 data-number="1.2.2" class="anchored" data-anchor-id="activity-4---calculate-the-correlation-coefficient">
<span class="header-section-number">1.2.2</span> Activity 4 - Calculate the correlation coefficient</h3>
<p>Visualising the relationship between two variables is great for our understanding, but it does not tell us anything about the inferential statistics for what we can learn from our sample in hypothesis testing and measures of effect size.</p>
<p>A correlation is a specific application of the general linear model. We want to capture the covariation between two variables. If you are interested, see the Handy Workbook (<a href="https://psyteachr.github.io/handyworkbook/pearson-correlation.html" target="_blank">McAleer, 2023</a>) for the calculations behind different types of correlation and how it represents the covariance of two variables compared to their total variability. They are not the only methods, but the two most common versions of a correlation are:</p>
<ul>
<li><p>Pearson’s product-moment correlation (often shortened to the <a class="glossary">Pearson<span class="def">A standardised measure of the linear relationship between two variables that makes stringent assumptions about the population.</span></a> correlation) and symbolised by <strong>r</strong>.</p></li>
<li><p>Spearman’s rank correlation coefficient (often shortened to the <a class="glossary">Spearman<span class="def">A standardised measure of the relationship between two variables that assumes a monotonic - but not necessarily a linear - relationship and makes less stringent assumptions about the population.</span></a> correlation) and symbolised by <span class="math inline">\(r_s\)</span> or sometimes the Greek letter <strong>rho</strong> <span class="math inline">\(\rho\)</span>.</p></li>
</ul>
<p>There is a function built into R (<code><a href="https://rdrr.io/r/stats/cor.test.html">cor.test()</a></code>) to calculate the correlation between two variables, but we tend to use the <code>correlation()</code> function from the <pkg>correlation</pkg> package as it has more consistent reporting features. The <code>correlation()</code> function requires:</p>
<ul>
<li><p>The name of the data set you are using.</p></li>
<li><p>The name of the first variable you want to select for the correlation.</p></li>
<li><p>The name of the second variable you want to select for the correlation.</p></li>
<li><p>The type of correlation you want to run: e.g.&nbsp;<code>pearson</code>, <code>spearman</code>.</p></li>
</ul>
<p>For our <code>dawtry_clean</code> data, we would run the following code for a two-tailed Pearson correlation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="fu">correlation</span>(<span class="at">data =</span> dawtry_clean, </span>
<span id="cb4-2"><a href="#cb4-2"></a>            <span class="at">select =</span> <span class="st">"fairness_satisfaction"</span>, </span>
<span id="cb4-3"><a href="#cb4-3"></a>            <span class="at">select2 =</span> <span class="st">"redistribution"</span>,  </span>
<span id="cb4-4"><a href="#cb4-4"></a>            <span class="at">method =</span> <span class="st">"pearson"</span>, </span>
<span id="cb4-5"><a href="#cb4-5"></a>            <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 16%">
<col style="width: 4%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Parameter1</th>
<th style="text-align: left;">Parameter2</th>
<th style="text-align: right;">r</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">t</th>
<th style="text-align: right;">df_error</th>
<th style="text-align: left;">p</th>
<th style="text-align: left;">Method</th>
<th style="text-align: right;">n_Obs</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">fairness_satisfaction</td>
<td style="text-align: left;">redistribution</td>
<td style="text-align: right;">-0.70034</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.7533907</td>
<td style="text-align: right;">-0.6382316</td>
<td style="text-align: right;">-17.07843</td>
<td style="text-align: right;">303</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">Pearson correlation</td>
<td style="text-align: right;">305</td>
</tr></tbody>
</table>
</div>
</div>
</div>
<p>Your output will look a little different due to how our book renders tables, but you should get the same information. For the three key concepts of inferential statistics, we get</p>
<ul>
<li><p><strong>Hypothesis testing</strong>: <em>p</em> &lt; .001, suggesting we can reject the null hypothesis assuming <span class="math inline">\(\alpha\)</span> = .05.</p></li>
<li><p><strong>Effect size</strong>: <em>r</em> = -.70, suggesting a strong negative correlation.</p></li>
<li><p><strong>Confidence interval</strong>: [-0.75, -0.64], showing the precision around the effect size estimate.</p></li>
</ul>
<p>To summarise: a Pearson correlation showed there was a strong, negative, statistically significant relationship between attitudes on wealth redistribution and perceived fairness and satisfaction, <em>r</em> (303) = -0.70, <em>p</em> &lt; .001, 95% CI = [-0.75, -0.64].</p>
<p>If we had reason to use a Spearman correlation instead, all we need to do is change the <code>method</code> argument.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="fu">correlation</span>(<span class="at">data =</span> dawtry_clean, </span>
<span id="cb5-2"><a href="#cb5-2"></a>            <span class="at">select =</span> <span class="st">"fairness_satisfaction"</span>, </span>
<span id="cb5-3"><a href="#cb5-3"></a>            <span class="at">select2 =</span> <span class="st">"redistribution"</span>,  </span>
<span id="cb5-4"><a href="#cb5-4"></a>            <span class="at">method =</span> <span class="st">"spearman"</span>, </span>
<span id="cb5-5"><a href="#cb5-5"></a>            <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 4%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 18%">
<col style="width: 5%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Parameter1</th>
<th style="text-align: left;">Parameter2</th>
<th style="text-align: right;">rho</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">S</th>
<th style="text-align: left;">p</th>
<th style="text-align: left;">Method</th>
<th style="text-align: right;">n_Obs</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">fairness_satisfaction</td>
<td style="text-align: left;">redistribution</td>
<td style="text-align: right;">-0.6806667</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.738182</td>
<td style="text-align: right;">-0.6133274</td>
<td style="text-align: right;">7947402</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">Spearman correlation</td>
<td style="text-align: right;">305</td>
</tr></tbody>
</table>
</div>
</div>
</div>
<p>Similarly, we could report the results as: a Spearman correlation showed there was a strong, negative, statistically significant relationship between attitudes on wealth redistribution and perceived fairness and satisfaction, <span class="math inline">\(r_s\)</span> (303) = -0.68, <em>p</em> &lt; .001, 95% CI = [-0.74, -0.61].</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try this
</div>
</div>
<div class="callout-body-container callout-body">
<p>Great work following along so far, but now it is time to test your understanding on a new set of variables. Use the variables <code>age</code> and <code>redistribution</code> from <code>dawtry_clean</code>. We can ask the question: “What is the relationship between age and attitudes on wealth redistribution?”</p>
<ol type="1">
<li><p>Create a scatterplot to visualise the relationship between <code>age</code> and <code>redistribution</code> from <code>dawtry_clean</code>.</p></li>
<li>
<p>Apply the Pearson correlation to get your inferential statistics and answer the following questions:</p>
<ul>
<li><p><strong>Hypothesis testing</strong>: Assuming <span class="math inline">\(\alpha\)</span> = .05, the relationship between age and wealth redistribution is <select class="webex-select"><option value="blank"></option>
<option value="">statistically significant</option>
<option value="answer">not statistically significant</option></select>.</p></li>
<li><p><strong>Effect size</strong>: Rounded to 2 decimals, the value for Pearson’s correlation coefficient is <select class="webex-select"><option value="blank"></option>
<option value="">-0.14</option>
<option value="answer">-0.03</option>
<option value="">0.08</option>
<option value="">-0.49</option></select>.</p></li>
<li><p><strong>Confidence interval</strong>: Rounded to 2 decimals, the lower bound is <select class="webex-select"><option value="blank"></option>
<option value="answer">-0.14</option>
<option value="">-0.03</option>
<option value="">0.08</option>
<option value="">-0.49</option></select> and the upper bound is <select class="webex-select"><option value="blank"></option>
<option value="">-0.14</option>
<option value="">-0.03</option>
<option value="answer">0.08</option>
<option value="">-0.49</option></select>.</p></li>
</ul>
</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The scatterplot shows very little correlation between the two variables. The regression line is almost flat and there does not appear to be a clear pattern to the data points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>dawtry_clean <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> redistribution)) <span class="sc">+</span> </span>
<span id="cb6-3"><a href="#cb6-3"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb6-4"><a href="#cb6-4"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span> </span>
<span id="cb6-5"><a href="#cb6-5"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Attitudes on Wealth Distribution"</span>, </span>
<span id="cb6-6"><a href="#cb6-6"></a>                     <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-lm-continuous_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For our inferential statistics, the relationship is not statistically significant and the Pearson correlation coefficient is very weak, <em>r</em> (302) = -0.03, <em>p</em> = .625, 95% CI = [-0.14, 0.08]. Note there is a missing value for age, so we have one few participant / degrees of freedom.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">correlation</span>(<span class="at">data =</span> dawtry_clean, </span>
<span id="cb7-2"><a href="#cb7-2"></a>            <span class="at">select =</span> <span class="st">"age"</span>, </span>
<span id="cb7-3"><a href="#cb7-3"></a>            <span class="at">select2 =</span> <span class="st">"redistribution"</span>,  </span>
<span id="cb7-4"><a href="#cb7-4"></a>            <span class="at">method =</span> <span class="st">"pearson"</span>, </span>
<span id="cb7-5"><a href="#cb7-5"></a>            <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 4%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 16%">
<col style="width: 5%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Parameter1</th>
<th style="text-align: left;">Parameter2</th>
<th style="text-align: right;">r</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">t</th>
<th style="text-align: right;">df_error</th>
<th style="text-align: right;">p</th>
<th style="text-align: left;">Method</th>
<th style="text-align: right;">n_Obs</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: left;">redistribution</td>
<td style="text-align: right;">-0.0281749</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.1402227</td>
<td style="text-align: right;">0.0845855</td>
<td style="text-align: right;">-0.4898215</td>
<td style="text-align: right;">302</td>
<td style="text-align: right;">0.6246159</td>
<td style="text-align: left;">Pearson correlation</td>
<td style="text-align: right;">304</td>
</tr></tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</section></section><section id="linear-regression-with-one-continuous-predictor" class="level2" data-number="1.3"><h2 data-number="1.3" class="anchored" data-anchor-id="linear-regression-with-one-continuous-predictor">
<span class="header-section-number">1.3</span> Linear regression with one continuous predictor</h2>
<p>Now you know how to calculate a correlation in R, we can turn to simple linear regression as a more flexible tool for modelling the relationship between variables. In this chapter, we focus on the relationship between a continuous <a class="glossary">outcome<span class="def">The outcome (also known as the dependent variable) is the variable you are interested in seeing a potential change in.</span></a> and one continuous <a class="glossary">predictor<span class="def">The predictor (also known as an independent variable) is the variable you measure or manipulate to see how it is associated with changes in the outcome variable.</span></a>, before extending the framework to one categorical predictor in Chapter 2. There is also a chapter in the Handy Workbook (<a href="https://psyteachr.github.io/handyworkbook/simple-linear-regression.html" target="_blank">McAleer, 2023</a>) dedicated to manually calculating simple linear regression.</p>
<section id="activity-5--calculating-descriptive-statistics" class="level3" data-number="1.3.1"><h3 data-number="1.3.1" class="anchored" data-anchor-id="activity-5--calculating-descriptive-statistics">
<span class="header-section-number">1.3.1</span> Activity 5- Calculating descriptive statistics</h3>
<p>For all the information we want to include in a report, calculating descriptive statistics is helpful for the reader to show the context behind the results you present. Here, we can report the mean and standard deviation of our two variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>dawtry_clean <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2"></a>  <span class="co"># pivot longer to avoid repeating yourself</span></span>
<span id="cb8-3"><a href="#cb8-3"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> fairness_satisfaction<span class="sc">:</span>redistribution,</span>
<span id="cb8-4"><a href="#cb8-4"></a>               <span class="at">names_to =</span> <span class="st">"Variable"</span>, </span>
<span id="cb8-5"><a href="#cb8-5"></a>               <span class="at">values_to =</span> <span class="st">"Value"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-6"><a href="#cb8-6"></a>  <span class="co"># group by Variable to get one value per variable</span></span>
<span id="cb8-7"><a href="#cb8-7"></a>  <span class="fu">group_by</span>(Variable) <span class="sc">%&gt;%</span> </span>
<span id="cb8-8"><a href="#cb8-8"></a>  <span class="co"># mean and SD, rounded to 2 decimals</span></span>
<span id="cb8-9"><a href="#cb8-9"></a>  <span class="fu">summarise</span>(<span class="at">mean_variable =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Value), <span class="dv">2</span>),</span>
<span id="cb8-10"><a href="#cb8-10"></a>            <span class="at">sd_variable =</span> <span class="fu">round</span>(<span class="fu">sd</span>(Value), <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">mean_variable</th>
<th style="text-align: right;">sd_variable</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">fairness_satisfaction</td>
<td style="text-align: right;">3.54</td>
<td style="text-align: right;">2.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">redistribution</td>
<td style="text-align: right;">3.91</td>
<td style="text-align: right;">1.15</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you want some reinforcement of how these skills apply to published research, look at Table 1 in <span class="citation" data-cites="dawtry_why_2015">Dawtry et al. (<a href="references.html#ref-dawtry_why_2015" role="doc-biblioref">2015</a>)</span>. The means and standard deviations here (and the correlation in Activity 4) exactly reproduce the values they report.</p>
</div>
</div>
<p>If other types of descriptive statistic would be more suitable to your data, then you can just replace the functions you use within <code>summarise()</code>.</p>
</section><section id="activity-6---using-the-lm-function" class="level3" data-number="1.3.2"><h3 data-number="1.3.2" class="anchored" data-anchor-id="activity-6---using-the-lm-function">
<span class="header-section-number">1.3.2</span> Activity 6 - Using the <code>lm()</code> function</h3>
<p>For our research question of “is there a relationship between support for wealth redistribution and fairness and satisfaction”, we can address it with simple linear regression.</p>
<p>Instead of a standardised correlation coefficient, we can frame it as whether knowing fairness and satisfaction can predict values of support for wealth redistribution. The design is still correlational, so it does not tell us anything about a causal relationship in isolation. We use the word predict in the statistical sense, where we can ask whether knowing values of one variable help us predict values of another variable with a degree of error.</p>
<p>The first step is to create an object (<code>lm_redistribution</code>) for the linear model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>lm_redistribution <span class="ot">&lt;-</span> <span class="fu">lm</span>(redistribution <span class="sc">~</span> fairness_satisfaction,</span>
<span id="cb9-2"><a href="#cb9-2"></a>                        <span class="at">data =</span> dawtry_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The function <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> is built into R and is incredibly flexible for creating linear regression models.</p>
<ul>
<li><p>The first argument is to specify a formula which defines our model. The first component (<code>redistribution</code>) is our outcome variable for what we are interested in modelling.</p></li>
<li><p>The tilde (<code>~</code>) separates the equation, where everything on the right is your predictor variable(s). In simple linear regression, we just have one predictor, which is <code>fairness_satisfaction</code> in our model here. This is saying we want to predict <code>redistribution</code> as our outcome from <code>fairness_satisfaction</code> as our predictor.</p></li>
<li><p>We then specify the data frame we want to use.</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In some resources, you might see people enter the same model as <code>redistribution ~ 1 + fairness_satisfaction</code>. The <code>1 +</code> component explicitly tells R to fit an intercept, plus a slope from <code>fairness_satisfaction</code>. R includes an intercept by default, so you do not need to add it, but some people like to include it for clarity.</p>
</div>
</div>
<p>When you create this object, it stores a bunch of information, but does not really tell us all the statistics we expect. If you simply print the object in the console, it will tell you the intercept and coefficient(s), but none of the model fitting nor hypothesis testing values. If you look at the object in the R environment, you will see it is a <a class="glossary">list<span class="def"></span></a> containing several elements. It stores things like the model, the residuals, and other information you can use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>lm_redistribution</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = redistribution ~ fairness_satisfaction, data = dawtry_clean)

Coefficients:
          (Intercept)  fairness_satisfaction  
               5.3169                -0.3975  </code></pre>
</div>
</div>
<p>To get that extra information, we need to call the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> function around the linear model object to explore it’s properties like estimates and model fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">summary</span>(lm_redistribution)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = redistribution ~ fairness_satisfaction, data = dawtry_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.9193 -0.5279  0.0233  0.4782  3.3634 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            5.31686    0.09488   56.04   &lt;2e-16 ***
fairness_satisfaction -0.39754    0.02328  -17.08   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8218 on 303 degrees of freedom
Multiple R-squared:  0.4905,    Adjusted R-squared:  0.4888 
F-statistic: 291.7 on 1 and 303 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>To walk through the output, <code>Call:</code> summarises the model you specified. <code>Residuals:</code> provides a summary of the model residuals which we will come back to later. <code>Coefficients:</code> provides our model output, this time with inferential statistics. The two key lines are:</p>
<ol type="1">
<li><p><code>(Intercept)</code> - This is the value of the outcome when our predictor is set to 0. For a fairness and satisfaction value of 0, we would expect a value of 5.32 for redistribution. You get a <em>p</em>-value for this, but in isolation it is not too useful. It just compares the intercept estimate to 0 which typically you are not interested in.</p></li>
<li><p><code>fairness_satisfaction</code> - This is the regression slope or coefficient. This is the change in the outcome for every 1 unit change in the predictor. So, for every 1 unit increase in fairness and satisfaction, we expect support for wealth redistribution to decrease (as we have a negative value) by 0.40 units. This is consistent with the correlation as we have a negative relationship between the two variables. Looking at the <em>p</em>-value, this is statistically significant (<em>p</em> &lt; .001), suggesting we can reject the null hypothesis and conclude there is an effect here.</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Does it matter if the slope is positive or negative?
</div>
</div>
<div class="callout-body-container callout-body">
<p>When you have a continuous predictor, the sign is important to keep in mind. A positive slope would mean an increase in the predictor is associated with increased values of your outcome. A negative slope would mean an increase in the predictor is associated with decreased values of your outcome. This is crucial for interpreting the coefficient.</p>
</div>
</div>
<p>At the bottom of the model output, you then get the fit statistics. Multiple <span class="math inline">\(R^2\)</span> tells you how much variance in your outcome your predictor(s) explain. Adjusted <span class="math inline">\(R^2\)</span> tends to be more conservative as it adjusts for the number of predictors in the model (something we will not cover until Chapter 3 on multiple regression), but they will be very similar when you have one predictor. Adjusted <span class="math inline">\(R^2\)</span> is .49, suggesting fairness and satisfaction explains 49% of the variance in support for wealth redistribution.</p>
<p>Finally, we have the model fit statistics to tell us whether the model explains a significant amount of variance in the outcome. With one predictor, the <em>p</em>-value next to the coefficient and next to the model fit will be identical, as one predictor is the whole model. The F-statistic is 291.7, the model degrees of freedom is 1, the residual degrees of freedom is 303, and the <em>p</em>-value is <em>p</em> &lt; .001.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What does 2e-16 mean?
</div>
</div>
<div class="callout-body-container callout-body">
<p>For the <em>p</em>-value here, the output looks a little weird. R reports very small or very large numbers using scientific notation to save space. We normally report <em>p</em>-values to three decimals, so we report anything smaller as <em>p</em> &lt; .001 to say it is smaller than this.</p>
<p>If you want to see the real number, you can use the following function which shows just how small the <em>p</em>-value is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="fu">format</span>(<span class="fl">2e-16</span>, <span class="at">scientific =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "0.0000000000000002"</code></pre>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How are correlation and regression the same?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If you are interested in the relationship between the two concepts, we said correlation was a specific application of the general linear model. It describes the - standardised - covariation between two variables compared to their total variability. For values of -1 and 1, knowing the value of one variable perfectly correlates to the value of your other variable. As you approach 0, the relationship between the variables is less perfect, meaning there is more variability left over compared to the covariance.</p>
<p>In regression, we frame it as how much variance you explain compared to the total amount of variance. The more variance your predictor explains, the less unexplained variance there is left over. We no longer calculate <em>r</em>, we calculate <span class="math inline">\(R^2\)</span> as the proportion of variance in your outcome explained by your model. A value of 0 would be you explain no variance and a value of 1 means you explain all the variance.</p>
<p>You can see the connection between the two by comparing the value of Pearson’s <em>r</em> from Activity 4 (-.70) to the value of <span class="math inline">\(R^2\)</span> = .4905. If you take the square root to get <em>r</em> (<code>sqrt(.4905)</code>), you get .70, which is exactly the same absolute value since <span class="math inline">\(R^2\)</span> can only be positive.</p>
<p>So, when you have a single continuous predictor, it is the exact same process as correlation, just expressed slightly different.</p>
</div>
</div>
</div>
</section><section id="activity-7---calculating-confidence-intervals" class="level3" data-number="1.3.3"><h3 data-number="1.3.3" class="anchored" data-anchor-id="activity-7---calculating-confidence-intervals">
<span class="header-section-number">1.3.3</span> Activity 7 - Calculating confidence intervals</h3>
<p>In the standard <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> and <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> output, we get most of the key values we need for our inferential statistics, but the one thing missing is confidence intervals around our estimates. Fortunately, R has a built-in function called <code><a href="https://rdrr.io/r/stats/confint.html">confint()</a></code> for calculating confidence intervals using your linear model object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="fu">confint</span>(lm_redistribution)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                           2.5 %     97.5 %
(Intercept)            5.1301581  5.5035664
fairness_satisfaction -0.4433442 -0.3517332</code></pre>
</div>
</div>
<p>Normally, you focus on the confidence interval around your slope estimate as the intercept is not usually super useful for interpreting your findings when you have a continuous predictor. Now, we can summarise the three key concepts of inferential statistics as:</p>
<ul>
<li><p><strong>Hypothesis testing</strong>: <em>p</em> &lt; .001, suggesting we can reject the null hypothesis assuming <span class="math inline">\(\alpha\)</span> = .05. Fairness and satisfaction is a significant predictor of support for wealth redistribution.</p></li>
<li><p><strong>Effect size</strong>: <span class="math inline">\(b_1\)</span> = -0.40, suggesting fairness and satisfaction is a negative predictor.</p></li>
<li><p><strong>Confidence interval</strong>: [-0.44, -0.35], showing the precision around the slope estimate.</p></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try this
</div>
</div>
<div class="callout-body-container callout-body">
<p>Great work following along so far, but now it is time to test your understanding on a new set of variables. This time, use <code>redistribution</code> as your outcome, <code>age</code> as your predictor, and use <code>dawtry_clean</code> as your data. We can ask the same question as before: “What is the relationship between age and attitudes on wealth redistribution?”.</p>
<p>Apply simple linear regression to get your inferential statistics and answer the following questions:</p>
<ul>
<li><p><strong>Hypothesis testing</strong>: Assuming <span class="math inline">\(\alpha\)</span> = .05, age is a <select class="webex-select"><option value="blank"></option>
<option value="">statistically significant</option>
<option value="answer">non-significant</option></select> predictor of support for wealth redistribution.</p></li>
<li><p><strong>Effect size</strong>: Rounded to 2 decimals, the age coefficient is <select class="webex-select"><option value="blank"></option>
<option value="">4.01</option>
<option value="answer">-0.003</option>
<option value="">0.005</option>
<option value="">0.22</option></select>.</p></li>
<li><p><strong>Confidence interval</strong>: Rounded to 2 decimals, the lower bound of the age coefficient is <select class="webex-select"><option value="blank"></option>
<option value="">3.59</option>
<option value="answer">-0.01</option>
<option value="">4.44</option>
<option value="">0.01</option></select> and the upper bound is <select class="webex-select"><option value="blank"></option>
<option value="">3.59</option>
<option value="">-0.01</option>
<option value="">4.44</option>
<option value="answer">0.01</option></select>.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The conclusions are the same as when we calculated the correlation where age is not a statistically significant predictor of support for wealth redistribution. As a regression model, we get the same conclusions expressed in a slightly different way. Age is negative, but the size of the slope is very small (-0.003) and non-significant (<em>p</em> = .625). We explain pretty much no variance in support for wealth redistribution (<span class="math inline">\(R^2\)</span> = .0008), so age is not very informative as a predictor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="co"># Create lm object for age as a predictor</span></span>
<span id="cb18-2"><a href="#cb18-2"></a>lm_age <span class="ot">&lt;-</span> <span class="fu">lm</span>(redistribution <span class="sc">~</span> age,</span>
<span id="cb18-3"><a href="#cb18-3"></a>             <span class="at">data =</span> dawtry_clean)</span>
<span id="cb18-4"><a href="#cb18-4"></a></span>
<span id="cb18-5"><a href="#cb18-5"></a><span class="co"># summary of the model object</span></span>
<span id="cb18-6"><a href="#cb18-6"></a><span class="fu">summary</span>(lm_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = redistribution ~ age, data = dawtry_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.93382 -0.69527  0.08099  0.84379  2.13621 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.011931   0.216042   18.57   &lt;2e-16 ***
age         -0.002693   0.005499   -0.49    0.625    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.153 on 302 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.0007938, Adjusted R-squared:  -0.002515 
F-statistic: 0.2399 on 1 and 302 DF,  p-value: 0.6246</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="co"># confidence intervals around estimates</span></span>
<span id="cb20-2"><a href="#cb20-2"></a><span class="fu">confint</span>(lm_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %     97.5 %
(Intercept)  3.58679351 4.43706821
age         -0.01351424 0.00812738</code></pre>
</div>
</div>
</div>
</div>
</div>
</section><section id="activity-8---centering-and-standardising-predictors" class="level3" data-number="1.3.4"><h3 data-number="1.3.4" class="anchored" data-anchor-id="activity-8---centering-and-standardising-predictors">
<span class="header-section-number">1.3.4</span> Activity 8 - Centering and standardising predictors</h3>
<p>So far, we have covered specifying your outcome and predictor variables as their raw values in the data. However, there are two variations that are useful to understand: centering and standardising predictors. These do not change the model fitting or <em>p</em>-values, but change how you interpret the intercept and/or slope.</p>
<section id="centering-predictors" class="level4" data-number="1.3.4.1"><h4 data-number="1.3.4.1" class="anchored" data-anchor-id="centering-predictors">
<span class="header-section-number">1.3.4.1</span> Centering predictors</h4>
<p><a class="glossary">Centering<span class="def">Usually, centering a predictor means subtracting the mean from each value, so the mean is 0. You can then interpret the intercept as the value of your outcome for the mean value of your predictor(s).</span></a> predictors is where you change the values of your predictor, but not their scale. Typically, this means substracting the mean of your predictor from each observation. This changes how you interpret the intercept of your regression model.</p>
<p>Remember the interpretation of the intercept is the predicted value of your outcome when your predictor is set to 0. If 0 is not present in your data or a value of 0 would be uninformative, the intercept can be difficult to interpret. When you center your predictor, 0 becomes the mean value of your predictor. So, the intercept is now the predicted value of your outcome for the mean value of your predictor, but the slope itself does not change. You can see the impact of this by plotting the data side by side in <a href="#fig-centering-predictors" class="quarto-xref">Figure&nbsp;<span>1.1</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>dawtry_clean <span class="ot">&lt;-</span> dawtry_clean <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2"></a>  <span class="co"># subtract fairness values from mean of fairness</span></span>
<span id="cb22-3"><a href="#cb22-3"></a>  <span class="fu">mutate</span>(<span class="at">fairness_center =</span> fairness_satisfaction <span class="sc">-</span> <span class="fu">mean</span>(fairness_satisfaction))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-centering-predictors" class="quarto-float quarto-figure quarto-figure-center anchored" alt="The plot at the top shows the relationship between wealth redistribution and perceived fairness and satisfaction using raw values. The plot at the bottom shows the relationship after centering perceived fairness and satisfaction values, so the values shift to the left.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-centering-predictors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-lm-continuous_files/figure-html/fig-centering-predictors-1.png" class="img-fluid figure-img" alt="The plot at the top shows the relationship between wealth redistribution and perceived fairness and satisfaction using raw values. The plot at the bottom shows the relationship after centering perceived fairness and satisfaction values, so the values shift to the left." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-centering-predictors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.1: Top: The relationship between wealth redistribution and perceived fairness and satisfaction using raw values. Bottom: The relationship after centering perceived fairness and satisfaction values.
</figcaption></figure>
</div>
</div>
</div>
<p>The relationship between the two variables is exactly the same, but the values of fairness and satisfaction shifted so the mean is 0. If you create a new linear model object, you can see the difference this makes to the output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a>lm_center <span class="ot">&lt;-</span> <span class="fu">lm</span>(redistribution <span class="sc">~</span> fairness_center, </span>
<span id="cb23-2"><a href="#cb23-2"></a>                <span class="at">data =</span> dawtry_clean)</span>
<span id="cb23-3"><a href="#cb23-3"></a></span>
<span id="cb23-4"><a href="#cb23-4"></a><span class="fu">summary</span>(lm_center)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = redistribution ~ fairness_center, data = dawtry_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.9193 -0.5279  0.0233  0.4782  3.3634 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      3.90984    0.04706   83.09   &lt;2e-16 ***
fairness_center -0.39754    0.02328  -17.08   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8218 on 303 degrees of freedom
Multiple R-squared:  0.4905,    Adjusted R-squared:  0.4888 
F-statistic: 291.7 on 1 and 303 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Every single one of the values remains the same apart from the intercept. Now, we can interpret it as the predicted value of redistribution when fairness and satisfaction is set to 0, i.e., the mean value. So, for the mean value of fairness and satisfaction, we would predict a value of 3.91 for redistribution.</p>
</section><section id="standardising-predictors" class="level4" data-number="1.3.4.2"><h4 data-number="1.3.4.2" class="anchored" data-anchor-id="standardising-predictors">
<span class="header-section-number">1.3.4.2</span> Standardising predictors</h4>
<p><a class="glossary">Standardising<span class="def">Standardising involves substracting the variable mean from each value and dividing it by the variable standard deviation. It then has the property of a mean of 0 and standard deviation of 1, so you interpret the units as standard deviations.</span></a> predictors is where you first convert your values to z-scores. This means you interpret the values as standard deviations rather than your original units. This is more useful in multiple regression (Chapter 3) to compare the magnitude of predictors, but it is useful to get used to now when you only have one predictor to focus on.</p>
<p>The first step is to standardise <strong>all</strong> your variables, not just the predictor this time. This involves subtracting the mean of your variable from each value, and dividing by the standard deviation of the variable. They now have a mean of 0 and a standard deviation of 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="co"># Be careful with the bracket placement to subtract the mean first</span></span>
<span id="cb25-2"><a href="#cb25-2"></a>dawtry_clean <span class="ot">&lt;-</span> dawtry_clean <span class="sc">%&gt;%</span> </span>
<span id="cb25-3"><a href="#cb25-3"></a>  <span class="fu">mutate</span>(<span class="at">redistribution_std =</span> (redistribution <span class="sc">-</span> <span class="fu">mean</span>(redistribution)) <span class="sc">/</span> <span class="fu">sd</span>(redistribution),</span>
<span id="cb25-4"><a href="#cb25-4"></a>         <span class="at">fairness_std =</span> (fairness_satisfaction <span class="sc">-</span> <span class="fu">mean</span>(fairness_satisfaction)) <span class="sc">/</span> <span class="fu">sd</span>(fairness_satisfaction))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once we enter them into the model, we no longer have values in the original units of measurement, we now have them expressed as standard deviations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a>lm_standardised <span class="ot">&lt;-</span> <span class="fu">lm</span>(redistribution_std <span class="sc">~</span> fairness_std, </span>
<span id="cb26-2"><a href="#cb26-2"></a>                      <span class="at">data =</span> dawtry_clean)</span>
<span id="cb26-3"><a href="#cb26-3"></a></span>
<span id="cb26-4"><a href="#cb26-4"></a><span class="fu">summary</span>(lm_standardised)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = redistribution_std ~ fairness_std, data = dawtry_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.53979 -0.45930  0.02026  0.41604  2.92617 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   7.387e-16  4.094e-02    0.00        1    
fairness_std -7.003e-01  4.101e-02  -17.08   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.715 on 303 degrees of freedom
Multiple R-squared:  0.4905,    Adjusted R-squared:  0.4888 
F-statistic: 291.7 on 1 and 303 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Like centering, the model fit and <em>p</em>-values do not change again, apart from the intercept. The relationship between the variables is exactly the same, but we changed their units. The intercept is tiny and close enough to zero that the <em>p</em>-value is 1.</p>
<p>More importantly, the slope is now expressed in standard deviations. Annoyingly, R prints the values in scientific notation, so this can be awkward to read (remember the <code><a href="https://rdrr.io/r/base/format.html">format()</a></code> function). Now, for every 1 standard deviation increase in our predictor, we predict the outcome to decrease by 0.70 standard deviations.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is important to demonstrate the underlying concepts first but if you want a shortcut without needing to standardise all your variables, the <pkg>effectsize</pkg> package has a handy function called <code>standardize_parameters()</code> which you can apply to your initial <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="fu">standardize_parameters</span>(lm_redistribution)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Std_Coefficient</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.0805627</td>
<td style="text-align: right;">0.0805627</td>
</tr>
<tr class="even">
<td style="text-align: left;">fairness_satisfaction</td>
<td style="text-align: right;">-0.70034</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.7810351</td>
<td style="text-align: right;">-0.6196449</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</section></section></section><section id="checking-assumptions" class="level2" data-number="1.4"><h2 data-number="1.4" class="anchored" data-anchor-id="checking-assumptions">
<span class="header-section-number">1.4</span> Checking assumptions</h2>
<p>For the inferential statistics to work as intended, the model makes certain assumptions about the data you are putting into it and the accuracy of the inferences depends on how sensible these assumption are. Remember these functions will always work even if the numbers you enter are nonsense, so it’s important for you as the researcher to recognise when it’s appropriate to use these techniques and when it is not.</p>
<section id="activity-9---diagnostic-plots-for-linear-regression" class="level3" data-number="1.4.1"><h3 data-number="1.4.1" class="anchored" data-anchor-id="activity-9---diagnostic-plots-for-linear-regression">
<span class="header-section-number">1.4.1</span> Activity 9 - Diagnostic plots for linear regression</h3>
<p>As a reminder, the assumptions for simple linear regression are:</p>
<ol type="1">
<li><p>The outcome is interval/ratio level data.</p></li>
<li><p>The predictor variable is interval/ratio or categorical (with two levels at a time).</p></li>
<li><p>All values of the outcome variable are independent (i.e., each score should come from a different participant/observation).</p></li>
<li><p>The predictors have non-zero variance.</p></li>
<li><p>The relationship between the outcome and predictor is linear.</p></li>
<li><p>The residuals should be normally distributed.</p></li>
<li><p>There should be homoscedasticity.</p></li>
</ol>
<p>Assumptions 1-4 are pretty straight forward as they relate to your understanding of the design or a simple check on the data for non-zero variance (the responses are not all the exact same value).</p>
<p>Assumptions 5-7 require diagnostic checks on the <a class="glossary">residuals<span class="def">The difference between the observed value in the data and the predicted value from the model given its assumptions.</span></a> from the model. The residuals are the difference between your observed values in the data and the values your model predicts given it’s assumptions. If you remember back, we highlighted the model output mentioned <code>Residuals:</code> and they are saved within the model object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="co"># head shows the first 6 values </span></span>
<span id="cb29-2"><a href="#cb29-2"></a><span class="fu">head</span>(lm_redistribution<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          2          3          4          5          6 
 0.5806764 -0.6754769  0.4208311  0.2159084 -0.5279383 -0.5730156 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What does the $ symbol mean?
</div>
</div>
<div class="callout-body-container callout-body">
<p>We have not used this symbol in the book yet, but it is a base R operator for extracting information. You use it to access specific components within a data frame or object.</p>
<p>Try the following in the console to see what it does:</p>
<ul>
<li><p><code>dawtry_clean$age</code></p></li>
<li><p><code>lm_redistribution$coefficients</code></p></li>
</ul>
<p>If you type an object name into the console and add the <code>$</code>, you will see all the components appear to auto complete.</p>
</div>
</div>
<p>In your reading, you might see individual statistical tests to check these assumptions, but they have more limitations than benefits. The best way to check the assumptions is through diagnostic plots which express the model residuals in different ways. We want to walk through this longer way of checking assumptions to develop a solid understanding before showing you a shortcut to see them all below.</p>
<p>In the code below, we use a format you will be less familiar with as all these functions come from base R. If you just run the code for the diagnostic plots <code>plot(lm_redistribution)</code>, each one gets individually printed to your Plots window. Here, we create a 2x2 panel to show them all together.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="co"># Change the panel layout to 2 x 2</span></span>
<span id="cb31-2"><a href="#cb31-2"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb31-3"><a href="#cb31-3"></a></span>
<span id="cb31-4"><a href="#cb31-4"></a><span class="co"># plot the diagnostic plots </span></span>
<span id="cb31-5"><a href="#cb31-5"></a><span class="fu">plot</span>(lm_redistribution)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-lm-continuous_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For more information on each of these plots, see this great resource by <a href="https://library.virginia.edu/data/articles/diagnostic-plots" target="_blank">Kim (2015)</a> via the University of Virginia, but we will break the key ones down below.</p>
</section><section id="checking-linearity" class="level3" data-number="1.4.2"><h3 data-number="1.4.2" class="anchored" data-anchor-id="checking-linearity">
<span class="header-section-number">1.4.2</span> Checking linearity</h3>
<p>To isolate each plot, we can use the <code>which</code> argument. Plot 1 is a residuals vs fitted plot and helps us check linearity by showing the residuals on the y-axis and the fitted (predicted) values on the x-axis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="fu">plot</span>(lm_redistribution, </span>
<span id="cb32-2"><a href="#cb32-2"></a>     <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-lm-continuous_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here, you are looking out for a roughly flat horizontal red line. Common patterns to look out for if there is a problem are when the line has an obvious curve to look like a hump or several bends to look like an S.</p>
<p>The only downside to using diagnostic plots is it takes experience to recognise when there is nothing wrong with a regression model compared to when it violates the assumptions. It is easy to see a little deviation and think there is some drastically wrong. Our advice is if you squint and it looks fine, it is probably fine. You are looking for clear and obvious deviations from what you expect and all the models we use in Chapters 1 to 3 are intentionally fine to develop foundational skills. In Chapter 4 and 5, we then introduce you to more problematic cases and what your options are, and introducing more flexible models.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Error mode
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you want to save these plots to add into a report, you might try using <code>ggsave()</code>. However, it will not work as these plots have not been created by <pkg>ggplot2</pkg>.</p>
<p>To save these plots, you can either right click and choose save as to save on your computer. Alternatively, if they open in the Plots window, you can click on Export and save them as an image or PDF to insert into your documents.</p>
</div>
</div>
</section><section id="checking-normality" class="level3" data-number="1.4.3"><h3 data-number="1.4.3" class="anchored" data-anchor-id="checking-normality">
<span class="header-section-number">1.4.3</span> Checking normality</h3>
<p>Plot 2 is a qq-plot (quantile-quantile plot) and helps us check the normality of the model residuals by showing the standardised residuals on the y-axis and the theoretical quantiles on the x-axis. A common misconception is your variables should all be normally distributed, but it is actually the model residuals which should be normal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="fu">plot</span>(lm_redistribution, </span>
<span id="cb33-2"><a href="#cb33-2"></a>     <span class="at">which =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-lm-continuous_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In this plot, you are looking for the data points to roughly follow the dashed line. The idea is there should be a linear relationship between the residuals and the values we would expect under a normal distribution.</p>
<p>Like the other diagnostic plots, it is tempting to think there are problems where there are none. The vast majority of the points here follow the line nicely, but tail off a little at the extremes. It flags the points with the largest deviations but there do not appear to be any obvious problems.</p>
<p>When there are problems with normality, you are looking for obvious deviations, like the points curving around in a banana shape, or snaking around like an S.</p>
</section><section id="checking-homoscedasticity" class="level3" data-number="1.4.4"><h3 data-number="1.4.4" class="anchored" data-anchor-id="checking-homoscedasticity">
<span class="header-section-number">1.4.4</span> Checking homoscedasticity</h3>
<p>Plot 3 is a scale-location plot and helps us check homoscedasticity by showing the square root of the standardised residuals on the y-axis and the fitted values on the x-axis. Homoscedasticity is where the variance of the residuals is approximately equal across the range of your predictor(s).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a><span class="fu">plot</span>(lm_redistribution, </span>
<span id="cb34-2"><a href="#cb34-2"></a>     <span class="at">which =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-lm-continuous_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In this plot, you are looking out for a roughly random spread of points as you move from one end of the x-axis to the other. The red line should be roughly flat and horizontal.</p>
<p>When there is <em>heteroscedasticity</em>, the characteristic patterns to look out for are a kind of arrow shape where there is a wide spread of points at one end and decreases to a denser range at the other end, or a bow tie where there is a wide spread of points at each end and dense in the middle.</p>
</section><section id="checking-influential-cases" class="level3" data-number="1.4.5"><h3 data-number="1.4.5" class="anchored" data-anchor-id="checking-influential-cases">
<span class="header-section-number">1.4.5</span> Checking influential cases</h3>
<p>Finally, there are two main plots to help us identify influential cases. You might have heard of the term outlier before and this is one way of classifying data points that are different enough to the rest of the data in a regression model. It is not strictly an assumption of linear regression, but it can affect the other assumptions. Identifying outliers is a complex decision and we will explore your options in the course materials and Chapter 14 on data screening.</p>
<p>If you only run <code>plot(lm_redistribution)</code> and cycle through the plots, you do not see this version. This plot shows values of Cook’s distance for each observation in your data along the x-axis. Cook’s distance measures the influence of deleting a given observation, where higher values mean deleting that observation results in a larger change to the model estimates. There are different thresholds in the literature, but estimates range from 1, 0.5, to 4/n.&nbsp;We explore the decision making around this and your options in Chapter 4.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="fu">plot</span>(lm_redistribution, </span>
<span id="cb35-2"><a href="#cb35-2"></a>     <span class="at">which =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-lm-continuous_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Finally, we get a residuals vs leverage plot to show influential cases in a slightly different way. Instead of just the Cook’s distance value of each observation, it plots the standardised residuals against leverage values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a><span class="fu">plot</span>(lm_redistribution, </span>
<span id="cb36-2"><a href="#cb36-2"></a>     <span class="at">which =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-lm-continuous_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Influential points and potential outliers would have high leverage values and the plot will show a threshold of Cook’s distance as red dashed lines. In this plot, they are not visible as there is no value with a big enough leverage value, but you would be looking for data points outside this threshold to identify influential values.</p>
</section><section id="checking-all-the-assumptions" class="level3" data-number="1.4.6"><h3 data-number="1.4.6" class="anchored" data-anchor-id="checking-all-the-assumptions">
<span class="header-section-number">1.4.6</span> Checking all the assumptions</h3>
<p>Now we have covered the individual diagnostic plots, there is a handy function called <code>check_model()</code> from the <pkg>performance</pkg> package. This function reports all the diagnostic checks from <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code>, but tidies up the presentation and has some useful reminders of what you are looking for.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="fu">check_model</span>(lm_redistribution)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-lm-continuous_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The key difference is you get a posterior predictive check (essentially comparing values you observe compared to what your model predicts). This will be an idea we return to in a much more important role when we cover Bayesian statistics later in the course, but it’s useful for these models too. The qq-plot for normality of residuals also looks a little different. Instead of a kind of angled line, the residuals are expressed as deviations instead, so the points should be close to a flat horizontal line. This version can make smaller deviations look worse, so keep in mind again you are looking for clear deviations in the overall pattern.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <pkg>performance</pkg> version of the diagnostic plots are actually created using <pkg>ggplot2</pkg>, so the function <code>ggsave()</code> would work here if you need to save the plot to add into your report.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try this
</div>
</div>
<div class="callout-body-container callout-body">
<p>In activity 7, you should have calculated the relationship between age and support for redistribution for your independent task. Using the model object <code>lm_age</code>, work through assumptions for simple linear regression and make a note of whether you think it meets the assumptions, or there might be any problems. Some of the assumptions you consider what you know about the design, while others you need the diagnostic plots.</p>
<ol type="1">
<li><p>The outcome is interval/ratio level data.</p></li>
<li><p>The predictor variable is interval/ratio or categorical (with two levels at a time).</p></li>
<li><p>All values of the outcome variable are independent (i.e., each score should come from a different participant/observation).</p></li>
<li><p>The predictors have non-zero variance.</p></li>
<li><p>The relationship between the outcome and predictor is linear.</p></li>
<li><p>The residuals should be normally distributed.</p></li>
<li><p>There should be homoscedasticity.</p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The outcome is interval/ratio level data.</li>
</ol>
<p><strong>There is a debate here we cover in the course materials, but there is an argument you can treat the average of multiple Likert items as interval, but you need to be careful.</strong></p>
<ol start="2" type="1">
<li>The predictor variable is interval/ratio or categorical (with two levels at a time).</li>
</ol>
<p><strong>Our predictor age is nicely ratio.</strong></p>
<ol start="3" type="1">
<li>All values of the outcome variable are independent (i.e., each score should come from a different participant/observation).</li>
</ol>
<p><strong>You need to know this from the design / data collection, but it appears to be the case in this study.</strong></p>
<ol start="4" type="1">
<li>The predictors have non-zero variance.</li>
</ol>
<p><strong>There are a range of ages in the data.</strong></p>
<ol start="5" type="1">
<li>The relationship between the outcome and predictor is linear.</li>
</ol>
<p><strong>Looking at the first plot, the red line is pretty flat and horizontal, so we are happy with this.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="fu">plot</span>(lm_age, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-lm-continuous_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="6" type="1">
<li>The residuals should be normally distributed.</li>
</ol>
<p><strong>The qq-plot is fine for the vast majority of the range. We just have a few deviations in the extreme ends of the x-axis, but this is a byproduct of using a scale score as our outcome as responses cannot go beyond 1-6.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="fu">plot</span>(lm_age, <span class="at">which =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-lm-continuous_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="7" type="1">
<li>There should be homoscedasticity.</li>
</ol>
<p><strong>The red line is pretty flat and it looks like there is a fairly even range of values across the x-axis range.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a><span class="fu">plot</span>(lm_age, <span class="at">which =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-lm-continuous_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>All in all, there do not appear to be any issues with the assumptions here.</p>
</div>
</div>
</div>
</section></section><section id="reporting-your-results" class="level2" data-number="1.5"><h2 data-number="1.5" class="anchored" data-anchor-id="reporting-your-results">
<span class="header-section-number">1.5</span> Reporting your results</h2>
<p>Now we have some results to go with, there are a few recommendations on how to communicate that information. In psychology (and other disciplines), we tend to follow the American Psychological Association (APA) formatting guidelines as they provide a comprehensive standardised style to make sure information is being reported as easily digestible and consistent as possible. You can see <a href="https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf" target="_blank">this PDF online</a> for a little cheat sheet for numbers and statistics, but we will outline some key principles to ensure you provide your reader with enough information.</p>
<ol type="1">
<li><p>Explain to the reader what your linear regression model was. For example, what was your outcome and predictor variable?</p></li>
<li><p>Report descriptive statistics to help contextualise your findings. For example, the mean/standard deviation for your outcome and continuous predictor.</p></li>
<li><p>Provide an appropriate data visualisation to help communciate key patterns to the reader. For example, a scatterplot for the relationship between your outcome and predictor.</p></li>
<li><p>Report all three key inferential statistics concepts for the coefficient: the slope, the confidence interval around your slope, and the <em>p</em>-value for hypothesis testing. When you have one predictor in simple linear regression, you typically focus on the slope as your key effect size that helps address your research question and hypothesis. APA style rounds numbers to 2 decimal places when numbers can be bigger than 1, and 3 decimals with no leading zero when it cannot be bigger than 1. When you report the unstandardised slope, you use the symbol <span class="math inline">\(b_1\)</span> but for the standardised slope, you use Beta instead <span class="math inline">\(\beta_1\)</span>.</p></li>
<li><p>Provide an overview of the model fit statistics for whether your model explained a significant amount of variance in your outcome. Remember: the <em>p</em>-value for your model will be the same as for the slope in simple linear regression.</p></li>
</ol>
<p>For our main example, we could summarise the findings as:</p>
<p>“Our research question was: is there a relationship between support for wealth redistribution and fairness and satisfaction with the current system? To test this, we applied simple linear regression using fairness and satisfaction as a predictor and support for wealth redistribution as our outcome. Figure 1 shows a scatterplot of the relationship.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-lm-continuous_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Our model explained a statistically significant amount of variance in our outcome (adjusted <span class="math inline">\(R^2\)</span> = .489, F(1, 303) = 291.70, <em>p</em> &lt; .001). Fairness and satisfaction was a negative predictor, where for every 1-unit increase we expect support for redistribution to decrease by 0.40 (<span class="math inline">\(b_1 = -0.40\)</span>, 95% CI = [-0.44, -0.35], <em>p</em> &lt; .001).”</p>
<p>Note: we have not included an APA formatted Figure title here as it is not easy to format in our book, so refer to the course materials for guidance.</p>
</section><section id="test-yourself" class="level2" data-number="1.6"><h2 data-number="1.6" class="anchored" data-anchor-id="test-yourself">
<span class="header-section-number">1.6</span> Test Yourself</h2>
<p>To end the chapter, we have some knowledge check questions to test your understanding of the concepts we covered in the chapter.</p>
<p>For this chapter’s knowledge check section, we have another example of linear regression from <span class="citation" data-cites="dawtry_why_2015">Dawtry et al. (<a href="references.html#ref-dawtry_why_2015" role="doc-biblioref">2015</a>)</span>. Feel free to create this model yourself, but we will show you some output and ask you questions based on it.</p>
<p>For this model, we focus on the two variables estimated population inequality index (<code>Population_Inequality_Gini_Index</code>) and support for wealth redistribution (<code>redistribution</code>). Check back to the code book in <a href="#08-explore">Activity 2</a> if you need a reminder of what the variables mean.</p>
<p><strong>Question 1</strong>. In the scatterplot of the relationship below, this shows a negative relationship between the inequality index and support for redistribution: <select class="webex-select"><option value="blank"></option>
<option value="">TRUE</option>
<option value="answer">FALSE</option></select>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="01-lm-continuous_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Question 2</strong> For the next few questions, we have the output from a linear regression model and we would like you to interpret it.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = redistribution ~ Population_Inequality_Gini_Index, 
    data = dawtry_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.9478 -0.6384  0.1389  0.8511  2.3854 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      3.097452   0.316914   9.774  &lt; 2e-16 ***
Population_Inequality_Gini_Index 0.022879   0.008734   2.619  0.00925 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.139 on 303 degrees of freedom
Multiple R-squared:  0.02214,   Adjusted R-squared:  0.01892 
F-statistic: 6.861 on 1 and 303 DF,  p-value: 0.009251</code></pre>
</div>
</div>
<p>The outcome variable in this model is <select class="webex-select"><option value="blank"></option>
<option value="answer">Attitudes on Wealth Redistribution</option>
<option value="">Population Inequality Index</option></select> and the predictor variable is <select class="webex-select"><option value="blank"></option>
<option value="">Attitudes on Wealth Redistribution</option>
<option value="answer">Population Inequality Index</option></select>.</p>
<p><strong>Question 3</strong> Rounded to 2 decimals, when the predictor is 0, we predict a value of <input class="webex-solveme nospaces" data-tol="0.1" size="3" data-answer="[&quot;3.1&quot;]"> for our outcome variable.</p>
<p><strong>Question 4</strong> The predictor is <select class="webex-select"><option value="blank"></option>
<option value="answer">significant</option>
<option value="">non-significant</option></select> with a <em>p</em>-value of <input class="webex-solveme nospaces" size="5" data-answer="[&quot;0.009&quot;,&quot;.009&quot;]">.</p>
<p><strong>Question 5</strong> The predictor is <select class="webex-select"><option value="blank"></option>
<option value="answer">positive</option>
<option value="">negative</option></select>, where we expect for every 1-unit increase in the predictor a <input class="webex-solveme nospaces" size="4" data-answer="[&quot;0.02&quot;,&quot;.02&quot;]"> -unit <select class="webex-select"><option value="blank"></option>
<option value="answer">increase</option>
<option value="">decrease</option></select> in the outcome.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-dawtry_why_2015" class="csl-entry" role="listitem">
Dawtry, R. J., Sutton, R. M., &amp; Sibley, C. G. (2015). Why <span>Wealthier</span> <span>People</span> <span>Think</span> <span>People</span> <span>Are</span> <span>Wealthier</span>, and <span>Why</span> <span>It</span> <span>Matters</span>: <span>From</span> <span>Social</span> <span>Sampling</span> to <span>Attitudes</span> to <span>Redistribution</span>. <em>Psychological Science</em>, <em>26</em>(9), 1389–1400. <a href="https://doi.org/10.1177/0956797615586560">https://doi.org/10.1177/0956797615586560</a>
</div>
</div>
</section></main><!-- /main --><script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script><script>
// open rdrr links externally ----

var exlinks = document.querySelectorAll("a[href^='https://rdrr.io']");
var exlink_func = function(){
  window.open(this.href);
  return false;
};
for (var i = 0; i < exlinks.length; i++) {
    exlinks[i].addEventListener('click', exlink_func, false);
}

// visible second sidebar in mobile ----

function move_sidebar() {
  var toc = document.getElementById("TOC");
  var small_sidebar = document.querySelector("#quarto-sidebar .sidebar-menu-container");
  var right_sidebar = document.getElementById("quarto-margin-sidebar");

  if (window.innerWidth < 768) {
    small_sidebar.append(toc);
  } else {
    right_sidebar.append(toc);
  }
}
move_sidebar();
window.onresize = move_sidebar;
</script><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link" aria-label="Overview">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Overview</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./02-lm-categorical.html" class="pagination-link" aria-label="Regression with one categorical predictor">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression with one categorical predictor</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>CC-BY (2025) Bartlett, Rousselet, &amp; DeBruine.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>