<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Materials for the MSc Statistics and Research Design course at the University of Glasgow.">
<title>3&nbsp; Multiple Linear Regression – Statistics and Research Design</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-screening-data.html" rel="next">
<link href="./02-lm-categorical.html" rel="prev">
<link href="./images/logos/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-6NP3MF25W3', { 'anonymize_ip': true});
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" href="include/booktem.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/glossary.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-lm-multiple.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics and Research Design</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-lm-continuous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Regression with one continuous predictor</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-lm-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression with one categorical predictor</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-lm-multiple.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-screening-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Missing data, outliers, and checking assumptions</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#chapter-preparation" id="toc-chapter-preparation" class="nav-link active" data-scroll-target="#chapter-preparation"><span class="header-section-number">3.1</span> Chapter preparation</a>
  <ul class="collapse">
<li><a href="#organising-your-files-and-project-for-the-chapter" id="toc-organising-your-files-and-project-for-the-chapter" class="nav-link" data-scroll-target="#organising-your-files-and-project-for-the-chapter"><span class="header-section-number">3.1.1</span> Organising your files and project for the chapter</a></li>
  </ul>
</li>
  <li>
<a href="#coding-schemes" id="toc-coding-schemes" class="nav-link" data-scroll-target="#coding-schemes"><span class="header-section-number">3.2</span> Different categorical predictor coding schemes</a>
  <ul class="collapse">
<li><a href="#introduction-to-the-dataset" id="toc-introduction-to-the-dataset" class="nav-link" data-scroll-target="#introduction-to-the-dataset"><span class="header-section-number">3.2.1</span> Introduction to the dataset</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">3.2.2</span> Exploratory data analysis</a></li>
  <li><a href="#no-specific-coding" id="toc-no-specific-coding" class="nav-link" data-scroll-target="#no-specific-coding"><span class="header-section-number">3.2.3</span> No specific coding</a></li>
  <li><a href="#dummy-coding" id="toc-dummy-coding" class="nav-link" data-scroll-target="#dummy-coding"><span class="header-section-number">3.2.4</span> Dummy coding</a></li>
  <li><a href="#deviation-coding" id="toc-deviation-coding" class="nav-link" data-scroll-target="#deviation-coding"><span class="header-section-number">3.2.5</span> Deviation coding</a></li>
  </ul>
</li>
  <li>
<a href="#multiple-linear-regression-with-individual-predictors" id="toc-multiple-linear-regression-with-individual-predictors" class="nav-link" data-scroll-target="#multiple-linear-regression-with-individual-predictors"><span class="header-section-number">3.3</span> Multiple linear regression with individual predictors</a>
  <ul class="collapse">
<li><a href="#introduction-to-the-dataset-1" id="toc-introduction-to-the-dataset-1" class="nav-link" data-scroll-target="#introduction-to-the-dataset-1"><span class="header-section-number">3.3.1</span> Introduction to the dataset</a></li>
  <li><a href="#visualise-the-relationship" id="toc-visualise-the-relationship" class="nav-link" data-scroll-target="#visualise-the-relationship"><span class="header-section-number">3.3.2</span> Visualise the relationship</a></li>
  <li><a href="#model-1-situational-factors" id="toc-model-1-situational-factors" class="nav-link" data-scroll-target="#model-1-situational-factors"><span class="header-section-number">3.3.3</span> Model 1: Situational factors</a></li>
  <li><a href="#model-2-situational-and-individual-factors" id="toc-model-2-situational-and-individual-factors" class="nav-link" data-scroll-target="#model-2-situational-and-individual-factors"><span class="header-section-number">3.3.4</span> Model 2: Situational and individual factors</a></li>
  <li><a href="#model-comparison" id="toc-model-comparison" class="nav-link" data-scroll-target="#model-comparison"><span class="header-section-number">3.3.5</span> Model comparison</a></li>
  </ul>
</li>
  <li>
<a href="#multiple-linear-regression-with-interactions" id="toc-multiple-linear-regression-with-interactions" class="nav-link" data-scroll-target="#multiple-linear-regression-with-interactions"><span class="header-section-number">3.4</span> Multiple linear regression with interactions</a>
  <ul class="collapse">
<li><a href="#coding-schemes-for-interactions" id="toc-coding-schemes-for-interactions" class="nav-link" data-scroll-target="#coding-schemes-for-interactions"><span class="header-section-number">3.4.1</span> Coding schemes for interactions</a></li>
  <li><a href="#categorical-by-categorical-interactions" id="toc-categorical-by-categorical-interactions" class="nav-link" data-scroll-target="#categorical-by-categorical-interactions"><span class="header-section-number">3.4.2</span> Categorical by categorical interactions</a></li>
  <li><a href="#continuous-by-categorical-interactions" id="toc-continuous-by-categorical-interactions" class="nav-link" data-scroll-target="#continuous-by-categorical-interactions"><span class="header-section-number">3.4.3</span> Continuous by categorical interactions</a></li>
  <li><a href="#continuous-by-continuous-interactions" id="toc-continuous-by-continuous-interactions" class="nav-link" data-scroll-target="#continuous-by-continuous-interactions"><span class="header-section-number">3.4.4</span> Continuous by continuous interactions</a></li>
  </ul>
</li>
  <li>
<a href="#test-yourself" id="toc-test-yourself" class="nav-link" data-scroll-target="#test-yourself"><span class="header-section-number">3.5</span> Test Yourself</a>
  <ul class="collapse">
<li><a href="#introduction-to-the-dataset-2" id="toc-introduction-to-the-dataset-2" class="nav-link" data-scroll-target="#introduction-to-the-dataset-2"><span class="header-section-number">3.5.1</span> Introduction to the dataset</a></li>
  <li><a href="#model-1-individual-predictors" id="toc-model-1-individual-predictors" class="nav-link" data-scroll-target="#model-1-individual-predictors"><span class="header-section-number">3.5.2</span> Model 1: Individual predictors</a></li>
  <li><a href="#model-2-interaction-term" id="toc-model-2-interaction-term" class="nav-link" data-scroll-target="#model-2-interaction-term"><span class="header-section-number">3.5.3</span> Model 2: Interaction term</a></li>
  <li><a href="#model-comparison-1" id="toc-model-comparison-1" class="nav-link" data-scroll-target="#model-comparison-1"><span class="header-section-number">3.5.4</span> Model comparison</a></li>
  </ul>
</li>
  <li><a href="#words-from-this-chapter" id="toc-words-from-this-chapter" class="nav-link" data-scroll-target="#words-from-this-chapter"><span class="header-section-number">3.6</span> Words from this Chapter</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>In this chapter, we build on the Chapter 1 and 2 content where you learnt about the general linear model and applied it to the case of simple linear regression. In this chapter, we will extend that framework for when you want to want to include multiple predictor variables and interactions between predictors. We will cover concepts like standardised and unstandardised predictors, and different coding schemes for predictor variables.</p>
<p><strong>Chapter Intended Learning Outcomes (ILOs)</strong></p>
<p>By the end of this chapter, you will be able to:</p>
<ol type="1">
<li><p>Understand different predictor coding schemes.</p></li>
<li><p>Understand the difference between unstandardised and standardised beta coefficients.</p></li>
<li><p>Understand how to run and interpret a regression for multiple predictors.</p></li>
<li><p>Understand how to run and interpret a regression containing interaction terms.</p></li>
</ol>
<section id="chapter-preparation" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="chapter-preparation">
<span class="header-section-number">3.1</span> Chapter preparation</h2>
<p>In this chapter, we need a few different datasets, so we will introduce them as we need them.</p>
<section id="organising-your-files-and-project-for-the-chapter" class="level3" data-number="3.1.1"><h3 data-number="3.1.1" class="anchored" data-anchor-id="organising-your-files-and-project-for-the-chapter">
<span class="header-section-number">3.1.1</span> Organising your files and project for the chapter</h3>
<p>Before we can get started, you need to organise your files and project for the chapter, so your working directory is in order.</p>
<ol type="1">
<li><p>In your folder for statistics and research design <code>Stats_Research_Design</code>, create a new folder called <code>03_regression_multiple</code>. Within <code>03_regression_multiple</code>, create two new folders called <code>data</code> and <code>figures</code>.</p></li>
<li><p>Create an R Project for <code>03_regression_multiple</code> as an existing directory for your chapter folder. This should now be your working directory.</p></li>
<li><p>Create a new Quarto document and give it a sensible title describing the chapter, such as <code>03 Multiple Regression</code>. Save the file in your <code>03_regression_multiple</code> folder.</p></li>
<li><p>We are working with a few data sets in this chapter, so please save the following zip file containing all the data files you need: <a href="data/03_data.zip">Chapter 03 Data</a>. Right click the link and select “save link as”, or clicking the link will save the file to your Downloads. Extract the files and make sure that you save them as “.csv”. Save or copy the files to your <code>data/</code> folder within <code>03_regression_multiple</code>.</p></li>
</ol>
<p>You are now ready to start working on the chapter!</p>
</section></section><section id="coding-schemes" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="coding-schemes">
<span class="header-section-number">3.2</span> Different categorical predictor coding schemes</h2>
<section id="introduction-to-the-dataset" class="level3" data-number="3.2.1"><h3 data-number="3.2.1" class="anchored" data-anchor-id="introduction-to-the-dataset">
<span class="header-section-number">3.2.1</span> Introduction to the dataset</h3>
<p>To demonstrate different predictor coding schemes, we will use data from <span class="citation" data-cites="james_computer_2015">James et al. (<a href="references.html#ref-james_computer_2015" role="doc-biblioref">2015</a>)</span> who wanted to find non-pharmacological interventions for reducing intrusive memories of traumatic events. They compared four conditions:</p>
<ol type="1">
<li><p>No-task control: Participants completed a 10-minute filler task.</p></li>
<li><p>Reactivation + Tetris: Participants were shown a series of images from a trauma film to reactivate traumatic memories. After a filler task, participants played Tetris for 12 minutes.</p></li>
<li><p>Tetris Only: Participants played Tetris for 12 minutes in isolation.</p></li>
<li><p>Reactivation Only: Participants completed the reactivation task in isolation.</p></li>
</ol>
<p>Their research question was: Would the reactivation and Tetris condition lead to fewer intrusive memories? They predicted the reactivation and Tetris group will have fewer intrusive memories in the week after experimental trauma exposure compared to the other three groups.</p>
<p>This means there is one predictor variable <code>Condition</code> with four levels, one for each experimental condition. We then have one outcome variable <code>post_intrusions</code> for the number of intrusive memories they recorded in the week after the experiment. To support the hypothesis, <code>post_intrusions</code> should decrease in group 2 compared to the three other groups.</p>
<p>We first need to load some packages and the data for the tasks throughout this chapter. If you do not have any of the packages, make sure you install them first.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># wrangling and visualisation functions </span></span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="co"># Regression interaction plots</span></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb1-5"><a href="#cb1-5"></a><span class="co"># Standardise model coefficients</span></span>
<span id="cb1-6"><a href="#cb1-6"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb1-7"><a href="#cb1-7"></a><span class="co"># VIF and other regression functions</span></span>
<span id="cb1-8"><a href="#cb1-8"></a><span class="fu">library</span>(car)</span>
<span id="cb1-9"><a href="#cb1-9"></a><span class="co"># Interaction estimates</span></span>
<span id="cb1-10"><a href="#cb1-10"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb1-11"><a href="#cb1-11"></a><span class="co"># Checking model assumptions</span></span>
<span id="cb1-12"><a href="#cb1-12"></a><span class="fu">library</span>(performance)</span>
<span id="cb1-13"><a href="#cb1-13"></a></span>
<span id="cb1-14"><a href="#cb1-14"></a><span class="co"># Load data for coding schemes</span></span>
<span id="cb1-15"><a href="#cb1-15"></a>james_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/James_2015.csv"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb1-16"><a href="#cb1-16"></a>  <span class="fu">mutate</span>(<span class="at">Condition =</span> <span class="fu">as.factor</span>(Condition)) <span class="sc">%&gt;%</span> </span>
<span id="cb1-17"><a href="#cb1-17"></a>  <span class="fu">rename</span>(<span class="at">post_intrusions =</span> Days_One_to_Seven_Number_of_Intrusions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="exploratory-data-analysis" class="level3" data-number="3.2.2"><h3 data-number="3.2.2" class="anchored" data-anchor-id="exploratory-data-analysis">
<span class="header-section-number">3.2.2</span> Exploratory data analysis</h3>
<p>When starting any data analysis, it is important to visualise the data for some exploratory data analysis. Using the skills you developed in Data Skills for Reproducible Research, you can explore the data to understand its properties and look for potential patterns. We can create a boxplot to get a brief overview of how the number of intrusive memories changes across the four condition groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>james_data <span class="sc">%&gt;%</span> </span>
<span id="cb2-2"><a href="#cb2-2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Condition, <span class="at">y =</span> post_intrusions)) <span class="sc">+</span> </span>
<span id="cb2-3"><a href="#cb2-3"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb2-4"><a href="#cb2-4"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Number of Intrusive Memories"</span>) <span class="sc">+</span></span>
<span id="cb2-5"><a href="#cb2-5"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">name =</span> <span class="st">"Experimental Task"</span>, </span>
<span id="cb2-6"><a href="#cb2-6"></a>                   <span class="at">label =</span> <span class="fu">c</span>(<span class="st">"Control"</span>, <span class="st">"Reactivation + Tetris"</span>, <span class="st">"Tetris"</span>, <span class="st">"Reactivation"</span>)) <span class="sc">+</span> </span>
<span id="cb2-7"><a href="#cb2-7"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-lm-multiple_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see group 2 (reactivation + Tetris) has the lowest score, but we need inferential statistics to test the hypothesis.</p>
</section><section id="no-specific-coding" class="level3" data-number="3.2.3"><h3 data-number="3.2.3" class="anchored" data-anchor-id="no-specific-coding">
<span class="header-section-number">3.2.3</span> No specific coding</h3>
<p>For a starting point, we can see what it looks like if you enter <code>post_intrusions</code> as the outcome and <code>Condition</code> as the predictor in simple linear regression with no specific coding scheme.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>james_nocoding <span class="ot">&lt;-</span> <span class="fu">lm</span>(post_intrusions <span class="sc">~</span> Condition, </span>
<span id="cb3-2"><a href="#cb3-2"></a>                     <span class="at">data =</span> james_data)</span>
<span id="cb3-3"><a href="#cb3-3"></a></span>
<span id="cb3-4"><a href="#cb3-4"></a><span class="fu">summary</span>(james_nocoding)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = post_intrusions ~ Condition, data = james_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.1111 -1.8889 -0.8333  1.1111 10.8889 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   5.1111     0.7485   6.828 2.89e-09 ***
Condition2   -3.2222     1.0586  -3.044  0.00332 ** 
Condition3   -1.2222     1.0586  -1.155  0.25231    
Condition4   -0.2778     1.0586  -0.262  0.79381    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.176 on 68 degrees of freedom
Multiple R-squared:  0.1434,    Adjusted R-squared:  0.1056 
F-statistic: 3.795 on 3 and 68 DF,  p-value: 0.01409</code></pre>
</div>
</div>
<p>Although we use <code>Condition</code> as a single predictor, we actually get three different predictors. In regression, it can only compare two groups at a time, so it will apply dummy coding to your groups. You get <em>k</em>-1 predictors, where there will be one fewer predictors than there are groups.</p>
<p>Using what you learnt in chapters 1 and 2, we can see its a significant model, but the only significant predictor is <code>Condition2</code>. Group 1 is the reference group as the intercept, so <code>Condition2</code> tells you the mean difference between group 1 and group 2. We compare each group successively to the reference, so <code>Condition3</code> is the mean difference between group 1 and group 3 etc.</p>
</section><section id="dummy-coding" class="level3" data-number="3.2.4"><h3 data-number="3.2.4" class="anchored" data-anchor-id="dummy-coding">
<span class="header-section-number">3.2.4</span> Dummy coding</h3>
<p>To demonstrate different coding schemes, we will start with dummy coding. Dummy coding is the default in R and when we entered <code>Condition</code> as a predictor, this is what R does behind the scenes. However, we have no control over the process and the reference group/intercept will be first in numerical or alphabetical order, then each successive <em>k</em>-1 group will be added as separate predictors.</p>
<p>Instead, we can define our own dummy coding to control the reference and target groups. This is particularly useful when you have specific hypotheses like in <span class="citation" data-cites="james_computer_2015">James et al. (<a href="references.html#ref-james_computer_2015" role="doc-biblioref">2015</a>)</span>, as we are interested in the combined reactivation and Tetris group (group 2). This means we can code for condition 2 as the reference group / intercept, and the other groups are coded as individual predictors.</p>
<p>For dummy coding, you will have <em>k</em>-1 predictors, meaning one fewer predictor than the number of groups. Since we have four groups, we will need to create three predictors. In the code below, our reference group will always be set to 0. Then, for each dummy coded predictor, we will set the target group to 1. Each target group will be 1 for when it is a predictor, but reactivation and Tetris (condition 2) will always be set to 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="co"># Dummy code condition 2 as 0 for each comparison, and each successive group as 1</span></span>
<span id="cb5-2"><a href="#cb5-2"></a>james_data <span class="ot">&lt;-</span> james_data <span class="sc">%&gt;%</span> </span>
<span id="cb5-3"><a href="#cb5-3"></a>  <span class="co"># For each group at a time, code as 1, with the default set to 0 for all other groups</span></span>
<span id="cb5-4"><a href="#cb5-4"></a>  <span class="fu">mutate</span>(<span class="at">RT_control =</span> <span class="fu">case_when</span>(Condition <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb5-5"><a href="#cb5-5"></a>                                <span class="at">.default =</span> <span class="dv">0</span>),</span>
<span id="cb5-6"><a href="#cb5-6"></a>         <span class="at">RT_tetris =</span> <span class="fu">case_when</span>(Condition <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb5-7"><a href="#cb5-7"></a>                               <span class="at">.default =</span> <span class="dv">0</span>),</span>
<span id="cb5-8"><a href="#cb5-8"></a>         <span class="at">RT_reactivation =</span> <span class="fu">case_when</span>(Condition <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb5-9"><a href="#cb5-9"></a>                                     <span class="at">.default =</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can get an overview of how this looks by checking the distinct values against <code>Condition</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>james_data <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2"></a>  <span class="fu">distinct</span>(Condition, RT_control, RT_tetris, RT_reactivation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">RT_control</th>
<th style="text-align: right;">RT_tetris</th>
<th style="text-align: right;">RT_reactivation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The three predictors show how each comparison is dummy coded. For <code>RT_control</code>, group 1 is coded 1 and all the others are coded 0. For <code>RT_tetris</code>, group 3 is coded 1 and all the others are coded 0 etc. Group 2 is the only one without ever being coded 1.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Remember the interpretation of the intercept is what the outcome value is when the predictors are set to 0. Setting all the predictors to 0 would indicate group 2 in this case, so that represents our reference group. See the predictors as little switches to turn on and off, and when they are all turned off (0), that represents the reference group.</p>
</div>
</div>
<p>We can now see what this looks like as our regression model containing dummy coded predictors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>james_dummy <span class="ot">&lt;-</span> <span class="fu">lm</span>(post_intrusions <span class="sc">~</span> RT_control <span class="sc">+</span> RT_tetris <span class="sc">+</span> RT_reactivation, </span>
<span id="cb7-2"><a href="#cb7-2"></a>                  <span class="at">data =</span> james_data)</span>
<span id="cb7-3"><a href="#cb7-3"></a></span>
<span id="cb7-4"><a href="#cb7-4"></a><span class="fu">summary</span>(james_dummy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = post_intrusions ~ RT_control + RT_tetris + RT_reactivation, 
    data = james_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.1111 -1.8889 -0.8333  1.1111 10.8889 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)       1.8889     0.7485   2.523  0.01396 * 
RT_control        3.2222     1.0586   3.044  0.00332 **
RT_tetris         2.0000     1.0586   1.889  0.06312 . 
RT_reactivation   2.9444     1.0586   2.781  0.00700 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.176 on 68 degrees of freedom
Multiple R-squared:  0.1434,    Adjusted R-squared:  0.1056 
F-statistic: 3.795 on 3 and 68 DF,  p-value: 0.01409</code></pre>
</div>
</div>
<p>This gives us a similar result to before, some of the coefficients are even the same, but we are controlling what the reference group is for the intercept, and what each target comparison is. They are all positive predictors showing the number of intrusive memories is higher in each control group compared to the combined reactivation and Tetris group. However, the difference to Tetris in isolation is not statistically significant.</p>
<p>For these initial steps, it is also a good opportunity to sense check how the comparisons work. The intercept is the mean for our reference group - reactivation plus Tetris. Each coefficient is then the mean difference for each target group against the reference. We can show this is the case by comparing the means.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co"># Calculate and isolate the mean for group 2 as our reference group</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>RT_mean <span class="ot">&lt;-</span> james_data <span class="sc">%&gt;%</span> </span>
<span id="cb9-3"><a href="#cb9-3"></a>  <span class="co"># Isolate group 2</span></span>
<span id="cb9-4"><a href="#cb9-4"></a>  <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb9-5"><a href="#cb9-5"></a>  <span class="fu">summarise</span>(<span class="at">mean_intrusions =</span> <span class="fu">mean</span>(post_intrusions)) <span class="sc">%&gt;%</span> </span>
<span id="cb9-6"><a href="#cb9-6"></a>  <span class="co"># Isolate the first value</span></span>
<span id="cb9-7"><a href="#cb9-7"></a>  <span class="fu">pluck</span>(<span class="dv">1</span>)</span>
<span id="cb9-8"><a href="#cb9-8"></a></span>
<span id="cb9-9"><a href="#cb9-9"></a><span class="co"># For each other group, calculate the mean difference between the group mean and RT mean</span></span>
<span id="cb9-10"><a href="#cb9-10"></a>james_data <span class="sc">%&gt;%</span> </span>
<span id="cb9-11"><a href="#cb9-11"></a>  <span class="co"># Omit group 2</span></span>
<span id="cb9-12"><a href="#cb9-12"></a>  <span class="fu">filter</span>(Condition <span class="sc">!=</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb9-13"><a href="#cb9-13"></a>  <span class="co"># Get mean difference for all other groups</span></span>
<span id="cb9-14"><a href="#cb9-14"></a>  <span class="fu">group_by</span>(Condition) <span class="sc">%&gt;%</span> </span>
<span id="cb9-15"><a href="#cb9-15"></a>  <span class="fu">summarise</span>(<span class="at">mean_difference =</span> <span class="fu">mean</span>(post_intrusions) <span class="sc">-</span> RT_mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">mean_difference</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">3.222222</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: right;">2.000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: right;">2.944444</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>We can see the mean for group 2 and the mean differences align with exactly what we expect. It is important to work through the process now as the group means align with the model estimates. This will not be the case when we have multiple predictors since the coefficients become partial effects.</p>
</div>
</div>
</section><section id="deviation-coding" class="level3" data-number="3.2.5"><h3 data-number="3.2.5" class="anchored" data-anchor-id="deviation-coding">
<span class="header-section-number">3.2.5</span> Deviation coding</h3>
<p>Finally, we have deviation coding. This is more useful once we get to interactions later, but it is easier to see the logic behind what it is doing when we have no other predictors to worry about.</p>
<p>Remember, in dummy coding, the intercept is the reference group mean, and each dummy coded predictor is the mean difference against the reference group.</p>
<p>In deviation coding, the interpretation of the intercept changes to be the grand mean of all observations, i.e., taking the mean of all four groups. The coefficients are then the difference between each comparison group with the grand mean for a main effect. We still need to create a new predictor for <em>k</em>-1 groups, but instead of coding 0 and 1, we use 0.5 and -0.5.</p>
<p>You might see different ways of deviation coding. When you use 0.5/-0.5, you can calculate the effect of the group as 0.5 times the slope, which tells you the difference to the grand mean. For 1/-1. you calculate the effect of the group as 1 times the slope, which tells you the difference to the grand mean. We will typically use 0.5/-0.5 for consistency with other materials, but be aware you might see each approach.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="co"># Create deviation coding for k-1 groups</span></span>
<span id="cb10-2"><a href="#cb10-2"></a><span class="co"># In this method, group 2 as our reference will be -0.5 in each comparison. </span></span>
<span id="cb10-3"><a href="#cb10-3"></a><span class="co"># Variables not included in the predictor are set to 0</span></span>
<span id="cb10-4"><a href="#cb10-4"></a><span class="co"># The target group is set to 0.5 for each predictor</span></span>
<span id="cb10-5"><a href="#cb10-5"></a>james_data <span class="ot">&lt;-</span> james_data <span class="sc">%&gt;%</span> </span>
<span id="cb10-6"><a href="#cb10-6"></a>  <span class="fu">mutate</span>(<span class="at">control_deviation =</span> <span class="fu">case_when</span>(Condition <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="fl">0.5</span>,</span>
<span id="cb10-7"><a href="#cb10-7"></a>                                       Condition <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>) <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb10-8"><a href="#cb10-8"></a>                                       Condition <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="sc">-</span><span class="fl">0.5</span>),</span>
<span id="cb10-9"><a href="#cb10-9"></a>         <span class="at">tetris_deviation =</span> <span class="fu">case_when</span>(Condition <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="fl">0.5</span>,</span>
<span id="cb10-10"><a href="#cb10-10"></a>                                       Condition <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">4</span>) <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb10-11"><a href="#cb10-11"></a>                                       Condition <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="sc">-</span><span class="fl">0.5</span>),</span>
<span id="cb10-12"><a href="#cb10-12"></a>         <span class="at">reactivation_deviation =</span> <span class="fu">case_when</span>(Condition <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="fl">0.5</span>,</span>
<span id="cb10-13"><a href="#cb10-13"></a>                                       Condition <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>) <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb10-14"><a href="#cb10-14"></a>                                       Condition <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="sc">-</span><span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As before, we can get an overview of how this looks by checking the distinct values against <code>Condition</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>james_data <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2"></a>  <span class="fu">distinct</span>(Condition, </span>
<span id="cb11-3"><a href="#cb11-3"></a>           control_deviation, </span>
<span id="cb11-4"><a href="#cb11-4"></a>           tetris_deviation, </span>
<span id="cb11-5"><a href="#cb11-5"></a>           reactivation_deviation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 26%">
<col style="width: 25%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">control_deviation</th>
<th style="text-align: right;">tetris_deviation</th>
<th style="text-align: right;">reactivation_deviation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">-0.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.5</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The three predictors show how each comparison is deviation coded. For <code>control_deviation</code>, group 1 is coded 0.5, the predictors to ignore are coded 0, and the target group is coded -0.5. For <code>tetris_deviation</code>, group 3 is coded 0.5 etc. Group 2 is always coded -0.5 in this case.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Remember the interpretation of the intercept is what the outcome value is when the predictors are set to 0. The interpretation shifts here as the intercept represents the grand mean across the group. When the predictors are set to 0, the outcome is in the middle of -0.5 and 0.5, so its the mid point or average. When you do not have interactions, this might not be as useful, but its easier to understand the logic when there are no partial effects.</p>
</div>
</div>
<p>We can now see what this looks like for our regression model containing deviation coded predictors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>james_deviation <span class="ot">&lt;-</span> <span class="fu">lm</span>(post_intrusions <span class="sc">~</span> control_deviation <span class="sc">+</span> tetris_deviation <span class="sc">+</span> reactivation_deviation, </span>
<span id="cb12-2"><a href="#cb12-2"></a>                      <span class="at">data =</span> james_data)</span>
<span id="cb12-3"><a href="#cb12-3"></a></span>
<span id="cb12-4"><a href="#cb12-4"></a><span class="fu">summary</span>(james_deviation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = post_intrusions ~ control_deviation + tetris_deviation + 
    reactivation_deviation, data = james_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.1111 -1.8889 -0.8333  1.1111 10.8889 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             3.93056    0.37427  10.502 7.11e-16 ***
control_deviation       2.36111    1.29652   1.821    0.073 .  
tetris_deviation       -0.08333    1.29652  -0.064    0.949    
reactivation_deviation  1.80556    1.29652   1.393    0.168    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.176 on 68 degrees of freedom
Multiple R-squared:  0.1434,    Adjusted R-squared:  0.1056 
F-statistic: 3.795 on 3 and 68 DF,  p-value: 0.01409</code></pre>
</div>
</div>
<p>This time, the results look a little different. None of the coefficients are significant, but importantly, the model is exactly the same. We are still explaining the same amount of variance in the outcome, but the way we are expressing it is different.</p>
<p>Deviation coding is tricky at first to appreciate what its doing, so working through the logic is even more important than for dummy coding. This time, we need to calculate the grand mean of all observations, then compare the coefficients against the grand mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="co"># Calculate and isolate the grand mean of all groups</span></span>
<span id="cb14-2"><a href="#cb14-2"></a>grand_mean <span class="ot">&lt;-</span> james_data <span class="sc">%&gt;%</span> </span>
<span id="cb14-3"><a href="#cb14-3"></a>  <span class="fu">summarise</span>(<span class="at">mean_intrusions =</span> <span class="fu">mean</span>(post_intrusions)) <span class="sc">%&gt;%</span> </span>
<span id="cb14-4"><a href="#cb14-4"></a>  <span class="fu">pluck</span>(<span class="dv">1</span>)</span>
<span id="cb14-5"><a href="#cb14-5"></a></span>
<span id="cb14-6"><a href="#cb14-6"></a><span class="co"># Calculate the mean number of intrusions for each group</span></span>
<span id="cb14-7"><a href="#cb14-7"></a><span class="co"># Then calculate the deviations as 2 times the mean difference </span></span>
<span id="cb14-8"><a href="#cb14-8"></a>james_data <span class="sc">%&gt;%</span> </span>
<span id="cb14-9"><a href="#cb14-9"></a>  <span class="fu">group_by</span>(Condition) <span class="sc">%&gt;%</span> </span>
<span id="cb14-10"><a href="#cb14-10"></a>  <span class="fu">summarise</span>(<span class="at">mean_intrusions =</span> <span class="fu">mean</span>(post_intrusions),</span>
<span id="cb14-11"><a href="#cb14-11"></a>            <span class="at">deviations =</span> (grand_mean <span class="sc">-</span> <span class="fu">mean</span>(post_intrusions)) <span class="sc">*</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">mean_intrusions</th>
<th style="text-align: right;">deviations</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">5.111111</td>
<td style="text-align: right;">-2.3611111</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">1.888889</td>
<td style="text-align: right;">4.0833333</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">3.888889</td>
<td style="text-align: right;">0.0833333</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">4.833333</td>
<td style="text-align: right;">-1.8055556</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>We can see the grand mean and deviations align with exactly what we expect. It is trickier than dummy coding, but this is what deviation coding does. Note in the model you do not get the group 2 contrast as that’s always the reference group and we are ignoring the sign of the deviation to check its consistency. Also pay attention to calculating 2 times the difference, since we used 0.5/-0.5 as the coding scheme.</p>
<p>It is important to work through the process now as the deviations align with the model estimates. This will not be the case when we have multiple predictors since the coefficients become partial predictors.</p>
</div>
</div>
</section></section><section id="multiple-linear-regression-with-individual-predictors" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="multiple-linear-regression-with-individual-predictors">
<span class="header-section-number">3.3</span> Multiple linear regression with individual predictors</h2>
<section id="introduction-to-the-dataset-1" class="level3" data-number="3.3.1"><h3 data-number="3.3.1" class="anchored" data-anchor-id="introduction-to-the-dataset-1">
<span class="header-section-number">3.3.1</span> Introduction to the dataset</h3>
<p>To demonstrate multiple linear regression models, we will use data from <span class="citation" data-cites="evans_unethical_2024">Evans (<a href="references.html#ref-evans_unethical_2024" role="doc-biblioref">2024</a>)</span> (the stage two manuscript is currently under review) who performed a multi-site registered replication report containing 2218 participants. They wanted to replicate <span class="citation" data-cites="jones_experimental_1996">Jones &amp; Kavanagh (<a href="references.html#ref-jones_experimental_1996" role="doc-biblioref">1996</a>)</span> - an influential study in organisational psychology on unethical workplace behaviour. The variables can be split into two types. The first are situational factors and relate to experimental manipulations on a vignette that participants read:</p>
<ol type="1">
<li><p>Workplace environment (<code>QWE</code>): Your workplace environment is described as high or low quality.</p></li>
<li><p>Manager influence (<code>MI</code>): Your manager is described as behaving ethically or unethically.</p></li>
<li><p>Peer influence (<code>PI</code>): Your peers are described as behaving ethically or unethically.</p></li>
</ol>
<p>The second group of variables are individual and relate to the participant rather than being experimentally manipulated:</p>
<ol type="1">
<li><p>Locus of control (<code>LOCTot</code>): A measure of whether someone attributes events internally or externally.</p></li>
<li><p>Social desirability (<code>SocDesTot</code>): A measure of whether someone would respond in a way that would make them look better than they would typically act.</p></li>
<li><p>Machiavellianism (<code>MachTot</code>): A personality trait that is part of the dark-triad, showing a lack of empathy and willingness to manipulate others.</p></li>
</ol>
<p>The outcome in the study was then the participant’s unethical workplace behaviour intention (<code>BehIntTot</code>). The vignette described a situation in a company and the unethical behaviour was whether you would manipulate expense requests to claim more money than you really should. There were four questions which were added up to range from 4 to 20, with higher values meaning greater intention to behave unethically.</p>
<p>Our research question for this study is: What is the effect of individual and situational factors on unethical workplace behaviour intentions? We will not pose specific hypotheses, but we essentially predict that these six factors will affect someone’s unethical workplace behaviour intention.</p>
<p>To start with, we will load the data and set the factor levels for independent variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="co"># Load data for multiple linear regression</span></span>
<span id="cb15-2"><a href="#cb15-2"></a>evans_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Evans_2023.csv"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb15-3"><a href="#cb15-3"></a>  <span class="fu">mutate</span>(<span class="at">QWE =</span> <span class="fu">factor</span>(QWE, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"low"</span>, <span class="st">"high"</span>)),</span>
<span id="cb15-4"><a href="#cb15-4"></a>         <span class="at">MI =</span> <span class="fu">factor</span>(MI, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"unethical"</span>, <span class="st">"ethical"</span>)),</span>
<span id="cb15-5"><a href="#cb15-5"></a>         <span class="at">PI =</span> <span class="fu">factor</span>(PI, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"unethical"</span>, <span class="st">"ethical"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="visualise-the-relationship" class="level3" data-number="3.3.2"><h3 data-number="3.3.2" class="anchored" data-anchor-id="visualise-the-relationship">
<span class="header-section-number">3.3.2</span> Visualise the relationship</h3>
<p>When starting any data analysis, it is important to visualise the data for some exploratory data analysis. Using the skills you developed in Data Skills for Reproducible Research, explore the data understand its properties and look for potential patterns.</p>
<p>Please try this yourself and explore different variables and their relationship to unethical workplace behaviour. For example, we can look at the effect of quality of workplace environment:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>evans_data <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> QWE, <span class="at">y =</span> BehIntTot)) <span class="sc">+</span> </span>
<span id="cb16-3"><a href="#cb16-3"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb16-4"><a href="#cb16-4"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Sum of Behavioural Intentions"</span>) <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">name =</span> <span class="st">"Quality of Workplace Environment"</span>, <span class="at">label =</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"High"</span>)) <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-lm-multiple_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Alternatively, we might look at the relationship between unethical behaviour intention and Machiavellianism:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a>evans_data <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> MachTot, <span class="at">y =</span> BehIntTot)) <span class="sc">+</span> </span>
<span id="cb17-3"><a href="#cb17-3"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb17-4"><a href="#cb17-4"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span> </span>
<span id="cb17-5"><a href="#cb17-5"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Sum of Behavioural Intentions"</span>) <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">name =</span> <span class="st">"Machiavellianism"</span>) <span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-lm-multiple_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="model-1-situational-factors" class="level3" data-number="3.3.3"><h3 data-number="3.3.3" class="anchored" data-anchor-id="model-1-situational-factors">
<span class="header-section-number">3.3.3</span> Model 1: Situational factors</h3>
<p>Now you understand the data a little better, it is time to apply our modelling techniques to address our research question. We will go with the hierarchical approach to entering predictors to enter them in two steps. First, situational factors, then the individual factors on top of them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>individual_model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(BehIntTot <span class="sc">~</span> QWE <span class="sc">+</span> MI <span class="sc">+</span> PI, </span>
<span id="cb18-2"><a href="#cb18-2"></a>                        <span class="at">data =</span> evans_data)</span>
<span id="cb18-3"><a href="#cb18-3"></a></span>
<span id="cb18-4"><a href="#cb18-4"></a><span class="fu">summary</span>(individual_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BehIntTot ~ QWE + MI + PI, data = evans_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.5855 -2.5855 -0.5956  2.9452 10.3357 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  10.5855     0.1628  65.018  &lt; 2e-16 ***
QWEhigh      -0.3905     0.1629  -2.397  0.01663 *  
MIethical    -0.5307     0.1630  -3.256  0.00115 ** 
PIethical    -0.4592     0.1630  -2.817  0.00488 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.837 on 2214 degrees of freedom
Multiple R-squared:  0.01068,   Adjusted R-squared:  0.009341 
F-statistic: 7.968 on 3 and 2214 DF,  p-value: 2.774e-05</code></pre>
</div>
</div>
<p>All three predictors are statistically significant and are all negative. Since we coded the positive manipulations as the target groups, this shows people reported lower unethical workplace behaviour intentions in the high/ethical groups.</p>
<p>We explain a significant amount of variance in unethical behaviour intentions, but note the <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span> values. They are approximately .01 or 1%, showing with 2000 plus participants, we can reject the null, but we explain only a modest proportion of variance.</p>
<p>At this point, it is an important lesson to see how the presence of other predictors affects the estimates of another predictor. For a demonstration, we will create another regression model, but only including one situational variable at a time. Feel free to create the other two yourself and compare.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a>individual_model1a <span class="ot">&lt;-</span> <span class="fu">lm</span>(BehIntTot <span class="sc">~</span> QWE, </span>
<span id="cb20-2"><a href="#cb20-2"></a>                         <span class="at">data =</span> evans_data)</span>
<span id="cb20-3"><a href="#cb20-3"></a></span>
<span id="cb20-4"><a href="#cb20-4"></a><span class="fu">summary</span>(individual_model1a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BehIntTot ~ QWE, data = evans_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.0938 -2.0938 -0.7052  2.9062 10.2948 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  10.0938     0.1151  87.685   &lt;2e-16 ***
QWEhigh      -0.3886     0.1635  -2.377   0.0176 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.851 on 2216 degrees of freedom
Multiple R-squared:  0.002542,  Adjusted R-squared:  0.002092 
F-statistic: 5.648 on 1 and 2216 DF,  p-value: 0.01756</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you compare the coefficient for QWE in model 1 to this new isolated model, we get slightly different estimates. Its close, but not exactly the same. That is because in a multiple linear regression model, the predictors become partial effects. We are trying to model different sources of variance, so what might be explained by a predictor in one model, might change in a model with additional predictors. So, you might find predictors that are statistically significant in one model are no longer significant in another model.</p>
</div>
</div>
</section><section id="model-2-situational-and-individual-factors" class="level3" data-number="3.3.4"><h3 data-number="3.3.4" class="anchored" data-anchor-id="model-2-situational-and-individual-factors">
<span class="header-section-number">3.3.4</span> Model 2: Situational and individual factors</h3>
<p>Now we have explored the effect of situational factors on unethical behaviour intentions, we can add the individual factors to see how well they contribute to the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>individual_model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(BehIntTot <span class="sc">~</span> QWE <span class="sc">+</span> MI <span class="sc">+</span> PI <span class="sc">+</span> LOCTot <span class="sc">+</span> SocDesTot <span class="sc">+</span> MachTot, </span>
<span id="cb22-2"><a href="#cb22-2"></a>                        <span class="at">data =</span> evans_data)</span>
<span id="cb22-3"><a href="#cb22-3"></a></span>
<span id="cb22-4"><a href="#cb22-4"></a><span class="fu">summary</span>(individual_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BehIntTot ~ QWE + MI + PI + LOCTot + SocDesTot + 
    MachTot, data = evans_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.0856 -2.7105 -0.4456  2.8414 11.8721 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  7.61519    1.00062   7.610 4.02e-14 ***
QWEhigh     -0.41735    0.15513  -2.690  0.00719 ** 
MIethical   -0.47421    0.15532  -3.053  0.00229 ** 
PIethical   -0.39941    0.15526  -2.572  0.01016 *  
LOCTot       0.02330    0.01687   1.381  0.16744    
SocDesTot   -0.08860    0.01984  -4.467 8.35e-06 ***
MachTot      0.18967    0.01773  10.697  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.652 on 2211 degrees of freedom
Multiple R-squared:  0.1049,    Adjusted R-squared:  0.1025 
F-statistic: 43.19 on 6 and 2211 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>With three more variables, we explain a larger proportion of variance. Before, adjusted <span class="math inline">\(R^2\)</span> was around 1%, now it is .10 or 10%. So adding these situational variables seem to explain a larger chunk of variance. All the predictors apart from locus of control are statistically significant. Almost all the significant predictors are negative, suggesting lower unethical behaviour intention, apart from Machiavellianism. This makes sense as it means higher in a personality trait for unempathic behaviour is associated with higher intention for unethical behaviour.</p>
<section id="standardised-coefficients" class="level4" data-number="3.3.4.1"><h4 data-number="3.3.4.1" class="anchored" data-anchor-id="standardised-coefficients">
<span class="header-section-number">3.3.4.1</span> Standardised coefficients</h4>
<p>At this point with a mix of predictors, we can also check the standardised coefficients to see which predictors appear to be the strongest on a standard deviation scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="fu">standardize_parameters</span>(individual_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Std_Coefficient</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.1659965</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.0871282</td>
<td style="text-align: right;">0.2448649</td>
</tr>
<tr class="even">
<td style="text-align: left;">QWEhigh</td>
<td style="text-align: right;">-0.1082689</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.1871863</td>
<td style="text-align: right;">-0.0293515</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MIethical</td>
<td style="text-align: right;">-0.1230192</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.2020337</td>
<td style="text-align: right;">-0.0440047</td>
</tr>
<tr class="even">
<td style="text-align: left;">PIethical</td>
<td style="text-align: right;">-0.1036139</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.1826004</td>
<td style="text-align: right;">-0.0246273</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LOCTot</td>
<td style="text-align: right;">0.0296680</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.0124626</td>
<td style="text-align: right;">0.0717985</td>
</tr>
<tr class="even">
<td style="text-align: left;">SocDesTot</td>
<td style="text-align: right;">-0.0989384</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.1423766</td>
<td style="text-align: right;">-0.0555001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MachTot</td>
<td style="text-align: right;">0.2421870</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.1977892</td>
<td style="text-align: right;">0.2865848</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Machiavellianism seems to be the strongest predictor here, showing for every 1 standard deviation increase in Machiavellianism, we expect unethical behaviour intentions to increase by 0.24 standard deviations.</p>
</section><section id="checking-assumptions" class="level4" data-number="3.3.4.2"><h4 data-number="3.3.4.2" class="anchored" data-anchor-id="checking-assumptions">
<span class="header-section-number">3.3.4.2</span> Checking assumptions</h4>
<p>At this point, we can check whether there are any red flags by checking the assumption plots. Remember, in multiple linear regression, we want:</p>
<ul>
<li><p>The outcome is interval/ratio level data.</p></li>
<li><p>The predictor variables are interval/ratio or categorical (with two levels at a time).</p></li>
<li><p>All values of the outcome variable are independent (i.e., each score should come from a different participant/observation).</p></li>
<li><p>The predictors have non-zero variance.</p></li>
<li><p>The relationship between the outcome and predictors is linear.</p></li>
<li><p>The residuals should be normally distributed.</p></li>
<li><p>There should be homoscedasticity.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="co"># Change the panel layout to 2 x 2</span></span>
<span id="cb25-2"><a href="#cb25-2"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb25-3"><a href="#cb25-3"></a></span>
<span id="cb25-4"><a href="#cb25-4"></a><span class="co"># plot the diagnostic plots</span></span>
<span id="cb25-5"><a href="#cb25-5"></a><span class="fu">plot</span>(individual_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-lm-multiple_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There do not appear to be any major red flags (apart from the outcome looks discrete which we will get onto). Plot 1 shows homoscedasticity as the residuals are roughly consistent across the x-axis. The qq plot in plot 2 is fine, just with values at the lower and upper scale moving away from the line. Combined with plots 1 and 3, there are characteristic signs that the outcome may not be truly interval. The residuals are organised into lines as remember our outcome is the sum of a Likert question, so there are only so many possible values. We will come back to this idea in chapter 5. Finally, plot 4 is not flagging any observations as high in leverage for potential outliers.</p>
<p>So far, this is the same as chapters 1 and 2. We have a new assumption to check when we have multiple predictors though. We do not want predictors to be too heavily correlated with each other, known as multicollinearity. We can check this using a function from <pkg>car</pkg> called <code>vif()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">vif</span>(individual_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      QWE        MI        PI    LOCTot SocDesTot   MachTot 
 1.000447  1.002926  1.002201  1.140099  1.211972  1.266108 </code></pre>
</div>
</div>
<p>VIF stands for variance inflation factor and a conservative estimate is values that are less than 2.5 are fine. Values above 2.5 suggest your predictors are too heavily correlated. Some people suggest less than 10 is OK, but siding with caution is normally a good approach. Here, the highest value is 1.27, so it does not look like there is anything to worry about.</p>
<p>Like Chapters 1 and 2, we can also use the <code>check_model()</code> function from <pkg>performance</pkg> to get some extra plots we do not get in the base R version</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="fu">check_model</span>(individual_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-lm-multiple_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The posterior predictive check reinforces our suspicions about the discrete looking data as the model happily predicts normal looking estimates, but the observed data have notable peaks where certain values are more common. We also get a plot for collinearity which does not suggest we have anything to worry about.</p>
</section></section><section id="model-comparison" class="level3" data-number="3.3.5"><h3 data-number="3.3.5" class="anchored" data-anchor-id="model-comparison">
<span class="header-section-number">3.3.5</span> Model comparison</h3>
<p>Now we have two competing models, we can see whether model 2 is the better fitting model and is worth adding three additional predictors in. We are trying to avoid overfitting as <span class="math inline">\(R^2\)</span> will almost always increase with more variables, but it might not be actually doing anything worthwhile.</p>
<section id="comparing-models-using-anova" class="level4" data-number="3.3.5.1"><h4 data-number="3.3.5.1" class="anchored" data-anchor-id="comparing-models-using-anova">
<span class="header-section-number">3.3.5.1</span> Comparing models using <code>anova()</code>
</h4>
<p>First, we can compare the two models using analysis of variance (ANOVA) to see whether model 2 explains significantly more variance than model 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="fu">anova</span>(individual_model1, </span>
<span id="cb29-2"><a href="#cb29-2"></a>      individual_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">Res.Df</th>
<th style="text-align: right;">RSS</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: right;">F</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2214</td>
<td style="text-align: right;">32591.48</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">2211</td>
<td style="text-align: right;">29487.44</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3104.04</td>
<td style="text-align: right;">77.5814</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>It does seem to be the case here. Careful of the rounding as the <em>p</em>-value is tiny and its rounded to 0 in the rendering of the book. The difference between the models is statistically significant, suggesting model 2 explains more variance than model 1.</p>
</section><section id="comparing-r2-for-each-model" class="level4" data-number="3.3.5.2"><h4 data-number="3.3.5.2" class="anchored" data-anchor-id="comparing-r2-for-each-model">
<span class="header-section-number">3.3.5.2</span> Comparing R2 for each model</h4>
<p>Second, we can compare <span class="math inline">\(R^2\)</span> for each model to see if model 2 explains more variance in our outcome than model 1. This is more of a prompt to look at your two model objects and compare the values.</p>
<p>Remember, adjusted <span class="math inline">\(R^2\)</span> is particularly useful here as it corrects for model complexity. It penalises for the number of predictors in your model, so there will be a bigger difference in <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span> when the model is unnecessarily complex. This also supports our case as adjusted <span class="math inline">\(R^2\)</span> increases from approximately .01 to .10.</p>
</section><section id="checking-model-fit-using-aic" class="level4" data-number="3.3.5.3"><h4 data-number="3.3.5.3" class="anchored" data-anchor-id="checking-model-fit-using-aic">
<span class="header-section-number">3.3.5.3</span> Checking model fit using AIC</h4>
<p>Finally, we can check the Akaike Information Criterion (AIC) as a measure of model fit. It calculates prediction error in the model and it can only be interpreted as a relative value. There is not an inherent good or bad threshold, its relative to the data and models you are working with.</p>
<p>As it represents prediction error, lower AIC values mean better model fit relative to another model. If a more complicated model has a higher AIC than a less complicated model, there is potential overfitting when you have redundant predictors, so its better to retain the less complex model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="fu">AIC</span>(individual_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12265.16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="fu">AIC</span>(individual_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12049.17</code></pre>
</div>
</div>
<p>The AIC value decreases in model 2, suggesting that although we have a more complex model, the additional predictors are not redundant, there is less prediction error and we are learning something useful by including these extra predictors.</p>
</section></section></section><section id="multiple-linear-regression-with-interactions" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="multiple-linear-regression-with-interactions">
<span class="header-section-number">3.4</span> Multiple linear regression with interactions</h2>
<p>Finally, we will explore how you can express different types of interactions in multiple linear regression models.</p>
<section id="coding-schemes-for-interactions" class="level3" data-number="3.4.1"><h3 data-number="3.4.1" class="anchored" data-anchor-id="coding-schemes-for-interactions">
<span class="header-section-number">3.4.1</span> Coding schemes for interactions</h3>
<p>At the start of this chapter and previously in Chapter 1, we explored different coding schemes for predictors. For continuous predictors, we can enter variables as raw or centered values. For categorical predictors, we can enter variables as dummy or deviation coded values.</p>
<p>When you have multiple linear regression models, changing the coding scheme does little else but helps you interpret the intercept. However, once you start adding interaction terms, it is <em>super</em> important to know the difference between what the coefficients mean when you center the predictors or not.</p>
<p>In preparation for later, lets deviation code the categorical variables and center the continuous variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a>evans_data <span class="ot">&lt;-</span> evans_data <span class="sc">%&gt;%</span> </span>
<span id="cb34-2"><a href="#cb34-2"></a>  <span class="co"># Start by deviation coding the categorical variables as 0.5 and -0.5</span></span>
<span id="cb34-3"><a href="#cb34-3"></a>  <span class="fu">mutate</span>(<span class="at">QWE_deviation =</span> <span class="fu">case_when</span>(QWE <span class="sc">==</span> <span class="st">"high"</span> <span class="sc">~</span> <span class="fl">0.5</span>, </span>
<span id="cb34-4"><a href="#cb34-4"></a>                                   <span class="at">.default =</span> <span class="sc">-</span><span class="fl">0.5</span>),</span>
<span id="cb34-5"><a href="#cb34-5"></a>         <span class="at">MI_deviation =</span> <span class="fu">case_when</span>(MI <span class="sc">==</span> <span class="st">"ethical"</span> <span class="sc">~</span> <span class="fl">0.5</span>, </span>
<span id="cb34-6"><a href="#cb34-6"></a>                                  <span class="at">.default =</span> <span class="sc">-</span><span class="fl">0.5</span>),</span>
<span id="cb34-7"><a href="#cb34-7"></a>         <span class="at">PI_deviation =</span> <span class="fu">case_when</span>(PI <span class="sc">==</span> <span class="st">"ethical"</span> <span class="sc">~</span> <span class="fl">0.5</span>, </span>
<span id="cb34-8"><a href="#cb34-8"></a>                                  <span class="at">.default =</span> <span class="sc">-</span><span class="fl">0.5</span>),</span>
<span id="cb34-9"><a href="#cb34-9"></a>         <span class="co"># Then center the continuous predictors by subtracting the mean</span></span>
<span id="cb34-10"><a href="#cb34-10"></a>         <span class="at">LOCTot_center =</span> LOCTot <span class="sc">-</span> <span class="fu">mean</span>(LOCTot),</span>
<span id="cb34-11"><a href="#cb34-11"></a>         <span class="at">SocDesTot_center =</span> SocDesTot <span class="sc">-</span> <span class="fu">mean</span>(SocDesTot),</span>
<span id="cb34-12"><a href="#cb34-12"></a>         <span class="at">MachTot_center =</span> MachTot <span class="sc">-</span> <span class="fu">mean</span>(MachTot))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="categorical-by-categorical-interactions" class="level3" data-number="3.4.2"><h3 data-number="3.4.2" class="anchored" data-anchor-id="categorical-by-categorical-interactions">
<span class="header-section-number">3.4.2</span> Categorical by categorical interactions</h3>
<p>We will demonstrate these principles by focusing on two predictors at a time, but note these concepts just extend everything you learnt so far. You could have just two interacting predictors, or you could have a mix of individual and interacting predictors.</p>
<p>First, we will explore categorical by categorical interactions. This looks at the moderating effect of one predictor on the difference in the outcome between levels of another predictor.</p>
<section id="dummy-coded-predictors" class="level4" data-number="3.4.2.1"><h4 data-number="3.4.2.1" class="anchored" data-anchor-id="dummy-coded-predictors">
<span class="header-section-number">3.4.2.1</span> Dummy coded predictors</h4>
<p>For a starting point, let’s look at what the model looks like for our original dummy coded predictors. Previously, we separated predictors with +, but to get the interaction between predictors, we use * instead.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a>interaction_model1_dummy <span class="ot">&lt;-</span> <span class="fu">lm</span>(BehIntTot <span class="sc">~</span> MI <span class="sc">*</span> PI, </span>
<span id="cb35-2"><a href="#cb35-2"></a>                               <span class="at">data =</span> evans_data)</span>
<span id="cb35-3"><a href="#cb35-3"></a></span>
<span id="cb35-4"><a href="#cb35-4"></a><span class="fu">summary</span>(interaction_model1_dummy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BehIntTot ~ MI * PI, data = evans_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.4693 -2.4693 -0.4841  3.1418 10.2177 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          10.4693     0.1632  64.156  &lt; 2e-16 ***
MIethical            -0.6870     0.2297  -2.992  0.00281 ** 
PIethical            -0.6112     0.2298  -2.660  0.00787 ** 
MIethical:PIethical   0.3130     0.3263   0.959  0.33759    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.841 on 2214 degrees of freedom
Multiple R-squared:  0.008527,  Adjusted R-squared:  0.007184 
F-statistic: 6.347 on 3 and 2214 DF,  p-value: 0.0002781</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>There are different symbols you can use for model formulas. Using * is shorthand for “give me the individual and interaction effects of these variables”. You could also specify it fully by using <code>predictor1 + predictor 2 + predictor1:predictor2</code>. You can find a full list of formula syntax in places like this <a href="https://www.econometrics.blog/post/the-r-formula-cheatsheet/">Econometrics blog</a> {target=“_blank”}.</p>
</div>
</div>
<p>Manager influence and peer influence are both significant, but the interaction between them is not statistically significant.</p>
</section><section id="deviation-coded-predictors" class="level4" data-number="3.4.2.2"><h4 data-number="3.4.2.2" class="anchored" data-anchor-id="deviation-coded-predictors">
<span class="header-section-number">3.4.2.2</span> Deviation coded predictors</h4>
<p>Compare that to the same model, but using the deviation coded predictors instead. Look at the coefficients for the individual predictors and the interaction. Which are different and which are the same between the models?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a>interaction_model1_deviation <span class="ot">&lt;-</span> <span class="fu">lm</span>(BehIntTot <span class="sc">~</span> MI_deviation <span class="sc">*</span> PI_deviation, </span>
<span id="cb37-2"><a href="#cb37-2"></a>                                   <span class="at">data =</span> evans_data)</span>
<span id="cb37-3"><a href="#cb37-3"></a></span>
<span id="cb37-4"><a href="#cb37-4"></a><span class="fu">summary</span>(interaction_model1_deviation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BehIntTot ~ MI_deviation * PI_deviation, data = evans_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.4693 -2.4693 -0.4841  3.1418 10.2177 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                9.89847    0.08158 121.341  &lt; 2e-16 ***
MI_deviation              -0.53053    0.16315  -3.252  0.00116 ** 
PI_deviation              -0.45467    0.16315  -2.787  0.00537 ** 
MI_deviation:PI_deviation  0.31297    0.32630   0.959  0.33759    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.841 on 2214 degrees of freedom
Multiple R-squared:  0.008527,  Adjusted R-squared:  0.007184 
F-statistic: 6.347 on 3 and 2214 DF,  p-value: 0.0002781</code></pre>
</div>
</div>
<p>You will see that the model fit and coefficient for the interaction is identical, but the individual predictor coefficients changed. This happens because of the interpretation of the intercept and coefficient in dummy coding. When you dummy code these variables, the intercept is the value for the outcome when both manager influence is unethical and peer influence is unethical. The coefficient for manager influence is then how we expect the outcome to change for ethical managers, when there is an unethical peer influence. These are <strong>simple effects</strong>, which can be useful information, but it might not be what you are expecting.</p>
<p>In the deviation model, this turns into something more familiar to those working with ANOVA to compare categorical variables. The intercept is the grand mean now, so the individual predictors become <strong>main effects</strong>, or the effect of one predictor, when the second predictor is held constant at 0. For instance, an ethical manager decreases the unethical behaviour intention by 1.06 (2 * -0.53 because of the -0.5/0.5 deviation coding scheme) compared to the grand mean.</p>
<p>Both approaches provide useful information, but think about what information you are looking for. Typically, main effects are more useful when you want to know the individual effect of predictors on the outcome. Simple effects are then normally more useful when you are trying to break down each element of an interaction and you want the conditional effect of one predictor on another.</p>
<p>Its always about your research question and what information you want to know.</p>
</section><section id="plotting-interactions" class="level4" data-number="3.4.2.3"><h4 data-number="3.4.2.3" class="anchored" data-anchor-id="plotting-interactions">
<span class="header-section-number">3.4.2.3</span> Plotting interactions</h4>
<p>In these examples, the data set is great for a large sample of different variables, but there are not really any meaningful interactions to explore. But, we can still demonstrate what you would do if there <em>was</em> an interaction to explore.</p>
<p>First, plotting is your friend. Sometimes you can plot your design fine using <pkg>ggplot2</pkg>, but you often miss out on the inferential parts for the confidence intervals around estimates, particularly when there are interactions to explore. So, the <pkg>sjPlot</pkg> package can be useful as it can take regression models and plot the model predictions. To decompose an interaction, it is normally more useful to use the original / dummy-coded variables, as we are interested in the simple effects here, and the units will be more interpretable for the average reader.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="co"># sjPlot makes it easy to plot estimates from the model</span></span>
<span id="cb39-2"><a href="#cb39-2"></a><span class="fu">plot_model</span>(interaction_model1_dummy, <span class="co"># You enter the model object</span></span>
<span id="cb39-3"><a href="#cb39-3"></a>           <span class="at">type =</span> <span class="st">"pred"</span>, <span class="co"># The type of plot you want to create</span></span>
<span id="cb39-4"><a href="#cb39-4"></a>           <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"MI"</span>, <span class="st">"PI"</span>)) <span class="co"># The predictors you want to plot </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-lm-multiple_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It is up to you and your research question which way you plot the interaction. You can explore the moderating effect of predictor 1 on predictor 2, or the moderating effect of predictor 2 on predictor 1. You will need to consider which addresses your research question. For example, we can flip it around:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a><span class="co"># sjPlot makes it easy to plot estimates from the model</span></span>
<span id="cb40-2"><a href="#cb40-2"></a><span class="fu">plot_model</span>(interaction_model1_dummy, <span class="co"># You enter the model object</span></span>
<span id="cb40-3"><a href="#cb40-3"></a>           <span class="at">type =</span> <span class="st">"pred"</span>, <span class="co"># The type of plot you want to create</span></span>
<span id="cb40-4"><a href="#cb40-4"></a>           <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"PI"</span>, <span class="st">"MI"</span>)) <span class="co"># The predictors you want to plot </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-lm-multiple_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><pkg>sjPlot</pkg> is built on <pkg>ggplot2</pkg>, so the output may not be publication quality immediately, but you can edit some elements like a regular <pkg>ggplot2</pkg> object. Annoyingly, its not easy to edit the x-axis and legend labels, so its normally better to edit the underlying variable name and labels instead.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a><span class="fu">plot_model</span>(interaction_model1_dummy,</span>
<span id="cb41-2"><a href="#cb41-2"></a>           <span class="at">type =</span> <span class="st">"pred"</span>, </span>
<span id="cb41-3"><a href="#cb41-3"></a>           <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"MI"</span>, <span class="st">"PI"</span>)) <span class="sc">+</span> </span>
<span id="cb41-4"><a href="#cb41-4"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">8</span>, <span class="dv">14</span>, <span class="dv">2</span>), </span>
<span id="cb41-5"><a href="#cb41-5"></a>                     <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">14</span>), </span>
<span id="cb41-6"><a href="#cb41-6"></a>                     <span class="at">name =</span> <span class="st">"Unethical Workplace Behaviour Intention"</span>) <span class="sc">+</span> </span>
<span id="cb41-7"><a href="#cb41-7"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span> </span>
<span id="cb41-8"><a href="#cb41-8"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Scale for y is already present.
Adding another scale for y, which will replace the existing scale.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-lm-multiple_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="breaking-down-model-estimates" class="level4" data-number="3.4.2.4"><h4 data-number="3.4.2.4" class="anchored" data-anchor-id="breaking-down-model-estimates">
<span class="header-section-number">3.4.2.4</span> Breaking down model estimates</h4>
<p>Another way of breaking down interactions is by reporting the estimated marginal means. When there is an interaction, you often want to known whether the mean difference in predictor 1 is different across the levels of predictor 2. Plotting shows you this visually, but you might want to report effect sizes in your write-up.</p>
<p>The <pkg>emmeans</pkg> package can take a model object and report the estimated marginal means providing you tell it which variables you want to break it down by. Remember, you can switch the order of the variables depending on which predictor you want as the moderator.</p>
<p>For example, we can report the estimated marginal means and their confidence intervals of all four groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a><span class="fu">emmeans</span>(interaction_model1_dummy, <span class="co"># model object</span></span>
<span id="cb43-2"><a href="#cb43-2"></a>        <span class="sc">~</span> MI <span class="sc">|</span> PI) <span class="co"># which order you want predictors</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>PI = unethical:
 MI        emmean    SE   df lower.CL upper.CL
 unethical  10.47 0.163 2214    10.15    10.79
 ethical     9.78 0.162 2214     9.47    10.10

PI = ethical:
 MI        emmean    SE   df lower.CL upper.CL
 unethical   9.86 0.162 2214     9.54    10.18
 ethical     9.48 0.166 2214     9.16     9.81

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>We can also report the mean difference moderated by the second predictor by wrapping it in the <code>contrast()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a><span class="fu">contrast</span>(<span class="fu">emmeans</span>(interaction_model1_dummy, </span>
<span id="cb45-2"><a href="#cb45-2"></a>                 <span class="sc">~</span> MI <span class="sc">|</span> PI))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>PI = unethical:
 contrast         estimate    SE   df t.ratio p.value
 unethical effect    0.344 0.115 2214   2.992  0.0028
 ethical effect     -0.344 0.115 2214  -2.992  0.0028

PI = ethical:
 contrast         estimate    SE   df t.ratio p.value
 unethical effect    0.187 0.116 2214   1.614  0.1067
 ethical effect     -0.187 0.116 2214  -1.614  0.1067

P value adjustment: fdr method for 2 tests </code></pre>
</div>
</div>
<p>Note you get all combinations of these comparisons, so when you have two levels in a predictor, you get the same contrast but flipped around for each level of the moderator.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>One final warning, you can look at these variables in many ways, but think about your plan and what will address your research question and hypothesis.</p>
</div>
</div>
</section></section><section id="continuous-by-categorical-interactions" class="level3" data-number="3.4.3"><h3 data-number="3.4.3" class="anchored" data-anchor-id="continuous-by-categorical-interactions">
<span class="header-section-number">3.4.3</span> Continuous by categorical interactions</h3>
<p>Second, we have categorical by continuous interactions. This is where you have one categorical predictor and one continuous predictor. It tells you whether the relationship between your continuous predictor and your outcome is moderated by your categorical predictor.</p>
<p>For this model, we will focus on whether workplace quality (<code>QWE_deviation</code>) moderates the relationship between Machiavellianism (<code>MachTot_center</code>) and unethical behaviour intentions (<code>BehIntTot</code>). Now you know the difference between raw and centered predictors, make sure you use the centered variables to interpret the individual predictors as main effects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1"></a>interaction_model2_deviation <span class="ot">&lt;-</span> <span class="fu">lm</span>(BehIntTot <span class="sc">~</span> QWE_deviation <span class="sc">*</span> MachTot_center, </span>
<span id="cb47-2"><a href="#cb47-2"></a>                                   <span class="at">data =</span> evans_data)</span>
<span id="cb47-3"><a href="#cb47-3"></a></span>
<span id="cb47-4"><a href="#cb47-4"></a><span class="fu">summary</span>(interaction_model2_deviation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BehIntTot ~ QWE_deviation * MachTot_center, data = evans_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.0748 -2.7977 -0.5381  2.9165 11.5690 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                   9.90061    0.07817 126.647  &lt; 2e-16 ***
QWE_deviation                -0.41162    0.15635  -2.633  0.00853 ** 
MachTot_center                0.22810    0.01591  14.341  &lt; 2e-16 ***
QWE_deviation:MachTot_center -0.04788    0.03181  -1.505  0.13246    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.681 on 2214 degrees of freedom
Multiple R-squared:  0.0892,    Adjusted R-squared:  0.08796 
F-statistic: 72.28 on 3 and 2214 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>There is no interaction again, but if we did want to explore it, we can plot the simple effects by creating a dummy-coded model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1"></a>interaction_model2_dummy <span class="ot">&lt;-</span> <span class="fu">lm</span>(BehIntTot <span class="sc">~</span> QWE <span class="sc">*</span> MachTot, </span>
<span id="cb49-2"><a href="#cb49-2"></a>                               <span class="at">data =</span> evans_data)</span>
<span id="cb49-3"><a href="#cb49-3"></a></span>
<span id="cb49-4"><a href="#cb49-4"></a><span class="fu">plot_model</span>(interaction_model2_dummy, </span>
<span id="cb49-5"><a href="#cb49-5"></a>           <span class="at">type =</span> <span class="st">"pred"</span>, </span>
<span id="cb49-6"><a href="#cb49-6"></a>           <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"MachTot"</span>, <span class="st">"QWE"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-lm-multiple_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In a continuous by categorical interaction, it will tell you whether the slope between your outcome and continuous predictor is different/moderated by the levels of your categorical predictor. For example, whether the relationship flips from positive to negative, one is very weak, or the gradient of the slopes are just different. Here, we can see the relationship is slightly weaker in high quality workplaces compared to low quality, but ultimately that difference is not statistically significant as shown by the interaction term in the model.</p>
</section><section id="continuous-by-continuous-interactions" class="level3" data-number="3.4.4"><h3 data-number="3.4.4" class="anchored" data-anchor-id="continuous-by-continuous-interactions">
<span class="header-section-number">3.4.4</span> Continuous by continuous interactions</h3>
<p>Finally, we have continuous by continuous interactions. This is where you have two continuous predictors. It tells you whether the relationship between your first continuous predictor and your outcome is moderated by your second continuous predictor.</p>
<p>For this model, we will focus on whether locus of control (<code>LOCTot_center</code>) moderates the relationship between Machiavellianism (<code>MachTot_center</code>) and unethical behaviour intentions (<code>BehIntTot</code>). Make sure you use the centered variables to interpret the individual predictors as main effects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a>interaction_model3_deviation <span class="ot">&lt;-</span> <span class="fu">lm</span>(BehIntTot <span class="sc">~</span> LOCTot_center <span class="sc">*</span> MachTot_center, </span>
<span id="cb50-2"><a href="#cb50-2"></a>                                   <span class="at">data =</span> evans_data)</span>
<span id="cb50-3"><a href="#cb50-3"></a></span>
<span id="cb50-4"><a href="#cb50-4"></a><span class="fu">summary</span>(interaction_model3_deviation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BehIntTot ~ LOCTot_center * MachTot_center, data = evans_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.0970 -2.7347 -0.5072  2.8787 12.0243 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                   9.9073451  0.0810659 122.213   &lt;2e-16 ***
LOCTot_center                 0.0357878  0.0168673   2.122    0.034 *  
MachTot_center                0.2172115  0.0168029  12.927   &lt;2e-16 ***
LOCTot_center:MachTot_center -0.0007797  0.0027161  -0.287    0.774    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.685 on 2214 degrees of freedom
Multiple R-squared:  0.08733,   Adjusted R-squared:  0.0861 
F-statistic: 70.62 on 3 and 2214 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Plotting is always helpful for interpreting interactions, but it is <em>crucial</em> for continuous by continuous interactions.</p>
<p>The interpretation relies on simple slopes analysis. As there are not discrete values of your moderator, simple slopes works by creating discrete values from your continuous predictor. Typically, this is 1 standard deviation below the mean, the mean, and 1 standard deviation above the mean. This tells you as you increase levels of your moderator, how does it affect the relationship between your first predictor and the outcome?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a>interaction_model3_dummy <span class="ot">&lt;-</span> <span class="fu">lm</span>(BehIntTot <span class="sc">~</span> LOCTot <span class="sc">*</span> MachTot, </span>
<span id="cb52-2"><a href="#cb52-2"></a>                               <span class="at">data =</span> evans_data)</span>
<span id="cb52-3"><a href="#cb52-3"></a></span>
<span id="cb52-4"><a href="#cb52-4"></a><span class="fu">plot_model</span>(interaction_model3_dummy, </span>
<span id="cb52-5"><a href="#cb52-5"></a>           <span class="at">type =</span> <span class="st">"pred"</span>, </span>
<span id="cb52-6"><a href="#cb52-6"></a>           <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"MachTot"</span>, <span class="st">"LOCTot"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-lm-multiple_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In a simple slopes analysis, it will tell you whether the slope between your outcome and continuous predictor is different/moderated by the fixed points of your second predictor. For example, whether the relationship flips from positive to negative, one is very weak, or the gradient of the slopes are just different. Here, the interaction was non-significant, and there is very little difference between the three lines, they are almost exactly parallel to each other.</p>
</section></section><section id="test-yourself" class="level2" data-number="3.5"><h2 data-number="3.5" class="anchored" data-anchor-id="test-yourself">
<span class="header-section-number">3.5</span> Test Yourself</h2>
<p>Now you have followed along to a guided example, it is important you can transfer your knowledge to a new scenario. So, we have a new data set for you to try out your understanding of these techniques on. Follow the instructions below and answer the questions. The solution is there to check your answers against, but make sure you try the activities independently first.</p>
<section id="introduction-to-the-dataset-2" class="level3" data-number="3.5.1"><h3 data-number="3.5.1" class="anchored" data-anchor-id="introduction-to-the-dataset-2">
<span class="header-section-number">3.5.1</span> Introduction to the dataset</h3>
<p>We will use data from Tulloch et al.&nbsp;who performed an unpublished replication of <span class="citation" data-cites="troy_change_2017">Troy et al. (<a href="references.html#ref-troy_change_2017" role="doc-biblioref">2017</a>)</span>. Troy et al.&nbsp;conducted three studies exploring the effect of emotion regulation and socioeconomic status on depressive symptoms. The data you will use comes from a dissertation project where the team replicated study one to investigate if socioeconomic status moderates the link between cognitive reappraisal ability and depressive symptoms. For the purposes of this task, the key variables from the study included:</p>
<ul>
<li><p>Socioeconomic Status (SES; <code>SES</code>) - Current annual family income was rated on a 1 to 12 scale aligning with income bands. The bands were converted from the original study’s values in US dollars, to the replication study’s target population of UK (in British Pounds) and Malaysia (in Malaysian Ringgit). Its an odd way of recording this data, but go with it…</p></li>
<li><p>Country (<code>Country</code>) - Categorical variable showing whether the participant completed the study in Malaysia or the UK.</p></li>
<li><p>Cognitive Reappraisal Ability (CRA; <code>CRA_mean</code>) - A scale measuring cognitive reappraisal ability. The variable was calculated from the mean of eight items measured on a 1 (strongly disagree) - 7 (strongly agree) scale, with higher values meaning higher cognitive reappraisal ability.</p></li>
<li><p>Depressive Symptoms (<code>DS_sum</code>) - This was measured as current non-clinical symptoms of depression from the Center for Epidemiological Studies Depression Scale. Participants reported the presence of depression symptoms in the past week across five items on a 0 (none of the time) to 3 (all of the time) scale. The variable was calculated from the sum of the five items, meaning the scale could range from 0 to 15, with higher values meaning greater depression symptoms in the past week.</p></li>
<li><p>Life Stress (<code>LS_mean</code>) - This was measured as perceptions of life stress in the past two years. Participants completed four questions on a 1 (never) to 5 (very often) scale. The variable was calculated from the mean of four questions, with higher values meaning greater life stress in the past two years.</p></li>
</ul>
<p>In the original Troy et al.&nbsp;study, they investigated if socioeconomic status moderates the link between cognitive reappraisal ability and depressive symptoms. In study one, they applied a multiple regression model with depressive symptoms as the outcome, life stress as an individual predictor, and an interaction between cognitive reappraisal ability and socioeconomic status. They found that:</p>
<ul>
<li><p>Life stress was a significant positive predictor of depressive symptoms.</p></li>
<li><p>Cognitive reappraisal was a significant negative predictor of depressive symptoms.</p></li>
<li><p>There was a significant interaction between cognitive reappraisal and socioeconomic status. They found that there was a stronger negative relationship between cognitive reappraisal and depressive symptoms for lower values of socioeconomic status compared to higher values (i.e., simple slopes analysis).</p></li>
</ul>
<p>In the replication study, the team wanted to replicate the study to see if they would observe similar findings by including two different countries of origin (Malaysia and UK) compared to the original sample from the United States. The research questions were:</p>
<ol type="1">
<li><p>Does country of origin, life stress, cognitive reappraisal ability, and socioeconomic status predict depressive symptoms?</p></li>
<li><p>Does socioeconomic status moderate the relationship between cognitive reappraisal ability and depressive symptoms?</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1"></a><span class="co"># Load data for coding schemes</span></span>
<span id="cb53-2"><a href="#cb53-2"></a><span class="co"># We are applying the coding scheme, just so its crystal clear whether your answers align</span></span>
<span id="cb53-3"><a href="#cb53-3"></a>tulloch_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Tulloch_2022.csv"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb53-4"><a href="#cb53-4"></a>  <span class="fu">mutate</span>(<span class="at">Country =</span> <span class="fu">factor</span>(Country, </span>
<span id="cb53-5"><a href="#cb53-5"></a>                          <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Malaysia"</span>, <span class="st">"UK"</span>)),</span>
<span id="cb53-6"><a href="#cb53-6"></a>         <span class="at">Country_deviation =</span> <span class="fu">case_when</span>(Country <span class="sc">==</span> <span class="st">"UK"</span> <span class="sc">~</span> <span class="fl">0.5</span>, </span>
<span id="cb53-7"><a href="#cb53-7"></a>                                       <span class="at">.default =</span> <span class="sc">-</span><span class="fl">0.5</span>),</span>
<span id="cb53-8"><a href="#cb53-8"></a>         <span class="at">SES_center =</span> SES <span class="sc">-</span> <span class="fu">mean</span>(SES), </span>
<span id="cb53-9"><a href="#cb53-9"></a>         <span class="at">CRA_center =</span> CRA_mean <span class="sc">-</span> <span class="fu">mean</span>(CRA_mean),</span>
<span id="cb53-10"><a href="#cb53-10"></a>         <span class="at">LS_center =</span> LS_mean <span class="sc">-</span> <span class="fu">mean</span>(LS_mean))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try this
</div>
</div>
<div class="callout-body-container callout-body">
<p>Fit two models:</p>
<ol type="1">
<li><p>Predict depressive symptoms (<code>DS_sum</code>) from country of origin (<code>Country_deviation</code>), life stress (<code>LS_center</code>), cognitive reappraisal (<code>CRA_center</code>), and socioeconomic status (<code>SES_center</code>) as individual predictors.</p></li>
<li><p>Predict depressive symptoms (<code>DS_sum</code>) from country of origin (<code>Country_deviation</code>), life stress (<code>LS_center</code>), and the interaction between cognitive reappraisal (<code>CRA_center</code>) and socioeconomic status (<code>SES_center</code>).</p></li>
</ol>
<p>From here, apply what you learnt in the guided examples above to this new independent task and complete the questions below to check your understanding.</p>
</div>
</div>
</section><section id="model-1-individual-predictors" class="level3" data-number="3.5.2"><h3 data-number="3.5.2" class="anchored" data-anchor-id="model-1-individual-predictors">
<span class="header-section-number">3.5.2</span> Model 1: Individual predictors</h3>
<ul>
<li><p>Rounding to three decimals, adjusted <span class="math inline">\(R^2\)</span> for the model is <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer="[&quot;0.239&quot;,&quot;.239&quot;]">, meaning the predictors explain <input class="webex-solveme nospaces" data-tol="0.001" size="2" data-answer="[&quot;24&quot;]">% of the variance in our outcome of depressive symptoms.</p></li>
<li><p>Rounding to two decimals, the slope for <code>Country_deviation</code> is <input class="webex-solveme nospaces" data-tol="0.001" size="4" data-answer="[&quot;1.33&quot;]">, suggesting depressive symptoms were higher in <select class="webex-select"><option value="blank"></option>
<option value="answer">the UK</option>
<option value="x">Malaysia</option></select>.</p></li>
<li><p>Rounding to two decimals, the slope for <code>LS_center</code> is <input class="webex-solveme nospaces" data-tol="0.001" size="3" data-answer="[&quot;1.7&quot;]">, suggesting life stress is a <select class="webex-select"><option value="blank"></option>
<option value="answer">positive</option>
<option value="x">negative</option></select> predictor.</p></li>
<li><p>Rounding to two decimals, the slope for <code>CRA_center</code> is <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer="[&quot;-0.48&quot;,&quot;-.48&quot;]">, suggesting cognitive reappraisal is a <select class="webex-select"><option value="blank"></option>
<option value="x">positive</option>
<option value="answer">negative</option></select> predictor.</p></li>
<li><p>Rounding to two decimals, the slope for <code>SES_center</code> is <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer="[&quot;-0.21&quot;,&quot;-.21&quot;]">, suggesting socioeconomic status is a <select class="webex-select"><option value="blank"></option>
<option value="x">positive</option>
<option value="answer">negative</option></select> predictor.</p></li>
<li><p>Converting the model to standardised predictors, <select class="webex-select"><option value="blank"></option>
<option value="x">country of origin</option>
<option value="answer">life stress</option>
<option value="x">cognitive reappraisal</option>
<option value="x">socioeconomic status</option></select> has the largest effect on depressive symptoms.</p></li>
</ul>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a>tulloch_model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DS_sum <span class="sc">~</span> Country_deviation <span class="sc">+</span> LS_center <span class="sc">+</span> CRA_center <span class="sc">+</span> SES_center,</span>
<span id="cb54-2"><a href="#cb54-2"></a>                     <span class="at">data =</span> tulloch_data) </span>
<span id="cb54-3"><a href="#cb54-3"></a></span>
<span id="cb54-4"><a href="#cb54-4"></a><span class="fu">summary</span>(tulloch_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DS_sum ~ Country_deviation + LS_center + CRA_center + 
    SES_center, data = tulloch_data)

Residuals:
   Min     1Q Median     3Q    Max 
-7.301 -2.069 -0.484  2.064  8.623 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        4.57426    0.22915  19.962  &lt; 2e-16 ***
Country_deviation  1.32867    0.56926   2.334  0.02070 *  
LS_center          1.69695    0.31853   5.327 2.95e-07 ***
CRA_center        -0.48039    0.18290  -2.626  0.00937 ** 
SES_center        -0.21012    0.09833  -2.137  0.03396 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.996 on 180 degrees of freedom
Multiple R-squared:  0.2557,    Adjusted R-squared:  0.2391 
F-statistic: 15.46 on 4 and 180 DF,  p-value: 6.901e-11</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a><span class="fu">standardize_parameters</span>(tulloch_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Std_Coefficient</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.1265450</td>
<td style="text-align: right;">0.1265450</td>
</tr>
<tr class="even">
<td style="text-align: left;">Country_deviation</td>
<td style="text-align: right;">0.1890952</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.0292300</td>
<td style="text-align: right;">0.3489603</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LS_center</td>
<td style="text-align: right;">0.3628109</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.2284307</td>
<td style="text-align: right;">0.4971912</td>
</tr>
<tr class="even">
<td style="text-align: left;">CRA_center</td>
<td style="text-align: right;">-0.1769852</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.3099507</td>
<td style="text-align: right;">-0.0440197</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SES_center</td>
<td style="text-align: right;">-0.1724731</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.3317415</td>
<td style="text-align: right;">-0.0132047</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="model-2-interaction-term" class="level3" data-number="3.5.3"><h3 data-number="3.5.3" class="anchored" data-anchor-id="model-2-interaction-term">
<span class="header-section-number">3.5.3</span> Model 2: Interaction term</h3>
<ul>
<li><p>Rounding to three decimals, adjusted <span class="math inline">\(R^2\)</span> for the model is <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer="[&quot;0.235&quot;,&quot;.235&quot;]">, meaning the predictors explain <input class="webex-solveme nospaces" data-tol="0.001" size="2" data-answer="[&quot;24&quot;]">% of the variance in our outcome of depressive symptoms.</p></li>
<li><p>Rounding to two decimals, the slope for <code>Country_deviation</code> is <input class="webex-solveme nospaces" data-tol="0.001" size="4" data-answer="[&quot;1.32&quot;]">, suggesting depressive symptoms were higher in <select class="webex-select"><option value="blank"></option>
<option value="answer">the UK</option>
<option value="x">Malaysia</option></select>.</p></li>
<li><p>Rounding to two decimals, the slope for <code>LS_center</code> is <input class="webex-solveme nospaces" data-tol="0.001" size="4" data-answer="[&quot;1.69&quot;]">, suggesting life stress is a <select class="webex-select"><option value="blank"></option>
<option value="answer">positive</option>
<option value="x">negative</option></select> predictor.</p></li>
<li><p>Rounding to two decimals, the slope for <code>CRA_center</code> is<input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer="[&quot;-0.49&quot;,&quot;-.49&quot;]">, suggesting cognitive reappraisal is a <select class="webex-select"><option value="blank"></option>
<option value="x">positive</option>
<option value="answer">negative</option></select> predictor.</p></li>
<li><p>Rounding to two decimals, the slope for <code>SES_center</code> is <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer="[&quot;-0.21&quot;,&quot;-.21&quot;]">, suggesting socioeconomic status is a <select class="webex-select"><option value="blank"></option>
<option value="x">positive</option>
<option value="answer">negative</option></select> predictor.</p></li>
<li><p>Rounding to two decimals, the slope for <code>CRA_center:SES_center</code> is <input class="webex-solveme nospaces" data-tol="0.001" size="4" data-answer="[&quot;0.02&quot;,&quot;.02&quot;]">, and it is a <select class="webex-select"><option value="blank"></option>
<option value="x">significant</option>
<option value="answer">non-significant</option></select> predictor.</p></li>
</ul>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1"></a>tulloch_model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DS_sum <span class="sc">~</span> Country_deviation <span class="sc">+</span> LS_center <span class="sc">+</span> CRA_center<span class="sc">*</span>SES_center,</span>
<span id="cb57-2"><a href="#cb57-2"></a>                     <span class="at">data =</span> tulloch_data) </span>
<span id="cb57-3"><a href="#cb57-3"></a></span>
<span id="cb57-4"><a href="#cb57-4"></a><span class="fu">summary</span>(tulloch_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DS_sum ~ Country_deviation + LS_center + CRA_center * 
    SES_center, data = tulloch_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.2692 -2.0546 -0.4714  1.9568  8.6498 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            4.57570    0.22980  19.911  &lt; 2e-16 ***
Country_deviation      1.31934    0.57172   2.308  0.02216 *  
LS_center              1.69024    0.32026   5.278 3.75e-07 ***
CRA_center            -0.48954    0.18632  -2.627  0.00935 ** 
SES_center            -0.21228    0.09889  -2.147  0.03318 *  
CRA_center:SES_center  0.01761    0.06357   0.277  0.78208    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.004 on 179 degrees of freedom
Multiple R-squared:  0.256, Adjusted R-squared:  0.2352 
F-statistic: 12.32 on 5 and 179 DF,  p-value: 2.832e-10</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1"></a><span class="fu">standardize_parameters</span>(tulloch_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Std_Coefficient</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.0007205</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.1262589</td>
<td style="text-align: right;">0.1276998</td>
</tr>
<tr class="even">
<td style="text-align: left;">Country_deviation</td>
<td style="text-align: right;">0.1877666</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.0272046</td>
<td style="text-align: right;">0.3483285</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LS_center</td>
<td style="text-align: right;">0.3613759</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.2262574</td>
<td style="text-align: right;">0.4964944</td>
</tr>
<tr class="even">
<td style="text-align: left;">CRA_center</td>
<td style="text-align: right;">-0.1803568</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.3158157</td>
<td style="text-align: right;">-0.0448979</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SES_center</td>
<td style="text-align: right;">-0.1742427</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.3344240</td>
<td style="text-align: right;">-0.0140615</td>
</tr>
<tr class="even">
<td style="text-align: left;">CRA_center:SES_center</td>
<td style="text-align: right;">0.0182935</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.1120138</td>
<td style="text-align: right;">0.1486008</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="model-comparison-1" class="level3" data-number="3.5.4"><h3 data-number="3.5.4" class="anchored" data-anchor-id="model-comparison-1">
<span class="header-section-number">3.5.4</span> Model comparison</h3>
<ul>
<li><p>Comparing the two models using ANOVA, model 2 <select class="webex-select"><option value="blank"></option>
<option value="x">does</option>
<option value="answer">does not</option></select> explain significantly more variance in depressive symptoms than model 1.</p></li>
<li><p>Adjusted <span class="math inline">\(R^2\)</span> is larger in <select class="webex-select"><option value="blank"></option>
<option value="answer">model 1</option>
<option value="x">model 2</option></select>.</p></li>
<li><p>The AIC value is lower in <select class="webex-select"><option value="blank"></option>
<option value="answer">model 1</option>
<option value="x">model 2</option></select>.</p></li>
<li><p>Looking at these model comparison criteria, <select class="webex-select"><option value="blank"></option>
<option value="answer">model 1</option>
<option value="x">model 2</option></select> seems to be the most appropriate model.</p></li>
</ul>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1"></a><span class="fu">anova</span>(tulloch_model1, tulloch_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">Res.Df</th>
<th style="text-align: right;">RSS</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: right;">F</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">180</td>
<td style="text-align: right;">1616.120</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">179</td>
<td style="text-align: right;">1615.428</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.6925931</td>
<td style="text-align: right;">0.0767439</td>
<td style="text-align: right;">0.7820792</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1"></a><span class="fu">AIC</span>(tulloch_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 937.9814</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1"></a><span class="fu">AIC</span>(tulloch_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 939.9021</code></pre>
</div>
</div>
</div>
</div>
</div>
</section></section><section id="words-from-this-chapter" class="level2" data-number="3.6"><h2 data-number="3.6" class="anchored" data-anchor-id="words-from-this-chapter">
<span class="header-section-number">3.6</span> Words from this Chapter</h2>
<p>Below you will find a list of words that were used in this chapter that might be new to you in case it helps to have somewhere to refer back to what they mean. The links in this table take you to the entry for the words in the <a href="https://psyteachr.github.io/glossary/" target="_blank">PsyTeachR Glossary</a>. Note that the Glossary is written by numerous members of the team and as such may use slightly different terminology from that shown in the chapter.</p>
<div class="kable-table">

</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-evans_unethical_2024" class="csl-entry" role="listitem">
Evans, T. R. (2024). <em>Unethical <span>Behaviour</span> in the <span>Workplace</span>: <span>A</span> <span>Direct</span> and <span>Conceptual</span> <span>Replication</span> of <span>Jones</span> &amp; <span>Kavanagh</span> (1996)</em>. <a href="https://doi.org/10.31234/osf.io/a2rj9">https://doi.org/10.31234/osf.io/a2rj9</a>
</div>
<div id="ref-james_computer_2015" class="csl-entry" role="listitem">
James, E. L., Bonsall, M. B., Hoppitt, L., Tunbridge, E. M., Geddes, J. R., Milton, A. L., &amp; Holmes, E. A. (2015). Computer <span>Game</span> <span>Play</span> <span>Reduces</span> <span>Intrusive</span> <span>Memories</span> of <span>Experimental</span> <span>Trauma</span> via <span>Reconsolidation</span>-<span>Update</span> <span>Mechanisms</span>: <em>Psychological Science</em>, <em>26</em>(8), 1201–1215. <a href="https://doi.org/10.1177/0956797615583071">https://doi.org/10.1177/0956797615583071</a>
</div>
<div id="ref-jones_experimental_1996" class="csl-entry" role="listitem">
Jones, G. E., &amp; Kavanagh, M. J. (1996). An experimental examination of the effects of individual and situational factors on unethical behavioral intentions in the workplace. <em>Journal of Business Ethics</em>, <em>15</em>, 511–523.
</div>
<div id="ref-troy_change_2017" class="csl-entry" role="listitem">
Troy, A. S., Ford, B. Q., McRae, K., Zarolia, P., &amp; Mauss, I. (2017). Change the things you can: <span>Emotion</span> regulation is more beneficial for people from lower than from higher socioeconomic status. <em>Emotion</em>, <em>17</em>(1), 141–154. <a href="https://doi.org/10.1037/emo0000210">https://doi.org/10.1037/emo0000210</a>
</div>
</div>
</section></main><!-- /main --><script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script><script>
// open rdrr links externally ----

var exlinks = document.querySelectorAll("a[href^='https://rdrr.io']");
var exlink_func = function(){
  window.open(this.href);
  return false;
};
for (var i = 0; i < exlinks.length; i++) {
    exlinks[i].addEventListener('click', exlink_func, false);
}

// visible second sidebar in mobile ----

function move_sidebar() {
  var toc = document.getElementById("TOC");
  var small_sidebar = document.querySelector("#quarto-sidebar .sidebar-menu-container");
  var right_sidebar = document.getElementById("quarto-margin-sidebar");

  if (window.innerWidth < 768) {
    small_sidebar.append(toc);
  } else {
    right_sidebar.append(toc);
  }
}
move_sidebar();
window.onresize = move_sidebar;
</script><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./02-lm-categorical.html" class="pagination-link" aria-label="Regression with one categorical predictor">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression with one categorical predictor</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-screening-data.html" class="pagination-link" aria-label="Missing data, outliers, and checking assumptions">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Missing data, outliers, and checking assumptions</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>CC-BY (2025) Bartlett, Rousselet, &amp; DeBruine.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>