<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Materials for the MSc Statistics and Research Design course at the University of Glasgow.">
<title>5&nbsp; Generalised Linear Regression – Statistics and Research Design</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./04-screening-data.html" rel="prev">
<link href="./images/logos/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-6NP3MF25W3', { 'anonymize_ip': true});
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" href="include/booktem.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/glossary.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-glm.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Generalised Linear Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics and Research Design</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-lm-continuous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Regression with one continuous predictor</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-lm-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression with one categorical predictor</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-lm-multiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-screening-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Missing data, outliers, and checking assumptions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-glm.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Generalised Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#chapter-preparation" id="toc-chapter-preparation" class="nav-link active" data-scroll-target="#chapter-preparation"><span class="header-section-number">5.1</span> Chapter preparation</a>
  <ul class="collapse">
<li><a href="#organising-your-files-and-project-for-the-chapter" id="toc-organising-your-files-and-project-for-the-chapter" class="nav-link" data-scroll-target="#organising-your-files-and-project-for-the-chapter"><span class="header-section-number">5.1.1</span> Organising your files and project for the chapter</a></li>
  </ul>
</li>
  <li>
<a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression"><span class="header-section-number">5.2</span> Logistic Regression</a>
  <ul class="collapse">
<li><a href="#introduction-to-the-dataset" id="toc-introduction-to-the-dataset" class="nav-link" data-scroll-target="#introduction-to-the-dataset"><span class="header-section-number">5.2.1</span> Introduction to the dataset</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">5.2.2</span> Exploratory data analysis</a></li>
  <li><a href="#would-linear-regression-work" id="toc-would-linear-regression-work" class="nav-link" data-scroll-target="#would-linear-regression-work"><span class="header-section-number">5.2.3</span> Would linear regression work?</a></li>
  <li><a href="#logistic-regression-1" id="toc-logistic-regression-1" class="nav-link" data-scroll-target="#logistic-regression-1"><span class="header-section-number">5.2.4</span> Logistic regression</a></li>
  </ul>
</li>
  <li>
<a href="#ordinal-regression" id="toc-ordinal-regression" class="nav-link" data-scroll-target="#ordinal-regression"><span class="header-section-number">5.3</span> Ordinal Regression</a>
  <ul class="collapse">
<li><a href="#introduction-to-the-dataset-1" id="toc-introduction-to-the-dataset-1" class="nav-link" data-scroll-target="#introduction-to-the-dataset-1"><span class="header-section-number">5.3.1</span> Introduction to the dataset</a></li>
  <li><a href="#exploratory-data-analysis-1" id="toc-exploratory-data-analysis-1" class="nav-link" data-scroll-target="#exploratory-data-analysis-1"><span class="header-section-number">5.3.2</span> Exploratory data analysis</a></li>
  <li><a href="#would-linear-regression-work-1" id="toc-would-linear-regression-work-1" class="nav-link" data-scroll-target="#would-linear-regression-work-1"><span class="header-section-number">5.3.3</span> Would linear regression work?</a></li>
  <li><a href="#ordinal-regression-1" id="toc-ordinal-regression-1" class="nav-link" data-scroll-target="#ordinal-regression-1"><span class="header-section-number">5.3.4</span> Ordinal regression</a></li>
  </ul>
</li>
  <li>
<a href="#test-yourself" id="toc-test-yourself" class="nav-link" data-scroll-target="#test-yourself"><span class="header-section-number">5.4</span> Test Yourself</a>
  <ul class="collapse">
<li><a href="#independent-logistic-regression" id="toc-independent-logistic-regression" class="nav-link" data-scroll-target="#independent-logistic-regression"><span class="header-section-number">5.4.1</span> Independent logistic regression</a></li>
  <li><a href="#independent-ordinal-regression" id="toc-independent-ordinal-regression" class="nav-link" data-scroll-target="#independent-ordinal-regression"><span class="header-section-number">5.4.2</span> Independent ordinal regression</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Generalised Linear Regression</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>In this chapter, we build on simple and multiple linear regression. All the lessons you learnt there still apply for building models with one or more predictors, but sometimes it is not appropriate to assume normality. It is a popular and convenient choice as assuming normality is often robust, but for some outcomes it would simply not be the appropriate choice. Generalised linear models allow you to specify a link and link function for the model residuals, so you can apply a linear model to alternative distributions. In this chapter, we will cover two types of generalised linear models: logistic regression and ordinal regression.</p>
<p><strong>Chapter Intended Learning Outcomes (ILOs)</strong></p>
<p>By the end of this chapter, you should be able to:</p>
<ol type="1">
<li><p>Understand how to run and interpret <a href="#logistic-regression">logistic regression</a>.</p></li>
<li><p>Understand how to run and interpret <a href="#ordinal-regression">ordinal regression</a>.</p></li>
</ol>
<section id="chapter-preparation" class="level2" data-number="5.1"><h2 data-number="5.1" class="anchored" data-anchor-id="chapter-preparation">
<span class="header-section-number">5.1</span> Chapter preparation</h2>
<p>In this chapter, we need a few different datasets, so we will introduce them as we need them.</p>
<section id="organising-your-files-and-project-for-the-chapter" class="level3" data-number="5.1.1"><h3 data-number="5.1.1" class="anchored" data-anchor-id="organising-your-files-and-project-for-the-chapter">
<span class="header-section-number">5.1.1</span> Organising your files and project for the chapter</h3>
<p>Before we can get started, you need to organise your files and project for the chapter, so your working directory is in order.</p>
<ol type="1">
<li><p>In your folder for statistics and research design <code>Stats_Research_Design</code>, create a new folder called <code>05_regression_generalised</code>. Within <code>05_regression_generalised</code>, create two new folders called <code>data</code> and <code>figures</code>.</p></li>
<li><p>Create an R Project for <code>05_regression_generalised</code> as an existing directory for your chapter folder. This should now be your working directory.</p></li>
<li><p>Create a new Quarto document and give it a sensible title describing the chapter, such as <code>05 Generalised Linear Regression</code>. Save the file in your <code>05_regression_generalised</code> folder.</p></li>
<li><p>We are working with a few data sets in this chapter, so please save the following zip file containing all the data files you need: <a href="data/05_data.zip">Chapter 05 Data</a>. Right click the link and select “save link as”, or clicking the link will save the file to your Downloads. Extract the files and make sure that you save them as “.csv”. Save or copy the files to your <code>data/</code> folder within <code>05_regression_generalised</code>.</p></li>
</ol>
<p>You are now ready to start working on the chapter!</p>
</section></section><section id="logistic-regression" class="level2" data-number="5.2"><h2 data-number="5.2" class="anchored" data-anchor-id="logistic-regression">
<span class="header-section-number">5.2</span> Logistic Regression</h2>
<section id="introduction-to-the-dataset" class="level3" data-number="5.2.1"><h3 data-number="5.2.1" class="anchored" data-anchor-id="introduction-to-the-dataset">
<span class="header-section-number">5.2.1</span> Introduction to the dataset</h3>
<p>For the guided examples, we have two datasets, but we will introduce them in turn. To demonstrate logistic regression, we will use data from <span class="citation" data-cites="bostyn_mice_2018">Bostyn et al. (<a href="references.html#ref-bostyn_mice_2018" role="doc-biblioref">2018</a>)</span>.</p>
<p>Bostyn et al.&nbsp;studied the classic trolley-dilemma in moral philosophy. In the typical format, a trolley (streetcar/tram) is travelling along tracks and will run over five people. However, you have the choice to pull a lever and divert the trolley to run over just one person. Although this would save lives, you must manually intervene to essentially kill one person. This is typically always a hypothetical scenario as it’s difficult to ask an ethics board for permission to run over people. In this study, Bostyn et al.&nbsp;compared a hypothetical version of the trolley-dilemma with a (seemingly) realistic version. Participants chose between not intervening and allowing five mice in a cage to be shocked with electricity or they could intervene and one mouse would be shocked instead. Do not worry, the mice were never shocked but participants did not know it at the time.</p>
<p>Their research question was: would there be a difference in moral decision-making when participants completed a hypothetical compared to a real version of the trolley-dilemma task? There was seemingly no hypothesis, so we will just focus on addressing the research question.</p>
<p>There is one independent variable (<code>STUDY</code>) to randomly allocate participants into one of two groups:</p>
<ol type="1">
<li><p>The “real” group (group <code>1</code> in the data) attended a lab session where they saw two cages of real mice. They had 20 seconds to decide whether to press a button and divert the electric shock to the cage with one mouse.</p></li>
<li><p>The hypothetical group (group <code>2</code> in the data) completed a more traditional version of the study where they just responded on a computer for whether they would intervene or not after reading a description of allowing five mice to be shocked or choosing for one mouse to be shocked.</p></li>
</ol>
<p>Participants completed a bunch of additional measures on moral judgement, empathy, psychopathy etc., but our main outcome of interest is whether they chose to intervene (<code>1</code>) or not (<code>0</code>) from the variable <code>DECISION</code>. They label these two decisions as deontological when people intervened and consequentialist when people did not intervene. For plotting, we will use the labels, but for the analyses we will use the 0s and 1s.</p>
<p>We first need to load some packages and the data for this task. If you do not have any of the packages, make sure you install them first.</p>
<p>As the first activity, try and test yourself by completing the following task list to practice your data wrangling skills. Create a final object called <code>bostyn_data</code> to be consistent with the tasks below. If you just want to focus on fitting the models, then you can just copy the code in the solution.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try this
</div>
</div>
<div class="callout-body-container callout-body">
<p>To wrangle the data, complete the following tasks:</p>
<ol type="1">
<li>
<p>Load the following packages. If you do not have them already, remember you will need to install them first if you are working on your own computer:</p>
<ul>
<li><p><pkg>tidyverse</pkg></p></li>
<li><p><pkg>emmeans</pkg></p></li>
<li><p><pkg>ordinal</pkg></p></li>
<li><p><pkg>sjPlot</pkg></p></li>
</ul>
</li>
<li><p>You can complete the following tasks individually or combining things in one pipe, you just need a final object called <code>bostyn_data</code>. Read the data file <code>data/bostyn_2018.csv</code>.</p></li>
<li><p>There are loads of variables in the data which you can explore in your own time, but for this chapter, just select the first four variables from <code>STUDY</code> to <code>DECISION</code>.</p></li>
<li><p>There are a few missing values in <code>DECISION</code>, so remove the NAs at this point.</p></li>
<li>
<p>To help with plotting and modelling later, create two new variables:</p>
<ul>
<li><p>Create a new variable called <code>study</code> where you create a factor to recode the values from <code>STUDY</code>. 1 should be relabelled “Real” and 2 should be relabelled as “Hypothetical”.</p></li>
<li><p>Create a new variable called <code>label</code> where you create a factor to recode the values from <code>DECISION</code>. 0 should be relabelled “DEO” for deontological and 1 should be relabelled as “CON” for consequentialist.</p></li>
</ul>
</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You should have the following in a code chunk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># wrangling and visualisation functions </span></span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="co"># Parameter estimates</span></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb1-5"><a href="#cb1-5"></a><span class="co"># Ordinal regression for later</span></span>
<span id="cb1-6"><a href="#cb1-6"></a><span class="fu">library</span>(ordinal)</span>
<span id="cb1-7"><a href="#cb1-7"></a><span class="co"># plotting model objects</span></span>
<span id="cb1-8"><a href="#cb1-8"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb1-9"><a href="#cb1-9"></a></span>
<span id="cb1-10"><a href="#cb1-10"></a><span class="co"># Bostyn data for logistic regression</span></span>
<span id="cb1-11"><a href="#cb1-11"></a>bostyn_data <span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">"data/Bostyn_2018.csv"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb1-12"><a href="#cb1-12"></a>  <span class="fu">select</span>(STUDY<span class="sc">:</span>DECISION) <span class="sc">%&gt;%</span>  <span class="co"># just select first four variables</span></span>
<span id="cb1-13"><a href="#cb1-13"></a>  <span class="fu">drop_na</span>(DECISION) <span class="sc">%&gt;%</span> </span>
<span id="cb1-14"><a href="#cb1-14"></a>  <span class="fu">mutate</span>(<span class="at">study =</span> <span class="fu">factor</span>(STUDY, </span>
<span id="cb1-15"><a href="#cb1-15"></a>                        <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), </span>
<span id="cb1-16"><a href="#cb1-16"></a>                        <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Real"</span>, <span class="st">"Hypothetical"</span>)),</span>
<span id="cb1-17"><a href="#cb1-17"></a>         <span class="at">label =</span> <span class="fu">factor</span>(DECISION, </span>
<span id="cb1-18"><a href="#cb1-18"></a>                           <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), </span>
<span id="cb1-19"><a href="#cb1-19"></a>                           <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"DEO"</span>, <span class="st">"CON"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="exploratory-data-analysis" class="level3" data-number="5.2.2"><h3 data-number="5.2.2" class="anchored" data-anchor-id="exploratory-data-analysis">
<span class="header-section-number">5.2.2</span> Exploratory data analysis</h3>
<p>When starting any data analysis, it is important to visualise the data for some exploratory data analysis. Using the skills you developed in data skills for reproducible research, you can explore the data to understand its properties and look for potential patterns. In this scenario, a bar plot might be handy as we have a dichotomous outcome, so we can explore the frequency of responses across each group.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>bostyn_data <span class="sc">%&gt;%</span> </span>
<span id="cb2-2"><a href="#cb2-2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> study, <span class="at">fill =</span> label)) <span class="sc">+</span> </span>
<span id="cb2-3"><a href="#cb2-3"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span> </span>
<span id="cb2-4"><a href="#cb2-4"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">name =</span> <span class="st">"Study"</span>) <span class="sc">+</span> </span>
<span id="cb2-5"><a href="#cb2-5"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Frequency"</span>, </span>
<span id="cb2-6"><a href="#cb2-6"></a>                     <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">200</span>, <span class="dv">50</span>), </span>
<span id="cb2-7"><a href="#cb2-7"></a>                     <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">200</span>)) <span class="sc">+</span> </span>
<span id="cb2-8"><a href="#cb2-8"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">name =</span> <span class="st">"Decision"</span>, <span class="at">option =</span> <span class="st">"E"</span>) <span class="sc">+</span></span>
<span id="cb2-9"><a href="#cb2-9"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-glm_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In the real group, there is a bigger difference in the number of people choosing to intervene and make a consequentialist response (1s in the data) compared to the hypothetical group where there is a smaller difference. The number of people choosing not to intervene and make a deontological response (0s in the data) is smaller in both groups, but it’s the proportional difference which changes.</p>
<p>Instead of counts, we can also express binary 0 and 1 data as a proportion or probability of intervening. If you take the mean of binary data, it tells you the proportion, so we can calculate the proportion of participant’s choosing to intervene as a consequentialist decision.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>bostyn_data <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2"></a>  <span class="fu">group_by</span>(study) <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3"></a>  <span class="fu">summarise</span>(<span class="at">proportion_con =</span> <span class="fu">mean</span>(DECISION))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">study</th>
<th style="text-align: right;">proportion_con</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Real</td>
<td style="text-align: right;">0.8645833</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hypothetical</td>
<td style="text-align: right;">0.7469880</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Participants in the real group (86%) were more likely to intervene than participants in the hypothetical group (75%). These are just descriptive statistics though, so you need to think about modelling to make inferences from these data.</p>
</section><section id="would-linear-regression-work" class="level3" data-number="5.2.3"><h3 data-number="5.2.3" class="anchored" data-anchor-id="would-linear-regression-work">
<span class="header-section-number">5.2.3</span> Would linear regression work?</h3>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>The most important part of data analysis is your role as the decision maker and thinking about what would be the most appropriate choice of model. Sometimes, there are equally valid approaches, while other times there is one better suited approach. If you apply an inappropriate test, R will gladly follow your instructions. Its your job to think critically about your modelling approach and check its an appropriate choice.</p>
</div>
</div>
<p>When we have a dichotomous outcome coded 0 and 1, it has numerical value, so R will happily apply regular linear regression.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>bostyn_model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DECISION <span class="sc">~</span> study, <span class="at">data =</span> bostyn_data)</span>
<span id="cb4-2"><a href="#cb4-2"></a></span>
<span id="cb4-3"><a href="#cb4-3"></a><span class="fu">summary</span>(bostyn_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DECISION ~ study, data = bostyn_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.8646  0.1354  0.1354  0.1354  0.2530 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        0.86458    0.02698  32.041   &lt;2e-16 ***
studyHypothetical -0.11760    0.04912  -2.394   0.0173 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3739 on 273 degrees of freedom
Multiple R-squared:  0.02056,   Adjusted R-squared:  0.01698 
F-statistic: 5.732 on 1 and 273 DF,  p-value: 0.01733</code></pre>
</div>
</div>
<p>It is somewhat interpretable as when you take the mean of binary data, you get the proportion. So, the intercept represents the proportion of consequentialist responses for those in the real group, and the slope coefficient represents the mean difference in proportion, suggesting there are .12/12% fewer consequentialist responses in the hypothetical group, which is statistically significant at <span class="math inline">\(\alpha\)</span> = .05.</p>
<p>Although it works and we can make sense of the results, the question is whether it is an informative and appropriate way of modelling a binary outcome. Lets check the assumptions to see if anything looks off.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># Change the panel layout to 2 x 2</span></span>
<span id="cb6-2"><a href="#cb6-2"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb6-3"><a href="#cb6-3"></a></span>
<span id="cb6-4"><a href="#cb6-4"></a><span class="co"># plot the diagnostic plots</span></span>
<span id="cb6-5"><a href="#cb6-5"></a><span class="fu">plot</span>(bostyn_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-glm_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now we can see the problems. Because we only have two possible outcomes, the assumption checks are all off. The qq plot in panel 2 particularly shows the problem, as there is a giant chunk missing where the values between 0 and 1 should be, at least theoretically if we assume normal residuals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="co"># plot the qq plot</span></span>
<span id="cb7-2"><a href="#cb7-2"></a><span class="fu">plot</span>(bostyn_model1, </span>
<span id="cb7-3"><a href="#cb7-3"></a>     <span class="at">which =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-glm_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now we can apply logistic regression to more appropriately model the dichotomous nature of the outcome.</p>
</section><section id="logistic-regression-1" class="level3" data-number="5.2.4"><h3 data-number="5.2.4" class="anchored" data-anchor-id="logistic-regression-1">
<span class="header-section-number">5.2.4</span> Logistic regression</h3>
<section id="generalised-linear-regression" class="level4" data-number="5.2.4.1"><h4 data-number="5.2.4.1" class="anchored" data-anchor-id="generalised-linear-regression">
<span class="header-section-number">5.2.4.1</span> Generalised linear regression</h4>
<p>In a linear model, we model the outcome as a product of an intercept, a slope, and error. Its that final error part which is why we have worried about normality so far. In a regular linear regression model, we need the model residuals (the difference between the expected and observed values) to be normally distributed.</p>
<p>Logistic regression is an adaptation of the linear regression framework we have worked with so far, where we can replace that error component. This is called generalised linear regression and we can specify a link and link function, instead of normal residuals being built into the model.</p>
<p>So far, we have always used <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>, but R comes with another function called <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> for generalised linear regression models. To demonstrate how we can set the link family, we can use it to recreate a regular linear regression model, but this time explicitly calling a normal distribution as the link (using its alternate name a Gaussian distribution) and “identity” as the link function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>bostyn_model1_glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(DECISION <span class="sc">~</span> study, </span>
<span id="cb8-2"><a href="#cb8-2"></a>                     <span class="at">family =</span> <span class="fu">gaussian</span>(<span class="at">link =</span> <span class="st">"identity"</span>), </span>
<span id="cb8-3"><a href="#cb8-3"></a>                     <span class="at">data =</span> bostyn_data)</span>
<span id="cb8-4"><a href="#cb8-4"></a></span>
<span id="cb8-5"><a href="#cb8-5"></a><span class="fu">summary</span>(bostyn_model1_glm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = DECISION ~ study, family = gaussian(link = "identity"), 
    data = bostyn_data)

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        0.86458    0.02698  32.041   &lt;2e-16 ***
studyHypothetical -0.11760    0.04912  -2.394   0.0173 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 0.1398019)

    Null deviance: 38.967  on 274  degrees of freedom
Residual deviance: 38.166  on 273  degrees of freedom
AIC: 243.34

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>The link specifies the distribution family and the link function is the transformation for the model units. So, for our normal/Gaussian distribution, we have an identity link which essentially means no transformation, just the values we input. A normal distribution is described by a mean and standard deviation, so we just interpret the raw units in the model.</p>
<p>The results here are the same to the third decimal to show its an identical process. The only difference to our regular model output is the model fit statistics. Regular linear regression uses ordinal least squares to fit the model, whereas generalised linear regression fits the models using maximum likelihood. Holding everything else constant, this requires greater computing power, so its overkill to use <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> when you just want to assume normal/Gaussian errors, but its important to show the process behind these procedures.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this chapter, we are focusing on logistic regression and ordinal regression as variations of generalised linear regression. There are more possibilities though, so type <code><a href="https://rdrr.io/r/stats/family.html">?family</a></code> into the console to see the different families you could enter for the link and link function.</p>
</div>
</div>
</section><section id="logistic-regression-in-glm" class="level4" data-number="5.2.4.2"><h4 data-number="5.2.4.2" class="anchored" data-anchor-id="logistic-regression-in-glm">
<span class="header-section-number">5.2.4.2</span> Logistic regression in <code>glm()</code>
</h4>
<p>After that brief detour, we will now actually fit the logistic regression model using <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code>. As we have a dichotomous outcome, one useful distribution is the binomial. This applies when you want to calculate the probability of an dichotomous outcome from a series of successes (1s) and failures (0s). This models that probability nicely as it has a boundary of 0 or 0% (no successes) and 1 or 100% (all successes). Traditionally, we refer to successes and failures, but you can apply it to any binary outcome where one response is labelled 0 and the other response is labelled 1.</p>
<p>To apply the linear model element, we then use the “logit” link function as the unit transformation. Probability ranges between 0 and 1, odds range between 0 and infinity, but log odds (the logit bit) range between minus infinity and infinity, meaning we can fit straight lines to it. Let’s see what a logistic regression model looks like.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>bostyn_model2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(DECISION <span class="sc">~</span> study, </span>
<span id="cb10-2"><a href="#cb10-2"></a>                     <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>), </span>
<span id="cb10-3"><a href="#cb10-3"></a>                     <span class="at">data =</span> bostyn_data)</span>
<span id="cb10-4"><a href="#cb10-4"></a></span>
<span id="cb10-5"><a href="#cb10-5"></a><span class="fu">summary</span>(bostyn_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = DECISION ~ study, family = binomial(link = "logit"), 
    data = bostyn_data)

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         1.8539     0.2109   8.790   &lt;2e-16 ***
studyHypothetical  -0.7713     0.3290  -2.344   0.0191 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 251.53  on 274  degrees of freedom
Residual deviance: 246.17  on 273  degrees of freedom
AIC: 250.17

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">confint</span>(bostyn_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                     2.5 %    97.5 %
(Intercept)        1.45962  2.289875
studyHypothetical -1.41563 -0.120060</code></pre>
</div>
</div>
<p>The model looks reassuringly similar. We have our coefficients for the intercept and slope, with their standard errors and <em>p</em>-values. There are no <em>p</em>-values for the model fit though as remember they are based on maximum likelihood, rather than least squares.</p>
<p>The main difference here is the interpretation of the coefficients. The link function is logit, so we get them in log odds, meaning the logarithm of an odds ratio (how likely something is to happen). These are not intuitive to interpret, so we can take the exponential to transform the slope coefficient from log odds to an odds ratio with its 95% CI.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="co"># Take the exponential of the second coefficient to avoid typing it manually</span></span>
<span id="cb15-2"><a href="#cb15-2"></a><span class="fu">exp</span>(<span class="fu">coef</span>(bostyn_model2)[<span class="dv">2</span>]) <span class="co">#subset second component</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>studyHypothetical 
        0.4624211 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="co"># Exponential of the confidence interval</span></span>
<span id="cb17-2"><a href="#cb17-2"></a><span class="fu">exp</span>(<span class="fu">confint</span>(bostyn_model2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                      2.5 %    97.5 %
(Intercept)       4.3043235 9.8737011
studyHypothetical 0.2427726 0.8868672</code></pre>
</div>
</div>
<p>An odds ratio is a ratio of the odds of an event happening in one group compared to the odds of an event happening in another group. In this context, a ratio of making a consequentialist decision (1s compared to 0s) in the real group compared to the hypothetical group.</p>
<p>An odds ratio of 1 means they are equally likely to happen. An odds ratio of less than 1 means something is less likely to happen, whereas more than 1 means something is more likely to happen. The odds ratio is 0.46 here, suggesting the odds of making a consequentialist decision is lower in the hypothetical group (our target group) compared to the real group (the reference group). Odds ratios below 1 can be tricky to interpret, so you can flip them around by taking the reciprocal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="co"># Take the reciprocal of the exponential of the second coefficient </span></span>
<span id="cb20-2"><a href="#cb20-2"></a><span class="dv">1</span> <span class="sc">/</span> <span class="fu">exp</span>(<span class="fu">coef</span>(bostyn_model2)[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>studyHypothetical 
         2.162531 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="co"># Reciprocal of the exponential of the confidence interval</span></span>
<span id="cb22-2"><a href="#cb22-2"></a><span class="dv">1</span> <span class="sc">/</span> <span class="fu">exp</span>(<span class="fu">confint</span>(bostyn_model2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                      2.5 %    97.5 %
(Intercept)       0.2323245 0.1012791
studyHypothetical 4.1190801 1.1275645</code></pre>
</div>
</div>
<p>Expressed this way, there are 2.16 (95% CI = [1.13, 4.12]) lower odds of making a consequentialist decision in the hypothetical group compared to the real group. In this model, it is statistically significant but we can see there is a decent amount of uncertainty around the estimate, spanning from 1.13 to 4.12.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this scenario, you would get the same reciprocal odds ratio if you changed the groups around with correction as the reference group. Taking the reciprocal is the same information expressed differently, but its important you are clear about the model estimates to avoid confusing your reader. If you do this yourself, make sure you explain what the model estimates were and how you took the reciprocal.</p>
</div>
</div>
<p>Returning to the idea of model comparison, we could compare the two GLM models using <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> and it will tell you the change in deviance (relating the maximum likelihood fitting process), but we can focus on comparing the AIC values for model fit between the two models. Lower values of AIC are better and if we subtract model 1 (the linear model) from model 2 (the logistic model), a negative difference would indicate better model fit from the ordinal model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="co"># AIC of model 1</span></span>
<span id="cb25-2"><a href="#cb25-2"></a><span class="fu">AIC</span>(bostyn_model1_glm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 243.3384</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="co"># AIC of model 2</span></span>
<span id="cb27-2"><a href="#cb27-2"></a><span class="fu">AIC</span>(bostyn_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 250.1702</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="co"># difference in AIC values</span></span>
<span id="cb29-2"><a href="#cb29-2"></a><span class="fu">AIC</span>(bostyn_model2) <span class="sc">-</span> <span class="fu">AIC</span>(bostyn_model1_glm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.831779</code></pre>
</div>
</div>
<p>Interestingly, the second model actually has worse fit! There is less prediction error when we use the regular linear regression model compared to the logistic regression model. Given the assumptions and what we know of the design though, the logistic regression model would still be the sensible choice here. This reinforces why it is so important to recognise you as the decision maker and considering different sources of information.</p>
</section><section id="calculating-the-model-probability-estimates" class="level4" data-number="5.2.4.3"><h4 data-number="5.2.4.3" class="anchored" data-anchor-id="calculating-the-model-probability-estimates">
<span class="header-section-number">5.2.4.3</span> Calculating the model probability estimates</h4>
<p>Finally, there is a relationship between probability, odds, and log odds. We can use the coefficients to produce model estimates for the probability of a consequentialist decision in each group. <span class="citation" data-cites="voas_odds_2024">Voas &amp; Watt (<a href="references.html#ref-voas_odds_2024" role="doc-biblioref">2024</a>)</span> recommend this as the key output of a logistic regression model for helping to communicate your findings.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Relatedly, the whole purpose of <span class="citation" data-cites="voas_odds_2024">Voas &amp; Watt (<a href="references.html#ref-voas_odds_2024" role="doc-biblioref">2024</a>)</span> is to warn against a common misinterpretation of logistic regression. Often, people interpret the odds ratio as an increase in the likelihood of a response. For example, our odds ratio of 2.16 mistakenly interpreted as a consequentialist decision being just over twice as likely in the real group than the hypothetical group. In reality, it is a 2.16 higher <em>odds</em> of making a consequentialist decision, and the difference will be clearer once we express it as probabilities.</p>
</div>
</div>
<p>The logic is the same as for regular linear regression models, the intercept is the reference group, and the slope coefficient for your predictor is the shift across units of your outcome. First, we can calculate the model estimated probability for the reference group by taking the exponential of the intercept log odds divided by 1 plus the exponential intercept log odds:</p>
<p><span class="math display">\[ p = \dfrac{e^{b_0}}{1 + e^{b_0}}\]</span></p>
<p>Or as code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="co"># Estimated probability in the reference group</span></span>
<span id="cb31-2"><a href="#cb31-2"></a><span class="co"># We use coef() to isolate the model coefficients and subset the 1st item - the intercept</span></span>
<span id="cb31-3"><a href="#cb31-3"></a><span class="fu">exp</span>(<span class="fu">coef</span>(bostyn_model2)[<span class="dv">1</span>]) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(bostyn_model2)[<span class="dv">1</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
  0.8645833 </code></pre>
</div>
</div>
<p>This means the estimated probability of a consequentialist decision in the real group is .86 or 86%.</p>
<p>Then for the hypothetical group, we repeat the process, but adding together the intercept and slope coefficient. Given the slope was negative, this is the equivalent of subtracting the slope. As an equation:</p>
<p><span class="math display">\[ p = \dfrac{e^{b_0 + b_1}}{1 + e^{b_0 + b_1}}\]</span></p>
<p>Then as code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="co"># Estimated probability in the target group</span></span>
<span id="cb33-2"><a href="#cb33-2"></a><span class="co"># We use coef() to isolate the model coefficients and subset the 1st item - the intercept </span></span>
<span id="cb33-3"><a href="#cb33-3"></a><span class="co"># We then add the 2nd item in coef() - the slope </span></span>
<span id="cb33-4"><a href="#cb33-4"></a><span class="fu">exp</span>(<span class="fu">coef</span>(bostyn_model2)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(bostyn_model2)[<span class="dv">2</span>]) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(bostyn_model2)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(bostyn_model2)[<span class="dv">2</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   0.746988 </code></pre>
</div>
</div>
<p>This means the estimated probability of a consequentialist decision in the hypothetical group is .75 or 75%. These values line up nicely with our original summary statistics, but keep in mind they are model estimates. They are closer here as its a very simple model and we are demonstrating the principles, but they will not line up this close when you have more complex models with marginal effects to understand.</p>
</section><section id="using-emmeans-to-get-model-estimates" class="level4" data-number="5.2.4.4"><h4 data-number="5.2.4.4" class="anchored" data-anchor-id="using-emmeans-to-get-model-estimates">
<span class="header-section-number">5.2.4.4</span> Using <code>emmeans</code> to get model estimates</h4>
<p>Another way of getting model estimates is using the <code>emmeans()</code> function from the <pkg>emmeans</pkg> package <span class="citation" data-cites="Lenth2022">(<a href="references.html#ref-Lenth2022" role="doc-biblioref">Lenth, 2024</a>)</span>. This can be particularly useful in more complicated models when you want marginal effects across interactions, but you might prefer to see the estimates in this format instead of reconstructing them from the coefficients.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="co"># logistic regression model as the object</span></span>
<span id="cb35-2"><a href="#cb35-2"></a><span class="co"># Specifying Condition as the predictor we want marginal effects for</span></span>
<span id="cb35-3"><a href="#cb35-3"></a><span class="fu">emmeans</span>(bostyn_model2, <span class="at">specs =</span> <span class="st">"study"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> study        emmean    SE  df asymp.LCL asymp.UCL
 Real           1.85 0.211 Inf     1.441      2.27
 Hypothetical   1.08 0.252 Inf     0.588      1.58

Results are given on the logit (not the response) scale. 
Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>These are still in log odds units, so you can calculate the probability using the same $ p = $ method. For example, the estimated probability of a consequentialist decision in the real group is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="fu">exp</span>(<span class="fl">1.85</span>) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fl">1.85</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8641271</code></pre>
</div>
</div>
<p>Which corresponds nicely with what we reconstructed from the model coefficients.</p>
</section><section id="plotting-logistic-regression-models" class="level4" data-number="5.2.4.5"><h4 data-number="5.2.4.5" class="anchored" data-anchor-id="plotting-logistic-regression-models">
<span class="header-section-number">5.2.4.5</span> Plotting logistic regression models</h4>
<p>Like any model, it will make your life and the lives of your reader much easier to supplement your statistics with a plot informatively showing the model estimates. We can use the <pkg>sjPlot</pkg> function <span class="citation" data-cites="luedecke_2024">(<a href="references.html#ref-luedecke_2024" role="doc-biblioref">Lüdecke, 2024</a>)</span> to take the logistic regression model and plot the predicted probabilites.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="co"># sjPlot makes it easy to plot estimates from the model</span></span>
<span id="cb39-2"><a href="#cb39-2"></a><span class="fu">plot_model</span>(bostyn_model2, <span class="co"># You enter the model object</span></span>
<span id="cb39-3"><a href="#cb39-3"></a>           <span class="at">type =</span> <span class="st">"pred"</span>, <span class="co"># The type of plot you want to create</span></span>
<span id="cb39-4"><a href="#cb39-4"></a>           <span class="at">terms =</span> <span class="st">"study"</span>) <span class="co"># The predictor(s)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-glm_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Plus some additional arguments and <code>ggplot()</code> layers to tidy things up.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a><span class="fu">plot_model</span>(bostyn_model2,</span>
<span id="cb40-2"><a href="#cb40-2"></a>           <span class="at">type =</span> <span class="st">"pred"</span>,</span>
<span id="cb40-3"><a href="#cb40-3"></a>           <span class="at">terms =</span> <span class="st">"study"</span>,</span>
<span id="cb40-4"><a href="#cb40-4"></a>           <span class="at">axis.title =</span> <span class="fu">c</span>(<span class="st">"Real or Hypothetical Scenario"</span>, <span class="st">"Proportion Consequentialist Decision"</span>),</span>
<span id="cb40-5"><a href="#cb40-5"></a>           <span class="at">axis.lim =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb40-6"><a href="#cb40-6"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span> </span>
<span id="cb40-7"><a href="#cb40-7"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Scale for y is already present.
Adding another scale for y, which will replace the existing scale.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-glm_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section></section></section><section id="ordinal-regression" class="level2" data-number="5.3"><h2 data-number="5.3" class="anchored" data-anchor-id="ordinal-regression">
<span class="header-section-number">5.3</span> Ordinal Regression</h2>
<section id="introduction-to-the-dataset-1" class="level3" data-number="5.3.1"><h3 data-number="5.3.1" class="anchored" data-anchor-id="introduction-to-the-dataset-1">
<span class="header-section-number">5.3.1</span> Introduction to the dataset</h3>
<p>To demonstrate ordinal regression, we will use data from <span class="citation" data-cites="brandt_does_2014">Brandt et al. (<a href="references.html#ref-brandt_does_2014" role="doc-biblioref">2014</a>)</span>. The aim of Brandt et al.&nbsp;was to replicate a relatively famous social psychology study (Banerjee et al., 2012) on the effect of recalling unethical behaviour on the perception of brightness.</p>
<p>In common language, unethical behaviour is considered as “dark”, so the original authors designed a priming experiment where participants were randomly allocated to recall an unethical behaviour or an ethical behaviour from their past. Participants then completed a series of measures including their perception of how bright the testing room was. Brandt et al.&nbsp;were sceptical and wanted to replicate this study to see if they could find similar results.</p>
<p>Participants were randomly allocated (<code>ExpCond</code>) to recall an unethical behaviour (<code>1</code>; n = 49) or an ethical behaviour (<code>0</code>; n = 51). The key outcome was their perception of how bright the room was (<code>welllit</code>), from 1 (not bright at all) to 7 (very bright). The research question was: Does recalling unethical behaviour lead people to perceive a room as darker than if they recall ethical behaviour?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a><span class="co"># Brandt data for ordinal regression</span></span>
<span id="cb42-2"><a href="#cb42-2"></a>Brandt_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Brandt_unlit.csv"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb42-3"><a href="#cb42-3"></a>  <span class="fu">mutate</span>(<span class="at">ExpCond =</span> <span class="fu">as.factor</span>(<span class="fu">case_when</span>(ExpCond <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">0</span>, <span class="co"># Ethical </span></span>
<span id="cb42-4"><a href="#cb42-4"></a>                             ExpCond <span class="sc">==</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">~</span> <span class="dv">1</span>))) <span class="co"># Unethical</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 100 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (7): BasicFollowedDirections, ExpCond, flagged, ppnr, bright, welllit, W...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section><section id="exploratory-data-analysis-1" class="level3" data-number="5.3.2"><h3 data-number="5.3.2" class="anchored" data-anchor-id="exploratory-data-analysis-1">
<span class="header-section-number">5.3.2</span> Exploratory data analysis</h3>
<p>When starting any data analysis, it is important to visualise the data for some exploratory data analysis. Using the skills you developed in data skills for reproducible research, you can explore the data to understand its properties and look for potential patterns. We can create a boxplot to get a brief overview of how perceived brightness changes depending on the experimental condition.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a>Brandt_data <span class="sc">%&gt;%</span> </span>
<span id="cb44-2"><a href="#cb44-2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ExpCond, <span class="at">y =</span> welllit)) <span class="sc">+</span> </span>
<span id="cb44-3"><a href="#cb44-3"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb44-4"><a href="#cb44-4"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">name =</span> <span class="st">"Ethical Group"</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Ethical"</span>, <span class="st">"Unethical"</span>)) <span class="sc">+</span> </span>
<span id="cb44-5"><a href="#cb44-5"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Brightness Rating"</span>, <span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>) <span class="sc">+</span> </span>
<span id="cb44-6"><a href="#cb44-6"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-glm_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There are some signs of the outcome being ordinal, but its not super obvious. We can create a histogram showing the distribution of brightness rating by group, to see how discrete the data are.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a>Brandt_data <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="#cb45-2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> welllit, <span class="at">fill =</span> ExpCond)) <span class="sc">+</span> </span>
<span id="cb45-3"><a href="#cb45-3"></a>  <span class="fu">geom_histogram</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span> </span>
<span id="cb45-4"><a href="#cb45-4"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">name =</span> <span class="st">"Brightness Rating"</span>, <span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>) <span class="sc">+</span> </span>
<span id="cb45-5"><a href="#cb45-5"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Count"</span>, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">20</span>, <span class="dv">5</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">20</span>)) <span class="sc">+</span> </span>
<span id="cb45-6"><a href="#cb45-6"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-glm_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>That’s much better. Now, we can see the clearly ordinal nature of brightness rating and how participants can only respond on the integer 1-7 scale.</p>
</section><section id="would-linear-regression-work-1" class="level3" data-number="5.3.3"><h3 data-number="5.3.3" class="anchored" data-anchor-id="would-linear-regression-work-1">
<span class="header-section-number">5.3.3</span> Would linear regression work?</h3>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>The most important part of data analysis is your role as the decision maker and thinking about what would be the most appropriate choice of modelling. Sometimes, there are equally valid approaches, while other times there is one better suited approach. If you apply an inappropriate test, R will gladly follow your instructions. Its your job to think critically about your modelling approach and check its an appropriate choice.</p>
</div>
</div>
<p>R will happily let us apply simple linear regression to predict brightness rating (<code>welllit</code>) from the categorical predictor of experimental condition (<code>ExpCond</code>). This is by far the most common approach to tackling ordinal outcomes in psychology, particularly when you take the mean or sum of multiple ordinal items, so it looks a little more continuous. If you meet the other assumptions of linear regression, it can often be a pragmatic and robust approach.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="co"># Linear model predicting brightness rating from condition </span></span>
<span id="cb46-2"><a href="#cb46-2"></a>brandt_model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(welllit <span class="sc">~</span> ExpCond, <span class="at">data =</span> Brandt_data)</span>
<span id="cb46-3"><a href="#cb46-3"></a></span>
<span id="cb46-4"><a href="#cb46-4"></a><span class="co"># model summary</span></span>
<span id="cb46-5"><a href="#cb46-5"></a><span class="fu">summary</span>(brandt_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = welllit ~ ExpCond, data = Brandt_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.1569 -0.3673  0.2379  0.8431  1.8431 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   5.1569     0.1779  28.992   &lt;2e-16 ***
ExpCond1      0.2105     0.2541   0.828    0.409    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.27 on 98 degrees of freedom
Multiple R-squared:  0.006953,  Adjusted R-squared:  -0.00318 
F-statistic: 0.6861 on 1 and 98 DF,  p-value: 0.4095</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a><span class="co"># Confidence intervals around estimates</span></span>
<span id="cb48-2"><a href="#cb48-2"></a><span class="fu">confint</span>(brandt_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %    97.5 %
(Intercept)  4.8038772 5.5098483
ExpCond1    -0.2937809 0.7147492</code></pre>
</div>
</div>
<p>The intercept suggests the mean brightness rating for participants in the ethical group was 5.16. The coefficient and model are not statistically significant - explaining very little variance in the outcome - and suggests those in the unethical group had a mean increase in brightness rating of 0.21 [-0.29, 0.71].</p>
<p>The first problem comes in the interpretation. As a linear model expecting normally distributed residuals, we get means for the intercept and coefficient, and they could - at least theoretically - be any values. So, we get an average of 5.16 and 5.37 for our two groups, but the scale items could only be integers from 1-7. So, you can question how informative it is to treat these data as interval, when they are only labels for arbitrary numbers ranging from 1 (not bright at all) to 7 (very bright).</p>
<p>The second problem comes in the assumptions of the model. If the means are around the middle of the scale, it can behave approximately normal. If the means are closer to the boundaries, then you start running into problems as the residuals that the model thinks are theoretically boundless, hit a boundary. Let’s look at the checks for this model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a><span class="co"># Change the panel layout to 2 x 2</span></span>
<span id="cb50-2"><a href="#cb50-2"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb50-3"><a href="#cb50-3"></a></span>
<span id="cb50-4"><a href="#cb50-4"></a><span class="co"># plot the diagnostic plots</span></span>
<span id="cb50-5"><a href="#cb50-5"></a><span class="fu">plot</span>(brandt_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-glm_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The qq plot in pane 2 of the residuals against the theoretical distribution is key here. Most of the points follow the dashes line, but it shifts away towards the lower boundary. There are also telltale signs of discrete ordinal data as the residuals move in set points. This is because the outcome can only be 1-7, but the theoretical quantiles are boundless.</p>
<p>So, while the assumptions do not look catastrophic, we will explore how we can model the ordinal nature of the outcome better.</p>
</section><section id="ordinal-regression-1" class="level3" data-number="5.3.4"><h3 data-number="5.3.4" class="anchored" data-anchor-id="ordinal-regression-1">
<span class="header-section-number">5.3.4</span> Ordinal regression</h3>
<p>Ordinal regression models are a kind of logistic regression model. They are also known as cumulative link or ordered logit models. They work on the same logic as logistic regression where we want to model the probability of a discrete outcome, but instead of only two possible outcomes, ordinal regression models split a scale up into an ordered series of discrete outcomes. Between each scale point, the model estimates the threshold and sees how the outcome shifts across your predictor(s).</p>
<p>To get an idea of cumulative probability, we can plot the Brandt et al.&nbsp;data to see how the cumulative percentage of responses across the scale shifts for each group.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1"></a>Brandt_data <span class="sc">%&gt;%</span> </span>
<span id="cb51-2"><a href="#cb51-2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> welllit, <span class="at">colour =</span> ExpCond)) <span class="sc">+</span> </span>
<span id="cb51-3"><a href="#cb51-3"></a>  <span class="fu">stat_ecdf</span>() <span class="sc">+</span></span>
<span id="cb51-4"><a href="#cb51-4"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>, <span class="at">name =</span> <span class="st">"Brightness Perception"</span>) <span class="sc">+</span> </span>
<span id="cb51-5"><a href="#cb51-5"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.2</span>), <span class="at">name =</span> <span class="st">"Cumulative Percent"</span>) <span class="sc">+</span> </span>
<span id="cb51-6"><a href="#cb51-6"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-glm_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For each group, the lines corresponds with the cumulative percentage at each scale point. When the line is horizontal, there is no change. When the line moves vertically, it represents the next percentage increase, adding to the cumulative percentage from the previous shift, until you reach 100%.</p>
<p>Ordinal regression models estimate these shifts in probability and you get <em>k</em>-1 estimates for the thresholds, meaning you get one fewer estimate than the total number of scale points. Behind the scenes, the model interprets the outcome as a Gaussian looking latent variable, meaning the ordinal scale points are tapping into some kind of construct, but honouring there are discrete scale points.</p>
<p>The coefficient in the model represents the probability shift of a 1 scale point increase from one distribution to another on the scale of your predictors. So, for every 1-unit increase in a continuous predictor, you see how the probability shifts, or how the probability shifts for the difference between two groups in a categorical predictor. A positive slope coefficient would mean an increase in probability along your predictor scale, while a negative slope coefficient would mean a decrease in probability along your predictor scale.</p>
<p>We will fit ordinal regression models using the <pkg>ordinal</pkg><span class="citation" data-cites="Christensen2023">(<a href="references.html#ref-Christensen2023" role="doc-biblioref">Christensen, 2023</a>)</span> package as it nicely supports cumulative link models as regular regression models we have used until this point or scaled up to mixed effects models.</p>
<p>First, we need to convert the outcome into a factor, so there are a discrete ordered number of points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a>Brandt_data <span class="ot">&lt;-</span> Brandt_data <span class="sc">%&gt;%</span> </span>
<span id="cb52-2"><a href="#cb52-2"></a>  <span class="fu">mutate</span>(<span class="at">WellLitFactor =</span> <span class="fu">factor</span>(welllit))</span>
<span id="cb52-3"><a href="#cb52-3"></a></span>
<span id="cb52-4"><a href="#cb52-4"></a><span class="fu">levels</span>(Brandt_data<span class="sc">$</span>WellLitFactor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "1" "3" "4" "5" "6" "7"</code></pre>
</div>
</div>
<p>We can see here the scale points are in ascending order as we want them to be, and no one in the data ever responded 2. Next, we can fit our ordinal regression model using the same format as all our regression models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a><span class="co"># clm = cumulative link model</span></span>
<span id="cb54-2"><a href="#cb54-2"></a>brandt_model2 <span class="ot">&lt;-</span> <span class="fu">clm</span>(WellLitFactor <span class="sc">~</span> ExpCond, <span class="at">data =</span> Brandt_data)</span>
<span id="cb54-3"><a href="#cb54-3"></a></span>
<span id="cb54-4"><a href="#cb54-4"></a><span class="fu">summary</span>(brandt_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>formula: WellLitFactor ~ ExpCond
data:    Brandt_data

 link  threshold nobs logLik  AIC    niter max.grad cond.H 
 logit flexible  100  -152.47 316.94 6(0)  1.10e-07 6.9e+01

Coefficients:
         Estimate Std. Error z value Pr(&gt;|z|)
ExpCond1   0.2594     0.3606   0.719    0.472

Threshold coefficients:
    Estimate Std. Error z value
1|3  -4.4751     1.0181  -4.395
3|4  -1.7798     0.3403  -5.231
4|5  -1.0845     0.2921  -3.713
5|6   0.1309     0.2703   0.484
6|7   1.9504     0.3460   5.637</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a><span class="fu">confint</span>(brandt_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              2.5 %    97.5 %
ExpCond1 -0.4465061 0.9702407</code></pre>
</div>
</div>
<p>In the first segment of the output, its somewhat similar to the other models we have fitted, but there is no intercept at the top. We just have the slope coefficients for each predictor (1 in this case), then the threshold coefficients for <em>k</em>-1 scale points.</p>
<p>As this is an adapted version of logistic regression, the units are in log odds. So, they are easier to interpret as an odds ratio by taking the exponential.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1"></a><span class="fu">exp</span>(brandt_model2<span class="sc">$</span>beta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ExpCond1 
1.296112 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(brandt_model2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             2.5 %  97.5 %
ExpCond1 0.6398599 2.63858</code></pre>
</div>
</div>
<p>The results correspond with what we plotted previously, we have an odds ratio of 1.30 [0.64, 2.64], meaning there are 1.3 higher odds of a brighter rating in the unethical condition compared to the ethical condition. However, the confidence interval is pretty wide here and the <em>p</em>-value is not statistically significant, so we cannot conclude there is a shift in probability between the two groups here.</p>
<p>Returning to the idea of model comparison, it will not let us compare them using <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> as we cannot compare the same outcome when its numeric vs a factor. However, we can compare the AIC values for model fit between the two models. Lower values of AIC are better and if we subtract model 1 (the linear model) from model 2 (the ordinal model), a negative difference would indicate better model fit from the ordinal model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1"></a><span class="fu">AIC</span>(brandt_model2) <span class="sc">-</span> <span class="fu">AIC</span>(brandt_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -18.67021</code></pre>
</div>
</div>
<p>That does seem to be the case here. Although both models were non-significant, modelling the outcome as ordinal - reassuringly - fits the data better with less prediction error.</p>
<section id="breaking-down-threshold-coefficients" class="level4" data-number="5.3.4.1"><h4 data-number="5.3.4.1" class="anchored" data-anchor-id="breaking-down-threshold-coefficients">
<span class="header-section-number">5.3.4.1</span> Breaking down threshold coefficients</h4>
<p>We would normally focus on the coefficient as the main outcome of the modelling, but we can also break down the threshold coefficients so they are not a mystery. These represent the estimates for the cumulative probability of choosing a given scale point. These relate to the reference group, so we see the cumulative probability of the ethical condition. Remember, these are still in log odds, so we can calculate the probability like we did for logistic regression by dividing the odds ratio by 1 plus the odds ratio.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The code below uses <code><a href="https://rdrr.io/r/stats/coef.html">coef()</a></code> function and subsetting (the <code>[1]</code>etc.) to avoid writing out the numbers manually and reduce copy and paste errors. Try <code>coef(brandt_model2)</code> in the console to see the coefficients it returns.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1"></a><span class="co"># Cumulative percentage for ethical group choosing less than 3 - coefficient 1</span></span>
<span id="cb64-2"><a href="#cb64-2"></a><span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model2)[<span class="dv">1</span>]) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model2)[<span class="dv">1</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1|3 
0.01126058 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1"></a><span class="co"># Cumulative percentage for ethical group choosing less than 4 - coefficient 2</span></span>
<span id="cb66-2"><a href="#cb66-2"></a><span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model2)[<span class="dv">2</span>]) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model2)[<span class="dv">2</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      3|4 
0.1443283 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1"></a><span class="co"># Cumulative percentage for ethical group choosing less than 5- coefficient 3</span></span>
<span id="cb68-2"><a href="#cb68-2"></a><span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model2)[<span class="dv">3</span>]) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model2)[<span class="dv">3</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      4|5 
0.2526636 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1"></a><span class="co"># Cumulative percentage for ethical group choosing less than 6- coefficient 4</span></span>
<span id="cb70-2"><a href="#cb70-2"></a><span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model2)[<span class="dv">4</span>]) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model2)[<span class="dv">4</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      5|6 
0.5326661 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1"></a><span class="co"># Cumulative percentage for ethical group choosing less than 7- coefficient 5</span></span>
<span id="cb72-2"><a href="#cb72-2"></a><span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model2)[<span class="dv">5</span>]) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model2)[<span class="dv">5</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      6|7 
0.8754855 </code></pre>
</div>
</div>
<p>This means choosing less than 3 (remember no one responded 2) represents .011 or 1.12%. Choosing less than 4 represents .144 or 14.4%, and so on. Once we get to the final threshold, this represents less than 7 at .875/87.5%. The cumulative probability of 7 or less is then 1/100%, which is why you get <em>k</em>-1 thresholds. So, you can work that final step out as 1 - .875 = .125/12.5%.</p>
<p>These cumulative percentage estimates are for the reference group (ethical), so you could calculate the estimate for the unethical group by subtracting the slope coefficient (0.2594) from each threshold. For example, for the first threshold:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1"></a><span class="co"># Cumulative percentage for unethical group choosing less than 3</span></span>
<span id="cb74-2"><a href="#cb74-2"></a><span class="co"># Coefficient 1 minus coefficient 6 as the slope is weirdly the last one here, not the first</span></span>
<span id="cb74-3"><a href="#cb74-3"></a><span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model2)[<span class="dv">1</span>] <span class="sc">-</span> <span class="fu">coef</span>(brandt_model2)[<span class="dv">6</span>]) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model2)[<span class="dv">1</span>] <span class="sc">-</span> <span class="fu">coef</span>(brandt_model2)[<span class="dv">6</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1|3 
0.008710377 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>As before, we are using the <code><a href="https://rdrr.io/r/stats/coef.html">coef()</a></code> function and subsetting (the <code>[1]</code>etc.) to avoid writing out the numbers manually and reduce copy and paste errors. This time, we are using two coefficients to subtract the slope coefficient from each threshold coefficient. So, if you apply this to a new data set, make sure you check how many coefficients there are to subset them accurately.</p>
</div>
</div>
<p>This means the cumulative probability estimate for less than 3 is .0087 or 0.87% in the unethical group.</p>
</section><section id="different-threshold-assumptions" class="level4" data-number="5.3.4.2"><h4 data-number="5.3.4.2" class="anchored" data-anchor-id="different-threshold-assumptions">
<span class="header-section-number">5.3.4.2</span> Different threshold assumptions</h4>
<p>Finally, the default option in <pkg>ordinal</pkg> is for <code>flexible</code> thresholds between scale points. This estimates a coefficient for threshold and makes the fewest assumptions about the outcome. Alternative options are <code>equidistant</code> which assume evenly spaced scale points, or <code>symmetric</code> which assume scale points are evenly spaced above and below the scale center. These two make stronger assumptions about the outcome but require fewer parameters, so you would need to think carefully about whether they would suit the outcome you are modelling.</p>
<p>To see how the <code>equidistant</code> option would compare:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1"></a><span class="co"># clm = cumulative link model with equidistant thresholds</span></span>
<span id="cb76-2"><a href="#cb76-2"></a>brandt_model3 <span class="ot">&lt;-</span> <span class="fu">clm</span>(WellLitFactor <span class="sc">~</span> ExpCond, </span>
<span id="cb76-3"><a href="#cb76-3"></a>                     <span class="at">data =</span> Brandt_data, </span>
<span id="cb76-4"><a href="#cb76-4"></a>                     <span class="at">threshold =</span> <span class="st">"equidistant"</span>)</span>
<span id="cb76-5"><a href="#cb76-5"></a></span>
<span id="cb76-6"><a href="#cb76-6"></a><span class="fu">summary</span>(brandt_model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>formula: WellLitFactor ~ ExpCond
data:    Brandt_data

 link  threshold   nobs logLik  AIC    niter max.grad cond.H 
 logit equidistant 100  -158.95 323.90 5(0)  7.75e-11 8.3e+01

Coefficients:
         Estimate Std. Error z value Pr(&gt;|z|)
ExpCond1   0.2728     0.3583   0.761    0.447

Threshold coefficients:
            Estimate Std. Error z value
threshold.1  -3.7721     0.4394  -8.585
spacing       1.3626     0.1280  10.647</code></pre>
</div>
</div>
<p>This time, you only get one threshold estimate and a spacing parameter. Instead of calculating the cumulative probability at each threshold, you must successively add them together:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1"></a><span class="co"># Cumulative percentage for ethical group choosing less than 3 equally spaced</span></span>
<span id="cb78-2"><a href="#cb78-2"></a><span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model3)[<span class="dv">1</span>] <span class="sc">+</span> <span class="dv">0</span> <span class="sc">*</span> <span class="fu">coef</span>(brandt_model3)[<span class="dv">2</span>]) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model3)[<span class="dv">1</span>] <span class="sc">+</span> <span class="dv">0</span> <span class="sc">*</span> <span class="fu">coef</span>(brandt_model3)[<span class="dv">2</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>threshold.1 
 0.02248644 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1"></a><span class="co"># Cumulative percentage for ethical group choosing less than 4 equally spaced</span></span>
<span id="cb80-2"><a href="#cb80-2"></a><span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model3)[<span class="dv">1</span>] <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> <span class="fu">coef</span>(brandt_model3)[<span class="dv">2</span>]) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(brandt_model3)[<span class="dv">1</span>] <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> <span class="fu">coef</span>(brandt_model3)[<span class="dv">2</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>threshold.1 
 0.08245417 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1"></a><span class="co"># Etc. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section></section></section><section id="test-yourself" class="level2" data-number="5.4"><h2 data-number="5.4" class="anchored" data-anchor-id="test-yourself">
<span class="header-section-number">5.4</span> Test Yourself</h2>
<p>Now you have followed along to a guided example, it is important you can transfer your knowledge to a new scenario. So, we have a new data set for you to try out your understanding of these techniques on. Follow the instructions below and answer the questions. The solution is there to check your answers against, but make sure you try the activities independently first.</p>
<section id="independent-logistic-regression" class="level3" data-number="5.4.1"><h3 data-number="5.4.1" class="anchored" data-anchor-id="independent-logistic-regression">
<span class="header-section-number">5.4.1</span> Independent logistic regression</h3>
<p>For an independent activity, we will use the same data set from <span class="citation" data-cites="irving_correcting_2022">Irving et al. (<a href="references.html#ref-irving_correcting_2022" role="doc-biblioref">2022</a>)</span>, but this time using a different question as a binary outcome. If you are coming to this fresh, make sure to remind yourself of the data set outlined in the <a href="#logistic-regression">logistic regression section</a> and load the data.</p>
<div class="try">
<p>From here, apply what you learnt in the guided example for logistic regression to this new independent task and complete the questions below to check your understanding. Remember you are predicting <code>DV1_3</code> from <code>Condition</code> to see if the probability of a mistaken causal inference is greater in the correction condition compared to the no correction condition.</p>
<ul>
<li><p>The correction condition is a <select class="webex-select"><option value="blank"></option>
<option value="answer">significant</option>
<option value="x">non-significant</option></select> and <select class="webex-select"><option value="blank"></option>
<option value="x">positive</option>
<option value="answer">negative</option></select> predictor of the third mistaken causal inference question.</p></li>
<li><p>Rounding to two decimals, the slope coefficient converted to an odds ratio is <input class="webex-solveme nospaces" data-tol="0.001" size="4" data-answer="[&quot;0.09&quot;,&quot;.09&quot;]">. Taking the reciprocal, the odds ratio is <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer="[&quot;10.58&quot;]"> [lower 95% CI = <input class="webex-solveme nospaces" data-tol="0.001" size="4" data-answer="[&quot;2.85&quot;]">, upper 95% CI = <input class="webex-solveme nospaces" data-tol="0.001" size="4" data-answer="[&quot;68.8&quot;]">].</p></li>
<li><p>This suggests there are <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer="[&quot;10.58&quot;]"> lower odds of making a mistaken causal inference in the <select class="webex-select"><option value="blank"></option>
<option value="x">no correction</option>
<option value="answer">correction</option></select> condition compared to the <select class="webex-select"><option value="blank"></option>
<option value="answer">no correction</option>
<option value="x">correction</option></select> condition.</p></li>
<li><p>Rounding to three decimals, the estimated probability of making a mistaken causal inference in the no correction group is <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer="[&quot;0.258&quot;,&quot;.258&quot;]"> and the estimated probability of making a mistaken causal inference in the correction group is <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer="[&quot;0.032&quot;,&quot;.032&quot;]">.</p></li>
</ul>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>To produce a logistic regression model for the third causal question, we will predict <code>DV1_3</code> from <code>Condition</code> as a single predictor.</p>
</div>
</div>
</div>
</section><section id="independent-ordinal-regression" class="level3" data-number="5.4.2"><h3 data-number="5.4.2" class="anchored" data-anchor-id="independent-ordinal-regression">
<span class="header-section-number">5.4.2</span> Independent ordinal regression</h3>
<p>For an independent activity, we will use data from <span class="citation" data-cites="schroeder_sound_2015">Schroeder &amp; Epley (<a href="references.html#ref-schroeder_sound_2015" role="doc-biblioref">2015</a>)</span>. The aim of the study was to investigate whether delivering a short speech to a potential employer would be more effective at landing you a job than writing the speech down and the employer reading it themselves. Thirty-nine professional recruiters were randomly assigned to receive a job application speech as either a transcript for them to read, or an audio recording of the applicant reading the speech.</p>
<p>The recruiters then rated the applicants on perceived intellect, their impression of the applicant, and whether they would recommend hiring the candidate. All ratings were originally on a rating scale ranging from 0 (low intellect, impression etc.) to 10 (high impression, recommendation etc.), with the final value representing the mean across several items.</p>
<p>For this example, we will focus on the hire rating (variable <code>Hire_Rating</code> to see whether the audio condition had a would lead to higher ratings than the transcript condition (variable <code>CONDITION</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1"></a>schroeder_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Schroeder_hiring.csv"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb83-2"><a href="#cb83-2"></a>  <span class="fu">mutate</span>(<span class="at">condition =</span> <span class="fu">as.factor</span>(CONDITION))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try this
</div>
</div>
<div class="callout-body-container callout-body">
<p>From here, apply what you learnt in the guided example for ordinal regression to this new independent task and complete the questions below to check your understanding. Remember you will need to treat the outcome as a factor to fit the ordinal model. The answers are based on the default approach for estimating flexible thresholds.</p>
<ul>
<li><p>The experimental condition is a <select class="webex-select"><option value="blank"></option>
<option value="answer">significant</option>
<option value="x">non-significant</option></select> and <select class="webex-select"><option value="blank"></option>
<option value="answer">positive</option>
<option value="x">negative</option></select> predictor of hire rating.</p></li>
<li><p>Rounding to two decimals, the slope coefficient converted to an odds ratio is <input class="webex-solveme nospaces" data-tol="0.001" size="4" data-answer="[&quot;4.67&quot;]"> [lower 95% CI = <input class="webex-solveme nospaces" data-tol="0.001" size="4" data-answer="[&quot;1.44&quot;]">, upper 95% CI = <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer="[&quot;16.31&quot;]">].</p></li>
<li><p>This suggests there are <input class="webex-solveme nospaces" data-tol="0.001" size="4" data-answer="[&quot;4.67&quot;]"> higher odds of a larger hire rating in the <select class="webex-select"><option value="blank"></option>
<option value="x">transcript</option>
<option value="answer">audio</option></select> condition compared to the <select class="webex-select"><option value="blank"></option>
<option value="answer">transcript</option>
<option value="x">audio</option></select> condition.</p></li>
<li><p>Rounding to three decimals, the estimated cumulative probability for the transcript group choosing a hire rating of lower than 3 (hint: coefficient 3) is <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer="[&quot;0.498&quot;,&quot;.498&quot;]"> and the cumulative probability for the audio group choosing a hire rating of lower than 3 (hint: coefficient 3 minus coefficient 9) is <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer="[&quot;0.175&quot;,&quot;.175&quot;]">.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show me the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>First, we need to convert hire rating to a factor for the ordinal model to work.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1"></a>schroeder_data <span class="ot">&lt;-</span> schroeder_data <span class="sc">%&gt;%</span> </span>
<span id="cb84-2"><a href="#cb84-2"></a>  <span class="fu">mutate</span>(<span class="at">hire_factor =</span> <span class="fu">factor</span>(Hire_Rating))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can explore the distribution of the two groups and see there is a clearer difference here, with more low ratings in the transcript (<code>0</code>) group and more high ratings in the audio (<code>1</code>) group.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1"></a>schroeder_data <span class="sc">%&gt;%</span> </span>
<span id="cb85-2"><a href="#cb85-2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Hire_Rating, <span class="at">fill =</span> condition)) <span class="sc">+</span> </span>
<span id="cb85-3"><a href="#cb85-3"></a>  <span class="fu">geom_histogram</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span> </span>
<span id="cb85-4"><a href="#cb85-4"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">8</span>, <span class="at">name =</span> <span class="st">"Hire Rating"</span>) <span class="sc">+</span></span>
<span id="cb85-5"><a href="#cb85-5"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-glm_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Alternatively, we can visualise the cumulative probability and see how it climbs steeper for the transcript group (more lower responses) and shallow for the audio group (more higher responses).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1"></a>schroeder_data <span class="sc">%&gt;%</span> </span>
<span id="cb86-2"><a href="#cb86-2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Hire_Rating, <span class="at">colour =</span> condition)) <span class="sc">+</span> </span>
<span id="cb86-3"><a href="#cb86-3"></a>  <span class="fu">stat_ecdf</span>() <span class="sc">+</span></span>
<span id="cb86-4"><a href="#cb86-4"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">8</span>, <span class="at">name =</span> <span class="st">"Hire Rating"</span>) <span class="sc">+</span> </span>
<span id="cb86-5"><a href="#cb86-5"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.2</span>), <span class="at">name =</span> <span class="st">"Cumulative Percent"</span>) <span class="sc">+</span> </span>
<span id="cb86-6"><a href="#cb86-6"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-glm_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Finally, we can fit our ordinal regression model and see the slope coefficient is positive and it is statistically significant.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1"></a>schroeder_model2 <span class="ot">&lt;-</span> <span class="fu">clm</span>(hire_factor <span class="sc">~</span> condition, <span class="at">data =</span> schroeder_data)</span>
<span id="cb87-2"><a href="#cb87-2"></a></span>
<span id="cb87-3"><a href="#cb87-3"></a><span class="fu">summary</span>(schroeder_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>formula: hire_factor ~ condition
data:    schroeder_data

 link  threshold nobs logLik AIC    niter max.grad cond.H 
 logit flexible  39   -77.29 172.59 7(1)  5.69e-10 1.6e+02

Coefficients:
           Estimate Std. Error z value Pr(&gt;|z|)  
condition1   1.5409     0.6146   2.507   0.0122 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
     Estimate Std. Error z value
0|1 -2.364790   0.754794  -3.133
1|2 -0.761366   0.459091  -1.658
2|3 -0.009953   0.437700  -0.023
3|4  0.526688   0.459758   1.146
4|5  1.262387   0.504261   2.503
5|6  2.197283   0.575101   3.821
6|7  2.357000   0.589496   3.998
7|8  3.976969   0.861277   4.618</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1"></a><span class="fu">confint</span>(schroeder_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               2.5 %   97.5 %
condition1 0.3669235 2.791582</code></pre>
</div>
</div>
<p>To be easier to interpret, we can convert the log odds to the odds ratio by taking the exponential for the slope coefficient and its 95% confidence interval.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1"></a><span class="co"># Get beta as odds ratio instead of logit</span></span>
<span id="cb91-2"><a href="#cb91-2"></a><span class="fu">exp</span>(schroeder_model2<span class="sc">$</span>beta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>condition1 
  4.668953 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1"></a><span class="co"># Convert CI to odds ratio</span></span>
<span id="cb93-2"><a href="#cb93-2"></a><span class="fu">exp</span>(<span class="fu">confint</span>(schroeder_model2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              2.5 %  97.5 %
condition1 1.443288 16.3068</code></pre>
</div>
</div>
<p>Finally, as a demonstration, we can calculate the estimated cumulative probability of choosing a rating of less than 3 (0-2) for the transcript group and the audio group. Note we are using coefficient 3 as that is the third threshold. We then subtract coefficient 9 as the slope coefficient is added on to the end.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1"></a><span class="co"># Cumulative percentage for transcript group choosing less than 3 - coefficient 1</span></span>
<span id="cb95-2"><a href="#cb95-2"></a><span class="fu">exp</span>(<span class="fu">coef</span>(schroeder_model2)[<span class="dv">3</span>]) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(schroeder_model2)[<span class="dv">3</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      2|3 
0.4975119 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1"></a><span class="co"># Cumulative percentage for audio group choosing less than 3 - coefficient 1 minus coefficient 9</span></span>
<span id="cb97-2"><a href="#cb97-2"></a><span class="fu">exp</span>(<span class="fu">coef</span>(schroeder_model2)[<span class="dv">3</span>] <span class="sc">-</span> <span class="fu">coef</span>(schroeder_model2)[<span class="dv">9</span>]) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(schroeder_model2)[<span class="dv">3</span>] <span class="sc">-</span> <span class="fu">coef</span>(schroeder_model2)[<span class="dv">9</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      2|3 
0.1749581 </code></pre>
</div>
</div>
</div>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-bostyn_mice_2018" class="csl-entry" role="listitem">
Bostyn, D. H., Sevenhant, S., &amp; Roets, A. (2018). Of <span>Mice</span>, <span>Men</span>, and <span>Trolleys</span>: <span>Hypothetical</span> <span>Judgment</span> <span>Versus</span> <span>Real</span>-<span>Life</span> <span>Behavior</span> in <span>Trolley</span>-<span>Style</span> <span>Moral</span> <span>Dilemmas</span>: <em>Psychological Science</em>, <em>29</em>(7), 1084–1093. <a href="https://doi.org/10.1177/0956797617752640">https://doi.org/10.1177/0956797617752640</a>
</div>
<div id="ref-brandt_does_2014" class="csl-entry" role="listitem">
Brandt, M. J., IJzerman, H., &amp; Blanken, I. (2014). Does <span>Recalling</span> <span>Moral</span> <span>Behavior</span> <span>Change</span> the <span>Perception</span> of <span>Brightness</span>? <em>Social Psychology</em>, <em>45</em>(3), 246–252. <a href="https://doi.org/10.1027/1864-9335/a000191">https://doi.org/10.1027/1864-9335/a000191</a>
</div>
<div id="ref-Christensen2023" class="csl-entry" role="listitem">
Christensen, R. H. B. (2023). <em>Ordinal—regression models for ordinal data</em>. <a href="https://CRAN.R-project.org/package=ordinal">https://CRAN.R-project.org/package=ordinal</a>
</div>
<div id="ref-irving_correcting_2022" class="csl-entry" role="listitem">
Irving, D., Clark, R. W. A., Lewandowsky, S., &amp; Allen, P. J. (2022). Correcting statistical misinformation about scientific findings in the media: <span>Causation</span> versus correlation. <em>Journal of Experimental Psychology. Applied</em>. <a href="https://doi.org/10.1037/xap0000408">https://doi.org/10.1037/xap0000408</a>
</div>
<div id="ref-Lenth2022" class="csl-entry" role="listitem">
Lenth, R. V. (2024). <em>Emmeans: Estimated marginal means, aka least-squares means</em>. <a href="https://CRAN.R-project.org/package=emmeans">https://CRAN.R-project.org/package=emmeans</a>
</div>
<div id="ref-luedecke_2024" class="csl-entry" role="listitem">
Lüdecke, D. (2024). <em>sjPlot: Data visualization for statistics in social science</em>. <a href="https://CRAN.R-project.org/package=sjPlot">https://CRAN.R-project.org/package=sjPlot</a>
</div>
<div id="ref-schroeder_sound_2015" class="csl-entry" role="listitem">
Schroeder, J., &amp; Epley, N. (2015). The <span>Sound</span> of <span>Intellect</span>: <span>Speech</span> <span>Reveals</span> a <span>Thoughtful</span> <span>Mind</span>, <span>Increasing</span> a <span>Job</span> <span>Candidate</span>’s <span>Appeal</span>. <em>Psychological Science</em>, <em>26</em>(6), 877–891. <a href="https://doi.org/10.1177/0956797615572906">https://doi.org/10.1177/0956797615572906</a>
</div>
<div id="ref-voas_odds_2024" class="csl-entry" role="listitem">
Voas, D., &amp; Watt, L. (2024). The odds are it’s wrong: <span>Correcting</span> a common mistake in statistics. <em>Teaching Statistics</em>. <a href="https://doi.org/10.1111/test.12391">https://doi.org/10.1111/test.12391</a>
</div>
</div>
</section></section></main><!-- /main --><script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script><script>
// open rdrr links externally ----

var exlinks = document.querySelectorAll("a[href^='https://rdrr.io']");
var exlink_func = function(){
  window.open(this.href);
  return false;
};
for (var i = 0; i < exlinks.length; i++) {
    exlinks[i].addEventListener('click', exlink_func, false);
}

// visible second sidebar in mobile ----

function move_sidebar() {
  var toc = document.getElementById("TOC");
  var small_sidebar = document.querySelector("#quarto-sidebar .sidebar-menu-container");
  var right_sidebar = document.getElementById("quarto-margin-sidebar");

  if (window.innerWidth < 768) {
    small_sidebar.append(toc);
  } else {
    right_sidebar.append(toc);
  }
}
move_sidebar();
window.onresize = move_sidebar;
</script><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./04-screening-data.html" class="pagination-link" aria-label="Missing data, outliers, and checking assumptions">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Missing data, outliers, and checking assumptions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>CC-BY (2025) Bartlett, Rousselet, &amp; DeBruine.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>