{
  "hash": "0a4da33a35e7042cd69f5e1749c15ed5",
  "result": {
    "engine": "knitr",
    "markdown": "# Frequentist and Bayesian Mixed Effects Models\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\nIn the recordings, James walked through the building blocks of fitting and interpreting mixed effects models, first from a frequentist perspective and then from a Bayesian perspective. The data come from @brown_introduction_2021 who developed a tutorial for mixed effects models. Part 1 here uses the <pkg>lme4</pkg> package to fit frequentist mixed effects models. These take a little longer than normal, but still fit in a few seconds. Part 2 uses the <pkg>brms</pkg> package to fit Bayesian mixed effects models. You are welcome to fit these in your own time, but for the practical, I have provided the saved model objects as they take 15-30 minutes to fit depending on your computer. \n\nMake sure you have the following packages installed and loaded.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# general data functions\nlibrary(tidyverse)\n\n# frequentist \nlibrary(lme4)\nlibrary(lmerTest)\nlibrary(sjPlot)\n\n# Bayesian \nlibrary(brms)\nlibrary(bayestestR)\nlibrary(see)\nlibrary(tidybayes)\n```\n:::\n\n\n\n\n\nNow we have our packages, we need to read the data from Brown (2021) who report a repeated measures study on speech perception. Participants complete two tasks where they listen to words being spoken while they complete a response time task. The words are presented in two conditions: 1) just being spoken in an auditory condition and 2) being spoken and seeing the speaker in an audiovisual condition. Each participant completes the task for 543 words, split between the two conditions in a different order for each participant. They expected response times to be slower in the audiovisual condition compared to the audio condition due to the interference from listening. \n\nThis means we have a repeated measures / within-subjects design. The outcome is response time in milliseconds (ms). The predictor - or fixed effect - is the modality (audio and audiovisual). We will also explore the impact of participants and the word stimuli as random effects. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read the raw data from Brown (2021)\nbrown_data <- read_csv(\"Data/Brown_2021.csv\")\n\n# create a simplified version of the data by averaging over the word stimuli\nbrown_aggregate <- brown_data %>% \n  group_by(PID, modality) %>% \n  summarise(mean_RT = mean(RT)) %>% \n  ungroup()\n```\n:::\n\n\n\n\n\n## Frequentist \n\nIn the first section, we will explore how to fit mixed effects models using frequentist statistics and the <pkg>lme4</pkg> package [@Bates_lme4]. \n\n### Aggregate participants\n\nFor demonstration purposes, we are going to start slow with aggregate data and averaging over the words, leaving us with only a mean response time per condition. \n\n#### Standard linear model, no random effects\n\nWe can try and fit a standard linear model using `mean_RT` as the outcome and `modality` as the predictor. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrown_model0 <- lm(mean_RT ~ modality,\n                     data = brown_aggregate)\n\nsummary(brown_model0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean_RT ~ modality, data = brown_aggregate)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-319.57 -124.34  -24.35  107.35  605.71 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          1044.07      23.89  43.697   <2e-16 ***\nmodalityAudiovisual    83.16      33.79   2.461   0.0155 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 173.9 on 104 degrees of freedom\nMultiple R-squared:  0.05503,\tAdjusted R-squared:  0.04595 \nF-statistic: 6.057 on 1 and 104 DF,  p-value: 0.0155\n```\n\n\n:::\n:::\n\n\n\n\n\nAs you will see in upcoming models, the intercept and slope are \"accurate\" but the standard errors and degrees of freedom are all off. We have 53 participants but 104 degrees of freedom since we are not factoring in they contribute two observations. \n\n#### Random intercept for participants\n\nAfter the brief demonstration, we can fit our first mixed effects model. We have a new function called `lmer()` instead of `lm()`. This time, we have a similar formula to define `mean_RT` as the outcome and `modality` is still our main predictor. In a mixed effects model, we refer to this as a fixed effect. The new component is the `(1 | PID)` which represents our random effect. This is a random intercepts only model, where we are telling R to allow the intercept (the 1 part) vary for each participant (the PID part). \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrown_model1 <- lmer(mean_RT ~ modality + (1 | PID), \n                     data = brown_aggregate)\n\nsummary(brown_model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: mean_RT ~ modality + (1 | PID)\n   Data: brown_aggregate\n\nREML criterion at convergence: 1305.6\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.59477 -0.46495 -0.00148  0.37616  2.64062 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n PID      (Intercept) 26066    161.45  \n Residual              4192     64.74  \nNumber of obs: 106, groups:  PID, 53\n\nFixed effects:\n                    Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)          1044.07      23.89   59.70  43.697  < 2e-16 ***\nmodalityAudiovisual    83.16      12.58   52.00   6.612 2.05e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr)\nmodltyAdvsl -0.263\n```\n\n\n:::\n:::\n\n\n\n\n\nThe output for a mixed effects model is similar, but we have some new sections. Since we loaded the `lmerTest` package, we get p-values via the Satterthwaite method. The two key sections are the random effects and fixed effects. \n\nStarting with fixed effects, if you scroll up to the standard linear model, you will see the estimate the the intercept and slope are identical, but the standard error has decreased substantially now we have taken the within-subjects design into consideration. \n\nUnder random effects, we accurately code that there are 106 observations but 53 participants by defining the random effect. The standard deviation tells us that we expect the response time to vary by 161ms around the intercept of 1044ms, which relates to the response time towards audio stimuli. We only allowed the intercept to vary in this model, not the slope, so this tells us we fit a constant slope in the model but the intercept for each participant can move up and down. \n\nYou can see this clearer by accessing coefficient values which will print the random effects for each participant. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(brown_model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$PID\n    (Intercept) modalityAudiovisual\n301    978.4349            83.16029\n302   1006.3888            83.16029\n303    882.0067            83.16029\n304   1167.7371            83.16029\n306   1019.0060            83.16029\n307   1063.8531            83.16029\n308   1230.6380            83.16029\n309    781.2698            83.16029\n310   1176.8249            83.16029\n311    990.6904            83.16029\n312   1137.5894            83.16029\n313   1084.9800            83.16029\n314   1088.1276            83.16029\n315    858.5082            83.16029\n316   1336.9827            83.16029\n318    940.9711            83.16029\n319   1026.4853            83.16029\n320    999.6693            83.16029\n321   1052.4284            83.16029\n324   1056.8015            83.16029\n325    819.4797            83.16029\n326   1028.3805            83.16029\n328   1244.5444            83.16029\n329   1008.8456            83.16029\n331   1417.8641            83.16029\n333   1589.9694            83.16029\n334    955.2190            83.16029\n335   1153.5106            83.16029\n337    924.7565            83.16029\n338    841.0854            83.16029\n340   1180.4104            83.16029\n341    898.8564            83.16029\n342   1214.5150            83.16029\n343   1049.2312            83.16029\n344   1035.4302            83.16029\n346    883.4886            83.16029\n348    823.7689            83.16029\n349    935.0100            83.16029\n350   1172.5127            83.16029\n351   1176.7303            83.16029\n352    811.5272            83.16029\n353   1132.9344            83.16029\n354   1106.1102            83.16029\n355   1185.4441            83.16029\n356   1062.5312            83.16029\n357    918.9947            83.16029\n358    945.6114            83.16029\n359   1028.0600            83.16029\n360   1042.4988            83.16029\n361   1008.7396            83.16029\n362    947.0871            83.16029\n363    910.8909            83.16029\n364   1002.4373            83.16029\n\nattr(,\"class\")\n[1] \"coef.mer\"\n```\n\n\n:::\n:::\n\n\n\n\n\nThe intercept value changes for each participant as some are faster and some are slower on average. But then the slope estimate is identical for each participant. \n\nYou can also see this visually using the `sjPlot` package and `plot_model()` function. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_model(brown_model1, \n           type = \"re\") # plot random effects\n```\n\n::: {.cell-output-display}\n![](03-03-mixedeffects_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\n\nZero on this plot represents the fixed effect intercept of 1044ms. Each participant then represents a deviation from this as the random effect. Participants in red are below the intercept (i.e., they respond faster), whereas those in blue are above the intercept (i.e., they respond slower).\n\n### Trial-level data\n\nNow the function is a little less of a mystery, we can step things up and use mixed effects models to their full capability on trial-level data. If you explore the data, you can see the difference. In the aggregate data, participants contribute two rows:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(brown_aggregate)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| PID|modality    |   mean_RT|\n|---:|:-----------|---------:|\n| 301|Audio-only  | 1027.4106|\n| 301|Audiovisual | 1002.0642|\n| 302|Audio-only  | 1047.3455|\n| 302|Audiovisual | 1042.5323|\n| 303|Audio-only  |  882.6735|\n| 303|Audiovisual |  938.4381|\n\n</div>\n:::\n:::\n\n\n\n\n\nWhereas in the full data, participants contribute 543 rows, one for each word: \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(brown_data)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| PID|   RT|modality   |stim  |\n|---:|----:|:----------|:-----|\n| 301| 1024|Audio-only |gown  |\n| 301|  838|Audio-only |might |\n| 301| 1060|Audio-only |fern  |\n| 301|  882|Audio-only |vane  |\n| 301|  971|Audio-only |pup   |\n| 301| 1064|Audio-only |rise  |\n\n</div>\n:::\n:::\n\n\n\n\n\nThis means we can model the variability within both participants and different words, both of which we expect to sampled from wider distributions of participants and words. \n\n#### Random intercepts only\n\nAs we work towards fitting the \"maximal\" model, a useful starting point for conducting a likelihood ratio test later is fitting the random effects with no fixed effects. We are only modelling the variability of responses across participants and words. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrown_model2 <- lmer(RT ~ (1 | PID) + (1 | stim), \n                     data = brown_data)\n\nsummary(brown_model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: RT ~ (1 | PID) + (1 | stim)\n   Data: brown_data\n\nREML criterion at convergence: 303405.8\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.4561 -0.7030 -0.0292  0.5919  4.7565 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n stim     (Intercept)   330.6   18.18  \n PID      (Intercept) 28075.5  167.56  \n Residual             68943.6  262.57  \nNumber of obs: 21679, groups:  stim, 543; PID, 53\n\nFixed effects:\n            Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)  1086.42      23.10   52.14   47.03   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\nThe intercept represents the average across all trials - around 1086ms - by ignoring the fixed effect of modality. \n\n#### Modality and random intercepts\n\nIn the next model, we now add our fixed effect of modality. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrown_model3 <- lmer(RT ~ modality + (1 | PID) + (1 | stim), \n                     data = brown_data)\n\nsummary(brown_model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: RT ~ modality + (1 | PID) + (1 | stim)\n   Data: brown_data\n\nREML criterion at convergence: 302861.5\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.3572 -0.6949 -0.0205  0.5814  4.9120 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n stim     (Intercept)   360.2   18.98  \n PID      (Intercept) 28065.7  167.53  \n Residual             67215.3  259.26  \nNumber of obs: 21679, groups:  stim, 543; PID, 53\n\nFixed effects:\n                     Estimate Std. Error        df t value Pr(>|t|)    \n(Intercept)          1044.449     23.164    52.781   45.09   <2e-16 ***\nmodalityAudiovisual    82.525      3.529 21433.526   23.38   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr)\nmodltyAdvsl -0.078\n```\n\n\n:::\n:::\n\n\n\n\n\nThe estimates are pretty close to our aggregate model but now we are modelling the full study design from different sources of variables. The intercept for the audio modality is 1044ms and we expect the audiovisual modality to have 83ms slower responses on average. \n\nIf you look at random effects, we have two key standard deviations to explore. We estimate participants' intercepts to vary by around 168ms but only around 19ms for word stimuli. This means the responses of different participants are more variable than different stimuli. \n\nAs before, we can visualise the random effects to see the broad pattern of variability. Just keep in mind, when we have a huge number of stimuli like the words, the plot can be difficult to distinguish different elements. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_model(brown_model3, \n           type = \"re\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](03-03-mixedeffects_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[2]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](03-03-mixedeffects_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n:::\n\n\n\n\n\n#### Modality, random intercepts, and slopes\n\nThe final model we will fit is the \"maximal\" model for our design, where we allow both the intercept **and** slope to vary. You can see the different syntax where a random intercept has the format `(1 | random_effect)`, whereas random intercept and slopes has the format `(1 + fixed_effect | random_effect)`. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrown_model4 <- lmer(RT ~ modality + (1 + modality | PID) + (1 + modality | stim), \n                     data = brown_data)\n\nsummary(brown_model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: RT ~ modality + (1 + modality | PID) + (1 + modality | stim)\n   Data: brown_data\n\nREML criterion at convergence: 302385.7\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.3646 -0.6964 -0.0140  0.5886  5.0003 \n\nRandom effects:\n Groups   Name                Variance Std.Dev. Corr \n stim     (Intercept)           304.0   17.44        \n          modalityAudiovisual   216.6   14.72   0.16 \n PID      (Intercept)         28554.1  168.98        \n          modalityAudiovisual  7709.1   87.80   -0.17\n Residual                     65258.8  255.46        \nNumber of obs: 21679, groups:  stim, 543; PID, 53\n\nFixed effects:\n                    Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)          1044.14      23.36   52.13  44.703  < 2e-16 ***\nmodalityAudiovisual    83.18      12.57   52.10   6.615 2.02e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr)\nmodltyAdvsl -0.178\n```\n\n\n:::\n:::\n\n\n\n\n\nThe random effects structure now has four key rows. We can look at the standard deviation around the intercept for word stimuli (17ms) and it's slope (15ms). Likewise, we can explore the intercept for participants (169ms) and it's slope (88ms). We are now allowing both the response time for audio stimuli to vary for each participant and stimulus (intercepts) and the difference to audiovisual stimuli (slopes). \n\nFor a completely wild graph, you can now see four panels for the random intercept and slope for each random effect. The same interpretation applies where 0 represents the fixed effect value, and values above and below are deviations from this for each level of the random effect. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_model(brown_model4, \n           type = \"re\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](03-03-mixedeffects_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[2]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](03-03-mixedeffects_files/figure-html/unnamed-chunk-14-2.png){width=672}\n:::\n:::\n\n\n\n\n\n#### Model comparison\n\nThe final step here is considering model comparison. We can ask questions such as \"does modality have an effect on response times?\" and \"is this more complicated model worthwhile?\". \n\nBy fitting the three models to our trial-level data, we can pass them to the `anova()` function. This is known as a likelihood ratio test. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(brown_model2, \n      brown_model3, \n      brown_model4)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrefitting model(s) with ML (instead of REML)\n```\n\n\n:::\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|             | npar|      AIC|      BIC|    logLik| deviance|    Chisq| Df| Pr(>Chisq)|\n|:------------|----:|--------:|--------:|---------:|--------:|--------:|--:|----------:|\n|brown_model2 |    4| 303421.9| 303453.9| -151707.0| 303413.9|       NA| NA|         NA|\n|brown_model3 |    5| 302884.0| 302923.9| -151437.0| 302874.0| 539.9420|  1|          0|\n|brown_model4 |    9| 302418.7| 302490.5| -151200.3| 302400.7| 473.3161|  4|          0|\n\n</div>\n:::\n:::\n\n\n\n\n\nYou can see the warning about it refitting the models using maximum likelihood instead of restricted maximum likelihood. We could do this manually by adding the argument `REML = FALSE` to the `lmer()` function. \n\nWe can see the difference between model 2 (random effects only) and model 3 (modality as a fixed effect and random intercepts) is statistically significant and we have a lower AIC value. Modality does have an effect on response times. The difference between model 3 and model 4 (random intercepts and slopes) is also significant. Even though model 4 is the most complex (9 parameters to estimate), it is a better fitting model relative to it's complexity. \n\n## Bayesian \n\nNow we have fitted the models using <pkg>lme4</pkg> and frequentist statistics, we can apply that understanding to fitting Bayesian mixed effects models using the <pkg>brms</pkg> package [@burkner_brms_2017]. \n\nAs an initial warning, these models are going to take 15-30 minutes to run on your computer. I have provided the model objects for you to work with quickly, but they are quite computationally expensive to run yourself. This is also why I have focused on the random intercept only model, purely for pragmatic reasons. It takes up to an hour to fit a random intercept and slope model for these data. The formula structure is identical though, so are you are welcome to try and fit the \"maximal\" model yourself. \n\n### Default priors \n\nWe will start by fitting a model with default priors to explore the main difference in using <pkg>brms</pkg> compared to <pkg>lme4</pkg>. We can define our descriptive model as: \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrown_intercept_model <- bf(RT ~ modality + (1 | PID) + (1 | stim)) \n```\n:::\n\n\n\n\n\nWe can pass that to the `brm()` function without specifying priors to update to our posterior probability distributions. You can download the model objects to speed things up, or it will save the model objects to your computer in a \"Models\" sub-folder if you do not have it saved. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrown_default_priors <- brm(formula = brown_intercept_model, \n                            family = gaussian(), \n                            data = brown_data, \n                              file = \"Models/brown_default_priors\")\n\nsummary(brown_default_priors)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: RT ~ modality + (1 | PID) + (1 | stim) \n   Data: brown_data (Number of observations: 21679) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nMultilevel Hyperparameters:\n~PID (Number of levels: 53) \n              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsd(Intercept)   169.56     16.59   141.56   205.40 1.00      634     1322\n\n~stim (Number of levels: 543) \n              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsd(Intercept)    18.22      3.72     9.25    24.62 1.00      942      670\n\nRegression Coefficients:\n                    Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept            1040.69     22.97   996.04  1087.17 1.01      263      604\nmodalityAudiovisual    82.52      3.57    75.46    89.66 1.00    10771     2504\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma   259.30      1.25   256.86   261.75 1.00     6120     2854\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n\n\n\nThe organisation of <pkg>brms</pkg> models is similar where we have model fitting information, random effects (but here called fancy multilevel hyperparameters), and fixed effects. The interpretation is identical but given we are working in a Bayesian framework, each parameter in the model is subject to it's own posterior distribution. \n\nOur estimates are similar to the frequentist equivalents but there are some potential problems we have not encountered in previous Bayesian models, given we are now working with more complex models. The R-hat values are all good but several effect sample size values are far too small in the low hundreds. \n\nWe will not explore everything for this default prior model, but we can explore the posteriors and trace plots. The intercept seems to be the most problematic following the low effective sample size values, with the plot here looking particularly choppy. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(brown_default_priors)\n```\n\n::: {.cell-output-display}\n![](03-03-mixedeffects_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n\n\nThe final thing we will look at here is the posterior predictive check to make sure assuming normality is a reasonable choice. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(brown_default_priors, \n         ndraws = 100)\n```\n\n::: {.cell-output-display}\n![](03-03-mixedeffects_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n\n\nBrown (2021) notes in the tutorial that the response time data have been edited to be more suitable for teaching contexts. Presumably this is making them look a little more normal or the responses are just much slower here, as a normal distribution suits the data quite well. Normally, they have characteristic skew where you need to consider something like a gamma distribution. \n\n### Informed priors\n\nThe model we will explore in a little more detail is setting informed priors for the parameters we can set reasonable expectations on. Using our descriptive model and data, we can see what <pkg>brms</pkg> will let us set priors on. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_prior(brown_intercept_model, \n          data = brown_data)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|prior                     |class     |coef                |group |resp |dpar |nlpar |lb |ub |source  |\n|:-------------------------|:---------|:-------------------|:-----|:----|:----|:-----|:--|:--|:-------|\n|                          |b         |                    |      |     |     |      |   |   |default |\n|                          |b         |modalityAudiovisual |      |     |     |      |   |   |default |\n|student_t(3, 1057, 289.1) |Intercept |                    |      |     |     |      |   |   |default |\n|student_t(3, 0, 289.1)    |sd        |                    |      |     |     |      |0  |   |default |\n|                          |sd        |                    |PID   |     |     |      |   |   |default |\n|                          |sd        |Intercept           |PID   |     |     |      |   |   |default |\n|                          |sd        |                    |stim  |     |     |      |   |   |default |\n|                          |sd        |Intercept           |stim  |     |     |      |   |   |default |\n|student_t(3, 0, 289.1)    |sigma     |                    |      |     |     |      |0  |   |default |\n\n</div>\n:::\n:::\n\n\n\n\n\nIn a mixed effects model, we have more parameters than we have set so far. We have our standard intercept, slope, and sigma. We also have standard deviation parameters for our two random effects. It looks busier than it really is as <pkg>brms</pkg> will allow you to set priors on all standard deviation parameters or specify individual parameters. \n\nFor our model, we can use Brown and Strand (2019), a previous article from the tutorial author where they reported a similar study. It is very rare to see people reporting values for sigma or standard deviations, so we are just going to focus on setting priors for the intercept and slope. We do not have enough subject knowledge to set the other priors. \n\nIn Brown and Strand (2019), they report descriptive statistics for the mean response time to audio stimuli between 998ms and 1089ms, with an SD between 161 and 203. We can use this information to set a prior for the intercept. There are other predictors in the models they fit, but modality ranged between 21ms and 48ms slower for audiovisual stimuli. The larger effects were statistically significant and the smaller effects were non-significant, so we can bake in a wide range of uncertainty to expect positive values for the slope, but include some negative values for the non-signicant effects. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrown_priors <- set_prior(\"normal(35, 20)\", class = \"b\") + \n  set_prior(\"normal(1040, 180)\", class = \"Intercept\")\n\nbrown_priors %>% \n  parse_dist() %>% # Function from tidybayes/ggdist to turn prior into a dataframe\n  mutate(prior_label = paste0(class, \": \", prior)) %>% # add the class and prior\n  ggplot(aes(y = 0, dist = .dist, args = .args, fill = prior_label)) + # Fill in details from prior and add fill\n  stat_slab(normalize = \"panels\") + # ggdist layer to visualise distributions\n  scale_fill_viridis_d(option = \"plasma\", end = 0.9) + # Add colour scheme\n  guides(fill = \"none\") + # Remove legend for fill\n  facet_wrap(~prior_label, scales = \"free\") + # Split into a different panel for each prior\n  labs(x = \"Value\", y = \"Density\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](03-03-mixedeffects_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\n\n\nNow we have our priors, we can refit the model. Given the effect sample size values, I also increased the number of iterations. This will produce 8000 post-warmup draws instead of 4000 to try and increase the effective sample size.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrown_informed_priors <- brm(formula = brown_intercept_model, \n                             prior = brown_priors,\n                            family = gaussian(), \n                            data = brown_data, \n                            iter = 4000,\n                            file = \"Models/brown_informed_priors\")\n\nsummary(brown_informed_priors)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: RT ~ modality + (1 | PID) + (1 | stim) \n   Data: brown_data (Number of observations: 21679) \n  Draws: 4 chains, each with iter = 4000; warmup = 2000; thin = 1;\n         total post-warmup draws = 8000\n\nMultilevel Hyperparameters:\n~PID (Number of levels: 53) \n              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsd(Intercept)   171.76     16.76   143.16   208.65 1.00     1173     2384\n\n~stim (Number of levels: 543) \n              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsd(Intercept)    18.22      3.77     9.57    24.70 1.00     1713     1266\n\nRegression Coefficients:\n                    Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept            1043.64     23.27   998.27  1089.81 1.01      387      928\nmodalityAudiovisual    81.08      3.45    74.28    87.85 1.00    21349     5464\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma   259.32      1.25   256.87   261.79 1.00    16344     5110\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n\n\n\nSetting priors and increasing the number of iterations has helped the model, but it is still quite ideal. Really, you would want to keep on tweaking the model until the effect sample size was in the high hundreds for the intercept, but it is improved for all the other parameters. Low effective sample size points to potentially unreliable parameter estimates but we will explore this one in the interests of time given the estimates are so close to the frequentist versions. \n\nThe posteriors and trace plots look similar, with the intercept just looking a little choppy. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(brown_informed_priors)\n```\n\n::: {.cell-output-display}\n![](03-03-mixedeffects_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n\n\nOne helpful type of plot is superimposing the prior with the probability of direction, to look at the consistency between the choice of prior and the posterior. If there is a mismatch, it does not automatically mean there is a problem, but it at least prompts you to reflect and ask questions of your model choices. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(p_direction(brown_informed_priors), \n     priors = TRUE)\n```\n\n::: {.cell-output-display}\n![](03-03-mixedeffects_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n\n\nHere, we can see the slope estimate is firmly positive with quite a narrow posterior compared to the prior we set. We allowed a wide range given the previous study, so the data have been the dominant force here. \n\nIf we wanted to plot the model predictions and help communicate our findings, we can take the conditional effects plot and tidy things up a little. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconditional_plot <- conditional_effects(brown_informed_priors)\n\nplot(conditional_plot, \n     plot = FALSE)[[1]] + #I don't know why you need this, but it doesn't work without\n  theme_classic() + \n  scale_y_continuous(limits = c(900, 1200), \n                     breaks = seq(900, 1200, 50)) + \n  labs(x = \"Modality\", \n       y = \"Response Time (ms)\")\n```\n\n::: {.cell-output-display}\n![](03-03-mixedeffects_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n\n\nThere is not anything different to the descriptive model, but we can run the posterior predictive check just to follow the process. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(brown_informed_priors, \n         ndraws = 100)\n```\n\n::: {.cell-output-display}\n![](03-03-mixedeffects_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "03-03-mixedeffects_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}